#!/usr/bin/env node
/* Builds the Field Apps bundles shipped with the desktop: fieldapps/apps/<id>/{manifest.json, <id>.html, <id>.css, <id>.js, *-engine.js}
 * → fieldapps/apps/<id>.app.js  (window.FA_APPS['<id>'] = { manifest, code }) — one self-contained HTML string, nothing loaded
 * from the network (the runtime shell seals the frame). The Order Pad engine (om/om-engine.js) is inlined into apps that list it.
 *   node fieldapps/build-app.js            build every app
 *   node fieldapps/build-app.js --check    fail when a built file is out of date (CI) */
'use strict';
var fs = require('fs'), path = require('path');
var root = path.join(__dirname, '..');
var appsDir = path.join(__dirname, 'apps');
var check = process.argv.indexOf('--check') >= 0;
var APPS = {
    pos: { engines: ['om/om-engine.js', 'fieldapps/apps/pos/pos-engine.js'] }
};
function read(p) { return fs.readFileSync(path.join(root, p), 'utf8'); }
function build(id) {
    var dir = 'fieldapps/apps/' + id + '/';
    var manifest = JSON.parse(read(dir + 'manifest.json'));
    var tpl = read(dir + id + '.html'), css = read(dir + id + '.css'), js = read(dir + id + '.js');
    var engines = (APPS[id].engines || []).map(function (p) { return '<script>\n' + read(p).replace(/<\/script/gi, '<\\/script') + '\n</script>'; }).join('\n');
    var html = tpl.replace('<!-- @css -->', '<style>\n' + css + '\n</style>')
        .replace('<!-- @engine -->', engines)
        .replace('<!-- @js -->', '<script>\n' + js.replace(/<\/script/gi, '<\\/script') + '\n</script>');
    manifest.id = manifest.id || id;
    manifest.builtAt = undefined;
    var out = '/* generated by fieldapps/build-app.js from fieldapps/apps/' + id + '/ — do not edit */\n' +
        'window.FA_APPS = window.FA_APPS || {};\n' +
        'window.FA_APPS[' + JSON.stringify(id) + '] = { manifest: ' + JSON.stringify(manifest) + ', code: ' + JSON.stringify(html).replace(/<\/script/gi, '<\\/script') + ' };\n';
    var file = path.join(appsDir, id + '.app.js');
    var old = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (check) {
        if (old !== out) { console.error('fieldapps/apps/' + id + '.app.js is out of date — run: node fieldapps/build-app.js'); process.exitCode = 1; }
        else console.log(id + '.app.js is up to date (' + out.length + ' chars)');
        return;
    }
    fs.writeFileSync(file, out);
    console.log('built fieldapps/apps/' + id + '.app.js (' + Math.round(out.length / 1024) + ' KB, html ' + Math.round(html.length / 1024) + ' KB)');
}
Object.keys(APPS).forEach(build);
