using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace WMSApp.MRA
{
    /// <summary>
    /// One row in APEX WMS_MRA_INTERFACE_STATUS for every MRA interface run, whoever started it (WMS MRA button, Shipping Agent
    /// Print Trip, WMS 2.0, AI Digital Employee, AI Agent, Order Management) — written from MRAProcessor.ProcessMRAInterfaceAsync,
    /// so no caller can skip it. Status SUCCESS / FAILED / SKIPPED (order type not interfaced) / ALREADY_DONE (MRA had it).
    /// The row keeps the order header as the summary report returned it, the JSON sent to MRA and MRA's answer.
    /// Writes go through the guarded APEX gateway (ai/executewrite). A write that fails is kept in
    /// %APPDATA%\GraysWMS\mra_status_pending.sql and sent again with the next run, so a row is never lost to a network blip.
    /// Table: apex_sql/90_mra_interface_status.sql (also created here on first use).
    /// </summary>
    public static class MRAInterfaceStatus
    {
        public const string TABLE = "WMS_MRA_INTERFACE_STATUS";
        internal const string DDL =
            "CREATE TABLE wms_mra_interface_status (" +
            "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_date DATE DEFAULT SYSDATE, started_at DATE, " +
            "instance_name VARCHAR2(20), trip_id VARCHAR2(50), order_number VARCHAR2(60), header_id VARCHAR2(40), order_type VARCHAR2(100), order_date DATE, " +
            "customer_number VARCHAR2(60), customer_name VARCHAR2(400), customer_brn VARCHAR2(60), customer_vat VARCHAR2(60), mra_customer_cat VARCHAR2(60), " +
            "currency VARCHAR2(10), order_amount NUMBER, tax_amount NUMBER, discount_amount NUMBER, line_count NUMBER, invoice_type VARCHAR2(10), " +
            "mra_interface_id VARCHAR2(200), mra_interface_status VARCHAR2(20), failed_step VARCHAR2(40), failed_reason VARCHAR2(4000), gateway_problem VARCHAR2(20), " +
            "http_status NUMBER, fusion_updated VARCHAR2(1), source VARCHAR2(30), batch_id VARCHAR2(100), app_user VARCHAR2(100), machine VARCHAR2(100), " +
            "duration_ms NUMBER, timings VARCHAR2(1000), order_header_json CLOB, mra_request_json CLOB, mra_response_json CLOB)";
        internal static readonly string[] AFTER_DDL =
        {
            "CREATE INDEX wms_mra_if_status_n1 ON wms_mra_interface_status (order_number, created_date)",
            "CREATE INDEX wms_mra_if_status_n2 ON wms_mra_interface_status (trip_id, instance_name)",
            "CREATE INDEX wms_mra_if_status_n3 ON wms_mra_interface_status (created_date, mra_interface_status)",
        };

        private static Task _ensure;
        private static readonly object _lock = new object();
        private static readonly SemaphoreSlim _fileLock = new SemaphoreSlim(1, 1);
        private static string PendingFile => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "GraysWMS", "mra_status_pending.sql");

        private static Task EnsureAsync(string user)
        {
            lock (_lock) { if (_ensure == null || _ensure.IsFaulted) _ensure = EnsureCoreAsync(user); return _ensure; }
        }
        private static async Task EnsureCoreAsync(string user)
        {
            var have = await AiControl.QueryAsync("SELECT table_name FROM user_tables WHERE table_name = '" + TABLE + "'", user).ConfigureAwait(false);
            if (have.Count > 0) return;
            await AiControl.WriteAsync(DDL, user).ConfigureAwait(false);
            foreach (var d in AFTER_DDL) { try { await AiControl.WriteAsync(d, user).ConfigureAwait(false); } catch { /* index exists */ } }
        }

        private static string Pick(Dictionary<string, object> h, params string[] names)
        {
            if (h == null) return null;
            foreach (var n in names)
                foreach (var kv in h)
                    if (string.Equals(kv.Key, n, StringComparison.OrdinalIgnoreCase) && kv.Value != null && Convert.ToString(kv.Value, System.Globalization.CultureInfo.InvariantCulture).Trim() != "")
                        return Convert.ToString(kv.Value, System.Globalization.CultureInfo.InvariantCulture).Trim();
            return null;
        }
        private static double? Number(string s) => double.TryParse(s, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var d) ? d : (double?)null;
        private static string Date(string s)
        {
            if (string.IsNullOrEmpty(s) || !DateTime.TryParse(s, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var d)) return "NULL";
            return "TO_DATE('" + d.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture) + "', 'YYYY-MM-DD HH24:MI:SS')";
        }

        /// <summary>Builds and writes the row; never throws (MRA itself has already finished).</summary>
        internal static async Task RecordAsync(MRAProcessor p, MRAProcessingResult r, Dictionary<string, object> header, int lineCount,
            MRAInvoiceCreationResult inv, bool already, bool fusionUpdated, DateTime started, long ms)
        {
            try
            {
                string status = r.Success ? "SUCCESS" : r.Skipped ? "SKIPPED" : already ? "ALREADY_DONE" : "FAILED";
                string step = status != "FAILED" ? null
                    : inv != null && inv.Success && !fusionUpdated ? "UpdatingFusionOrder"
                    : inv != null && !inv.Success ? "CreatingMRAInvoice"
                    : header == null ? "FetchingOrderSummary"
                    : lineCount == 0 ? "FetchingOrderDetails"
                    : "ValidatingOrderLines";
                if (status == "FAILED" && header != null && r.Message != null && r.Message.StartsWith("Order type", StringComparison.OrdinalIgnoreCase)) step = "CheckingOrderType";
                string reason = status == "SUCCESS" ? null : (r.Message ?? "") + (string.IsNullOrEmpty(r.ErrorDetails) || r.ErrorDetails.Contains(" at ") ? "" : " · " + r.ErrorDetails);
                double? amount = Number(Pick(header, "ORDER_AMOUNT"));
                string invType = header == null ? null : Pick(header, "ORDER_TYPE_CODE") == "PRO-FORMA INVOICE" ? "PRF" : amount < 0 ? "CRN" : "STD";
                string user = string.IsNullOrWhiteSpace(p.AppUser) ? Environment.UserName : p.AppUser;
                string order = Lit(r.OrderNumber, 60);
                string trip = !string.IsNullOrWhiteSpace(p.TripId) ? Lit(p.TripId, 50)
                    : "(SELECT TO_CHAR(MAX(t.trip_id)) FROM wms_trip_details t WHERE TRIM(t.order_number) = " + order + " AND t.trip_id <> 9999)";
                string headerJson = header == null ? null : JsonConvert.SerializeObject(header);

                string Sql(string tripExpr) =>
                    "INSERT INTO wms_mra_interface_status (started_at, instance_name, trip_id, order_number, header_id, order_type, order_date, customer_number, customer_name, " +
                    "customer_brn, customer_vat, mra_customer_cat, currency, order_amount, tax_amount, discount_amount, line_count, invoice_type, mra_interface_id, mra_interface_status, " +
                    "failed_step, failed_reason, gateway_problem, http_status, fusion_updated, source, batch_id, app_user, machine, duration_ms, timings, order_header_json, mra_request_json, mra_response_json) " +
                    "SELECT " + Date(started.ToString("o")) + ", " + Lit(p.Instance, 20) + ", " + tripExpr + ", " + order + ", " + Lit(r.HeaderId ?? Pick(header, "HEADER_ID"), 40) + ", " +
                    Lit(Pick(header, "ORDER_TYPE_CODE", "ORDER_TYPE"), 100) + ", " + Date(Pick(header, "ORDER_DATE")) + ", " +
                    Lit(Pick(header, "ACCOUNT_NUMBER", "CUSTOMER_NUMBER", "CUST_ACCOUNT_NUMBER", "BILL_TO_ACCOUNT_NUMBER", "PARTY_NUMBER"), 60) + ", " +
                    Lit(Pick(header, "ACCOUNT_NAME", "CUSTOMER_NAME", "PARTY_NAME"), 400) + ", " + Lit(Pick(header, "BRN"), 60) + ", " + Lit(Pick(header, "VATREGNO"), 60) + ", " +
                    Lit(Pick(header, "MRA_CUSTOMER_CAT"), 60) + ", " + Lit(Pick(header, "CURRENCY_CODE", "CURRENCY") ?? (header != null ? "MUR" : null), 10) + ", " +
                    AiControl.Num(amount) + ", " + AiControl.Num(Number(Pick(header, "TAX_AMOUNT"))) + ", " + AiControl.Num(Number(Pick(header, "DISCOUNT_AMOUNT"))) + ", " +
                    (header == null ? "NULL" : lineCount.ToString(System.Globalization.CultureInfo.InvariantCulture)) + ", " + Lit(invType, 10) + ", " +
                    Lit(r.IrnCode ?? inv?.IrnCode, 200) + ", " + Lit(status, 20) + ", " + Lit(step, 40) + ", " + Lit(reason, 4000) + ", " + Lit(r.GatewayProblem, 20) + ", " +
                    AiControl.Num((double?)inv?.HttpStatus) + ", " + Lit(inv == null ? null : fusionUpdated ? "Y" : "N", 1) + ", " + Lit(p.Source, 30) + ", " + Lit(p.OrderTypesBatch, 100) + ", " +
                    Lit(user, 100) + ", " + Lit(Environment.MachineName, 100) + ", " + ms.ToString(System.Globalization.CultureInfo.InvariantCulture) + ", " + Lit(r.Timings, 1000) + ", " +
                    Clob(headerJson) + ", " + Clob(inv?.RequestJson) + ", " + Clob(inv?.RawResponse) + " FROM dual";

                var write = WriteAsync(Sql(trip), Sql("NULL"), user);
                await Task.WhenAny(write, Task.Delay(15000)).ConfigureAwait(false);
            }
            catch (Exception ex) { System.Diagnostics.Debug.WriteLine("[MRA status] not recorded: " + ex.Message); }
        }

        private static string Lit(string s, int max) => AiControl.Lit(s, max);
        private static string Clob(string s) => string.IsNullOrEmpty(s) ? "NULL" : AiControl.Clob(s);

        /// <summary>Sends pending rows first, then this one; the trip lookup is dropped if WMS_TRIP_DETAILS refuses it. Unsent → pending file.</summary>
        private static async Task WriteAsync(string sql, string sqlNoTrip, string user)
        {
            try { await EnsureAsync(user).ConfigureAwait(false); } catch (Exception ex) { System.Diagnostics.Debug.WriteLine("[MRA status] table check: " + ex.Message); }
            await FlushPendingAsync(user).ConfigureAwait(false);
            try { await AiControl.WriteAsync(sql, user).ConfigureAwait(false); return; }
            catch (Exception ex) { System.Diagnostics.Debug.WriteLine("[MRA status] insert: " + ex.Message); }
            try { await AiControl.WriteAsync(sqlNoTrip, user).ConfigureAwait(false); return; }
            catch (Exception ex) { System.Diagnostics.Debug.WriteLine("[MRA status] insert (no trip): " + ex.Message); }
            await _fileLock.WaitAsync().ConfigureAwait(false);
            try { Directory.CreateDirectory(Path.GetDirectoryName(PendingFile)); File.AppendAllText(PendingFile, sqlNoTrip.Replace("\r", " ").Replace("\n", " ") + "\n"); }
            catch { /* nowhere to keep it */ }
            finally { _fileLock.Release(); }
        }
        private static async Task FlushPendingAsync(string user)
        {
            await _fileLock.WaitAsync().ConfigureAwait(false);
            try
            {
                if (!File.Exists(PendingFile)) return;
                var left = new List<string>();
                foreach (var line in File.ReadAllLines(PendingFile).Where(l => l.StartsWith("INSERT INTO wms_mra_interface_status", StringComparison.Ordinal)))
                {
                    if (left.Count > 0) { left.Add(line); continue; }   // the gateway is down again: keep the rest for next time
                    try { await AiControl.WriteAsync(line, user).ConfigureAwait(false); } catch { left.Add(line); }
                }
                if (left.Count == 0) File.Delete(PendingFile); else File.WriteAllLines(PendingFile, left);
            }
            catch (Exception ex) { System.Diagnostics.Debug.WriteLine("[MRA status] pending: " + ex.Message); }
            finally { _fileLock.Release(); }
        }
    }
}
