/* Finance Lens — understanding the numbers: what a KPI means, how it is worked out (formula → statement lines → windows →
   accounts, with this period's numbers), and the company's health (KPIs scored against bands in pillars) with the data that
   is still missing for a complete picture and where to get it. Engine: FINE.kpiExplain / FINE.health / FINE.HEALTH. */
(function () {
    /** Plain-language meaning of the starter KPIs (a KPI's own description wins) */
    FL.KPI_GUIDE = {
        rev: 'Sales after returns and discounts since the start of the financial year.',
        rev_g: 'How much more (or less) was sold this year to date than in the same months last year.',
        gm: 'Of every 100 of sales, what is left after the direct cost of the goods sold. Higher is better.',
        ebitda: 'Operating profit before depreciation, interest and tax — roughly the cash the operations earn.',
        ebitda_m: 'EBITDA for every 100 of sales.',
        np: 'Bottom-line profit after every cost, interest and tax, year to date.',
        npm: 'Net profit for every 100 of sales.',
        np_m: 'Net profit of the selected month only.',
        opex_r: 'Overheads (operating expenses) for every 100 of sales. Lower is better.',
        staff_r: 'Staff costs for every 100 of sales.',
        dist_r: 'Distribution costs for every 100 of sales.',
        cogs_r: 'Cost of the goods sold for every 100 of sales.',
        rev_bud: 'Sales against the budget for the same months: 100 % = on budget.',
        opex_bud: 'Operating expenses against budget: above 100 % = overspending.',
        np_bud: 'Net profit against budget.',
        fy_burn: 'How much of the full-year expense budget is already used.',
        cash: 'Money in the bank and in hand at the period end.',
        cr: 'Can short-term assets (cash, receivables, stock) pay the short-term debts? 1.5 or more is comfortable, below 1 is tight.',
        qr: 'Like the current ratio but without stock (stock is slower to turn into cash). 1 or more is comfortable.',
        wc: 'Current assets minus current liabilities — the cushion that funds day-to-day trading.',
        netdebt: 'Borrowings and leases minus cash. Negative = more cash than debt.',
        dso: 'On average, how many days customers take to pay (receivables ÷ sales incl. VAT × 365). Lower is better.',
        dio: 'How many days stock sits before it is sold. Lower is better.',
        dpo: 'How many days we take to pay suppliers.',
        ccc: 'Days cash is tied up in the trading cycle: days customers take + days stock sits − days we take to pay suppliers.',
        at: 'Sales generated by every 1 of assets in the last 12 months.',
        roe: 'Profit of the last 12 months for every 100 of equity (what the owners have in the business).',
        roa: 'Profit of the last 12 months for every 100 of assets.',
        roce: 'Operating profit for every 100 of capital employed (total assets − current liabilities).',
        de: 'Borrowings and leases for every 1 of equity. Above 2 is highly geared.',
        nd_ebitda: 'Years of EBITDA needed to pay back the net debt. Banks often set a covenant around 2.5–3×; negative EBITDA makes it meaningless.',
        icr: 'How many times operating profit covers the interest. Below 1.5 is a warning; covenants often ask for 3–4×.',
        ocf: 'Cash generated by the operations year to date (from the cash-flow statement).',
        fcf: 'Operating cash flow after investing in fixed assets.',
        cconv: 'Share of EBITDA that turned into cash. 80 % or more is healthy.',
        susp: 'Balance left on suspense / unallocated accounts — should be nil at month end.',
        bs_chk: 'Assets minus equity and liabilities — must be nil. Anything else means unmapped accounts or missing periods.'
    };
    var BAND_TXT = { good: 'good', watch: 'watch', poor: 'poor', nodata: 'no data' };
    var big = function (v) { return v == null ? '—' : FINE.fmt(v, 'num', { decimals: 0 }); };
    var bandText = function (b, fmt) {
        if (!b) return '';
        var f = function (v) { return FL.kfmt(v, fmt); };
        if (b.dir === 'zero') return 'healthy when nil';
        return b.dir === 'down' ? 'good at ' + f(b.good) + ' or less · poor above ' + f(b.poor) : 'good at ' + f(b.good) + ' or more · poor below ' + f(b.poor);
    };
    FL.healthCfg = function () { var c = (FL.config && FL.config.health) || {}; return { pillars: c.pillars || FINE.HEALTH.pillars, bands: Object.assign({}, FINE.HEALTH.bands, c.bands || {}) }; };

    /** The "how it is calculated" panel of one KPI for the filter period */
    FL.explainHtml = function (def, data) {
        var cfg = FL.config, ex = FINE.kpiExplain(def, cfg.kpis, FL.tplMap(), data, FL.filter.period), hc = FL.healthCfg(), b = hc.bands[def.id];
        var st = ex.error ? 'error' : ex.nodata ? 'nodata' : FINE.band(b, ex.value);
        var h = '<div class="kx">' +
            '<div class="kx-what"><i class="fa-solid fa-circle-info"></i> ' + esc(def.desc || FL.KPI_GUIDE[def.id] || 'A formula over the statement lines.') +
            (b ? '<div class="sm muted">Healthy range: ' + esc(bandText(b, def.fmt)) + '</div>' : '') + '</div>' +
            '<div class="kx-row"><span class="kx-l">Formula</span><code>' + esc(def.expr) + '</code></div>' +
            '<div class="kx-row"><span class="kx-l">' + esc(FL.periodName(FL.filter.period)) + '</span><code>' + esc(ex.substituted || '') + '</code> = <b class="kx-v ' + st + '">' +
            (ex.error ? 'error' : ex.nodata ? 'no data' : FL.kfmt(ex.value, def.fmt)) + '</b>' + (st !== 'error' && st !== 'nodata' && b ? ' <span class="tag ' + (st === 'good' ? 'good' : st === 'poor' ? 'bad' : 'warn') + '">' + BAND_TXT[st] + '</span>' : '') + '</div>' +
            (ex.error ? '<div class="callout bad sm">' + esc(ex.error) + '</div>' : '') +
            '<table class="t kx-in"><thead><tr><th>Input</th><th>What it is</th><th>Periods</th><th class="n">Amount</th></tr></thead><tbody>' +
            (ex.inputs || []).map(function (i) {
                if (i.kind === 'kpi') return '<tr><td><code>' + esc(i.ref) + '</code></td><td>KPI <b>' + esc(i.label) + '</b><div class="sm muted mono">' + esc(i.expr || '') + '</div></td><td class="sm muted">same period</td><td class="n">' + (i.nodata ? '<span class="tag">no data</span>' : esc(FL.kfmt(i.value, i.fmt))) + '</td></tr>';
                var what = '<b>' + esc(i.label) + '</b> <span class="sm muted">line ' + esc(i.row) + ' of ' + esc(i.tplName) + (i.scenario && i.scenario !== 'ACTUAL' ? ' · ' + esc(i.scenario.toLowerCase()) : '') + '</span>';
                var detail = '';
                if (i.accounts && i.accounts.length) detail = '<details><summary>' + i.accounts.length + ' account(s)</summary><table class="t kx-acc">' + i.accounts.slice(0, 25).map(function (a) { return '<tr><td class="mono">' + esc(a.code) + '</td><td>' + esc(a.name) + '</td><td class="n">' + big(a.amount) + '</td></tr>'; }).join('') +
                    (i.accounts.length > 25 ? '<tr><td colspan="3" class="sm muted">… ' + (i.accounts.length - 25) + ' more</td></tr>' : '') + '</table></details>';
                else if (i.parts && i.parts.length) detail = '<details><summary>= ' + esc(i.formula || '') + '</summary><table class="t kx-acc">' + i.parts.map(function (p) {
                    return '<tr><td class="mono">' + esc(p.row) + '</td><td>' + esc(p.label) + (p.accounts ? ' <span class="sm muted">' + p.accounts.length + ' account(s)</span>' : p.formula ? ' <span class="sm muted mono">= ' + esc(p.formula) + '</span>' : '') + '</td><td class="n">' + big(p.value) + '</td></tr>'; }).join('') + '</table></details>';
                else if (i.rowType === 'accounts') detail = '<div class="sm neg">no accounts with amounts</div>';
                return '<tr><td><code>' + esc(i.ref) + '</code></td><td>' + what + detail + (i.error ? '<div class="sm neg">' + esc(i.error) + '</div>' : '') + '</td>' +
                    '<td class="sm">' + esc(i.windowText) + (i.from ? '<div class="muted">' + esc(i.from === i.to ? i.to : i.from + ' – ' + i.to) + (i.months > 1 ? ' · ' + i.months + ' months' : '') + '</div>' : '') + (i.nodata ? '<div class="neg">' + esc(i.nodata) + '</div>' : '') + (i.partial ? '<div class="warn-t">only ' + i.months + ' of 12 months</div>' : '') + '</td>' +
                    '<td class="n">' + (i.nodata ? '—' : big(i.value)) + '</td></tr>';
            }).join('') + '</tbody></table>' +
            (ex.notes && ex.notes.length ? '<div class="callout warn sm"><b>Missing for this KPI</b><br>' + ex.notes.map(esc).join('<br>') + '</div>' : '') +
            '<p class="sm muted">Amounts are in units, credits shown as positive on revenue, liability and equity lines. Open an input to see the accounts behind it; Statements › click any amount drills to journals.</p></div>';
        return h;
    };
    /** Modal: one KPI explained, its 12-month trend, the monitors on it */
    FL.kpiExplain = function (id) {
        var cfg = FL.config, def = cfg.kpis.filter(function (k) { return k.id === id; })[0]; if (!def) return;
        FL.data().then(function (data) {
            var tr = FINE.kpiTrend(cfg.kpis, FL.tplMap(), data, FL.filter.period, 12)[id] || [];
            var mons = (cfg.monitors || []).filter(function (m) { return m.kpi === id; });
            FL.modal('<i class="fa-solid fa-calculator"></i> ' + esc(def.label), FL.explainHtml(def, data) +
                '<h4 style="margin:12px 0 4px">Last 12 months</h4><div class="chartbox short"><canvas id="kx-tr"></canvas></div>' +
                (mons.length ? '<h4 style="margin:12px 0 4px">Monitor rules on this KPI</h4>' + mons.map(function (m) { return '<div class="sm">• ' + esc(m.label) + ' — alert when ' + esc(def.label) + ' ' + esc(m.op) + ' ' + esc(FL.kfmt(+m.value, def.fmt)) + ' (' + esc(m.severity) + ')</div>'; }).join('') : ''),
                '<button class="btn sm" id="kx-edit"><i class="fa-solid fa-pen"></i> Edit formula</button>');
            FL.chart('kx-tr', { type: 'line', data: { labels: tr.map(function (x) { return x.name; }), datasets: [{ label: def.label, data: tr.map(function (x) { return x.value; }), borderColor: FL.PAL.act, tension: 0.25, spanGaps: false }] },
                options: { plugins: { legend: { display: false } }, scales: { y: { ticks: { callback: function (v) { return FL.kfmt(v, def.fmt); } } } } } });
            FL.charts.drill = FL.charts['kx-tr'];
            $('kx-edit').onclick = function () { FL.kpiEdit(cfg.kpis.indexOf(def)); };
        });
    };

    /** What is missing for a complete picture, each with where to get it: [{k, text, why, act, label}] */
    FL.healthGaps = function (h, data) {
        var out = [], add = function (k, text, why, act, label) { if (!out.some(function (x) { return x.k === k; })) out.push({ k: k, text: text, why: why, act: act, label: label }); };
        var n = (FL.dims.periods || []).length, src = ((FL.status || {}).meta || {}).source;
        h.gaps.forEach(function (g) {
            if (/budget/.test(g)) add('bud', 'No budget loaded', 'Revenue / opex / profit vs budget and the budget monitors need it. The trial balance sync reads actuals only — the full GL load also reads the budget.', 'status', 'Full GL load (with budget)');
            else if (/last year|year end/.test(g)) add('py', 'Last year not synced', 'Growth vs last year, the year-end balance sheet column and every "vs last year" figure need last year\'s periods.', 'tbsync', 'Sync last year');
            else if (/previous month|quarter/.test(g)) add('pm', 'Earlier months not synced', g, 'tbsync', 'Sync earlier months');
        });
        if (n && n < 12) add('ltm', 'Only ' + n + ' month(s) synced', 'Last-12-month KPIs (DSO, DIO, ROE, interest cover, net debt / EBITDA) use only these months, so days and returns are overstated or understated. Sync 12 months in a row.', 'tbsync', 'Sync the earlier months');
        var tm = FL.tplMap(), rowAcc = function (t, id) { var tpl = tm[t], r = tpl && (tpl.rows || []).filter(function (x) { return x.id === id; })[0]; if (!r) return null; if (r.type !== 'accounts') return 1; return FINE.matchAccounts(r.accounts, data.accounts).length; };
        [['BS', 'AR', 'Trade receivables', 'days customers take to pay (DSO)'], ['BS', 'INV', 'Inventories', 'days stock sits (DIO)'], ['BS', 'AP', 'Trade payables', 'days we take to pay (DPO)'], ['BS', 'CASH', 'Cash', 'cash, net debt'],
            ['PL', 'FIN', 'Finance costs', 'interest cover'], ['PL', 'COGS', 'Cost of sales', 'gross margin, DIO']].forEach(function (x) {
            var c = rowAcc(x[0], x[1]); if (c === 0) add('map_' + x[1], 'No accounts mapped to "' + x[2] + '"', 'Needed for ' + x[3] + '.', 'builder:' + x[0], 'Map accounts');
        });
        var guessed = (FL.dims.accounts || []).filter(function (a) { return a.typeGuess; }).length;
        if (guessed) add('types', guessed + ' account(s) without a type from Fusion', 'Their type was guessed from the name and code, so they may sit in the wrong statement. Sync the account values (names + types).', 'tbsync', 'Master data checklist');
        if (src === 'FUSION_TB') add('jnl', 'No journal lines', 'Journal risk, Benford and the drill to journal lines need posted journals (trial balances hold balances only).', 'status', 'Full GL load (journals)');
        return out;
    };
    FL.healthAct = function (a) {
        if (/^builder:/.test(a)) return FL.builder.open(a.split(':')[1]);
        FL.dataTab.view = a; FL.lsSet('data.view', a); FL.show('data');
    };
    /** Company health card (KPIs & monitor tab) */
    FL.healthCard = function (box, kv, data) {
        var cfg = FL.config, h = FINE.health(kv, cfg.kpis, FL.healthCfg()), gaps = FL.healthGaps(h, data);
        var col = h.score == null ? '#94a3b8' : h.score >= 75 ? FL.PAL.good : h.score >= 55 ? '#d97706' : FL.PAL.bad, R = 46, C = 2 * Math.PI * R;
        var items = []; h.pillars.forEach(function (p) { p.items.forEach(function (i) { items.push(i); }); });
        var good = items.filter(function (i) { return i.band === 'good'; }), poor = items.filter(function (i) { return i.band === 'poor'; });
        var chip = function (i) { return '<a class="hx-k ' + i.band + '" data-kx="' + esc(i.id) + '" title="' + esc((FL.KPI_GUIDE[i.id] || '') + (i.nodata ? ' — ' + i.nodata.join(', ') : '')) + '"><i class="dot"></i>' + esc(i.label) + ' <b>' + (i.band === 'nodata' ? 'no data' : esc(FL.kfmt(i.value, i.fmt))) + '</b></a>'; };
        box.innerHTML = '<div class="card hx"><div class="hx-top"><svg class="hx-ring" viewBox="0 0 110 110"><circle cx="55" cy="55" r="' + R + '" stroke="#e2e8f0" stroke-width="10" fill="none"/>' +
            '<circle cx="55" cy="55" r="' + R + '" stroke="' + col + '" stroke-width="10" fill="none" stroke-linecap="round" stroke-dasharray="' + (C * (h.score || 0) / 100).toFixed(1) + ' ' + C.toFixed(1) + '" transform="rotate(-90 55 55)"/>' +
            '<text x="55" y="58" text-anchor="middle" font-size="26" font-weight="800" fill="' + col + '">' + (h.score == null ? '?' : h.score) + '</text><text x="55" y="76" text-anchor="middle" font-size="10" fill="#64748b">of 100</text></svg>' +
            '<div class="hx-sum"><h3 style="margin:0"><i class="fa-solid fa-heart-pulse"></i> Company health · ' + esc(FL.periodName(FL.filter.period)) + ' <span class="tag" style="background:' + col + '22;color:' + col + '">' + esc(h.grade) + '</span></h3>' +
            '<div class="sm muted">' + esc(FL.filterText()) + ' · based on ' + h.coverage + ' % of the health KPIs' + (h.coverage < 100 ? ' — the rest need data that is not synced yet (below)' : '') + '</div>' +
            (good.length ? '<div class="hx-l"><b class="pos">Strengths</b> ' + good.slice(0, 4).map(chip).join('') + '</div>' : '') +
            (poor.length ? '<div class="hx-l"><b class="neg">Concerns</b> ' + poor.slice(0, 5).map(chip).join('') + '</div>' : '') + '</div></div>' +
            '<div class="hx-pillars">' + h.pillars.map(function (p) {
                var pc = p.score == null ? '#94a3b8' : p.score >= 75 ? FL.PAL.good : p.score >= 55 ? '#d97706' : FL.PAL.bad;
                return '<div class="hx-p"><div class="row"><b>' + esc(p.name) + '</b><span class="grow"></span><b style="color:' + pc + '">' + (p.score == null ? '—' : p.score) + '</b></div>' +
                    '<div class="hx-bar"><span style="width:' + (p.score || 0) + '%;background:' + pc + '"></span></div>' + p.items.map(chip).join('') + '</div>';
            }).join('') + '</div>' +
            (gaps.length ? '<div class="hx-gaps"><h4 style="margin:6px 0"><i class="fa-solid fa-list-check"></i> To complete the picture</h4>' + gaps.map(function (g) {
                return '<div class="hx-gap"><div><b>' + esc(g.text) + '</b><div class="sm muted">' + esc(g.why) + '</div></div><button class="btn sm" data-ha="' + esc(g.act) + '">' + esc(g.label) + '</button></div>';
            }).join('') + '</div>' : '<p class="sm pos">✓ Every health KPI has its data.</p>') +
            '<p class="sm muted" style="margin:6px 0 0">Each KPI is scored good (100) / watch (60) / poor (20) against typical ranges; pillars are averaged with weights. Click a KPI for how it is worked out. The ranges can be changed in config.json (<code>health.bands</code>).</p></div>';
        box.querySelectorAll('[data-kx]').forEach(function (a) { a.onclick = function () { FL.kpiExplain(a.dataset.kx); }; });
        box.querySelectorAll('[data-ha]').forEach(function (b) { b.onclick = function () { FL.healthAct(b.dataset.ha); }; });
        return h;
    };
})();
