/* ═══════════════════════════════════════════════════════════════
   Fusion SQL — Oracle Fusion process flow library
   The standard end-to-end processes, grouped by area. Flows tab ›
   Fusion flow library lists them; "Build with AI" sends the stages,
   the starting document and key tables to Claude in flow mode.
   Each entry: [area, name, param name, param label, description,
                stages[], key tables (hints for the AI)]
   ═══════════════════════════════════════════════════════════════ */

window.FS_FLOW_AREAS = [
    ['OTC', 'Order to Cash', 'fa-cart-shopping', '#2a78d6'],
    ['P2P', 'Procure to Pay', 'fa-file-invoice-dollar', '#eb6834'],
    ['INV', 'Inventory & Costing', 'fa-boxes-stacked', '#1baf7a'],
    ['MFG', 'Manufacturing', 'fa-industry', '#c98500'],
    ['FIN', 'Financials', 'fa-scale-balanced', '#4a3aa7'],
    ['PRJ', 'Projects', 'fa-diagram-project', '#d55181'],
    ['LOG', 'Logistics', 'fa-truck-fast', '#008300']
];

window.FS_FLOW_CATALOG = [
    // ── Order to Cash ──
    ['OTC', 'Order to Cash', 'P_ORDER_NUMBER', 'Sales order number',
        'Standard sales order from entry to cash: fulfilment, shipping, inventory issue, COGS, invoicing, revenue accounting and receipts — with margin.',
        ['Sales order', 'Fulfillment lines', 'Shipment / delivery', 'Inventory issue', 'Cost & COGS', 'AR invoice', 'Revenue distributions', 'Subledger accounting', 'Customer receipt'],
        'DOO_HEADERS_ALL, DOO_FULFILL_LINES_ALL, WSH_DELIVERY_DETAILS, INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, CST_COST_DISTRIBUTION_LINES, RA_CUSTOMER_TRX_ALL, RA_CUST_TRX_LINE_GL_DIST_ALL, XLA_AE_LINES, AR_RECEIVABLE_APPLICATIONS_ALL'],
    ['OTC', 'Drop Ship', 'P_ORDER_NUMBER', 'Sales order number',
        'Customer order fulfilled directly by a supplier: sales order → supply order → purchase order → supplier shipment/receipt → customer invoice and supplier invoice.',
        ['Sales order', 'Fulfillment lines', 'Supply order', 'Purchase order', 'Drop-ship receipt / ASN', 'Logical inventory transactions', 'AR invoice', 'AP invoice', 'Accounting'],
        'DOO_FULFILL_LINES_ALL, DOS_SUPPLY_HEADERS, DOS_SUPPLY_LINES, PO_HEADERS_ALL, PO_LINE_LOCATIONS_ALL, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, RA_CUSTOMER_TRX_LINES_ALL, AP_INVOICE_LINES_ALL'],
    ['OTC', 'Back-to-Back Order', 'P_ORDER_NUMBER', 'Sales order number',
        'Items bought specifically for a sales order: order → supply order → PO → receipt → reservation → shipment → invoice.',
        ['Sales order', 'Supply order', 'Purchase order', 'Receipt', 'Reservation', 'Shipment', 'AR invoice'],
        'DOO_FULFILL_LINES_ALL, DOS_SUPPLY_HEADERS, PO_HEADERS_ALL, RCV_TRANSACTIONS, INV_RESERVATIONS, WSH_DELIVERY_DETAILS, RA_CUSTOMER_TRX_ALL'],
    ['OTC', 'Return to Credit (RMA)', 'P_ORDER_NUMBER', 'Return order number',
        'Customer return: return order → expected receipt → return receipt / inspection → inventory → cost → credit memo → accounting.',
        ['Return order', 'Return lines', 'Expected receipt', 'Return receipt', 'Inventory transaction', 'Cost', 'Credit memo', 'Accounting'],
        'DOO_HEADERS_ALL, DOO_FULFILL_LINES_ALL, RCV_SHIPMENT_LINES, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, RA_CUSTOMER_TRX_ALL (credit memo), XLA_AE_LINES'],
    ['OTC', 'Configure to Order (ATO)', 'P_ORDER_NUMBER', 'Sales order number',
        'Assemble-to-order model: configured order → supply → work order → completion → shipment → invoice.',
        ['Configured order', 'Configuration lines', 'Supply order', 'Work order', 'Work order completion', 'Shipment', 'AR invoice'],
        'DOO_FULFILL_LINES_ALL, DOS_SUPPLY_HEADERS, WIE_WORK_ORDERS_B, WIE_WO_OPERATIONS_B, INV_MATERIAL_TXNS, WSH_DELIVERY_DETAILS, RA_CUSTOMER_TRX_ALL'],
    ['OTC', 'Intercompany Sale', 'P_ORDER_NUMBER', 'Sales order number',
        'Order shipped from another legal entity: order → shipment → intercompany AR/AP invoices → transfer pricing → accounting in both entities.',
        ['Sales order', 'Shipment', 'Inventory transaction', 'Intercompany cost', 'Intercompany AR invoice', 'Intercompany AP invoice', 'Customer AR invoice', 'Accounting'],
        'DOO_FULFILL_LINES_ALL, WSH_DELIVERY_DETAILS, INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, RA_CUSTOMER_TRX_ALL, AP_INVOICES_ALL, XLA_AE_LINES'],
    ['OTC', 'Order Holds & Credit Check', 'P_ORDER_NUMBER', 'Sales order number',
        'Why an order is stuck: order → holds applied/released → credit check → orchestration tasks and their status.',
        ['Sales order', 'Holds', 'Credit check', 'Orchestration process', 'Fulfillment tasks', 'Exceptions'],
        'DOO_HEADERS_ALL, DOO_HOLD_INSTANCES, DOO_PROCESS_INSTANCES, DOO_ORCHESTRATION_GROUPS, DOO_FULFILL_LINES_ALL'],
    ['OTC', 'Order Pricing & Charges', 'P_ORDER_NUMBER', 'Sales order number',
        'How an order was priced: lines → price adjustments → charges and charge components → totals vs invoice.',
        ['Sales order', 'Order lines', 'Price adjustments', 'Charges', 'Charge components', 'Order totals', 'AR invoice lines'],
        'DOO_LINES_ALL, DOO_PRICE_ADJUSTMENTS, DOO_ORDER_CHARGES, DOO_CHARGE_COMPONENTS, DOO_ORDER_TOTALS, RA_CUSTOMER_TRX_LINES_ALL'],
    ['OTC', 'Revenue Recognition (ASC 606)', 'P_ORDER_NUMBER', 'Sales order number',
        'Revenue Management: source document → customer contract → performance obligations → satisfaction events → recognised revenue → accounting.',
        ['Sales order', 'Source document lines', 'Customer contract', 'Performance obligations', 'Satisfaction events', 'Revenue recognised', 'Accounting'],
        'VRM_SOURCE_DOCUMENTS, VRM_SOURCE_DOC_LINES, VRM_CUSTOMER_CONTRACTS, VRM_PERF_OBLIGATIONS, VRM_SATISFACTION_EVENTS, XLA_AE_LINES'],

    // ── Procure to Pay ──
    ['P2P', 'Procure to Pay', 'P_PO_NUMBER', 'Purchase order number',
        'Standard purchase from order to payment: PO → schedules → receipts → receipt accounting → supplier invoice → payables accounting → payment.',
        ['Purchase order', 'Lines & schedules', 'Distributions', 'Receipts', 'Receipt accounting', 'Supplier invoice', 'Invoice holds', 'Payables accounting', 'Payment'],
        'PO_HEADERS_ALL, PO_LINE_LOCATIONS_ALL, PO_DISTRIBUTIONS_ALL, RCV_TRANSACTIONS, CMR_RCV_EVENTS, AP_INVOICE_LINES_ALL, AP_HOLDS_ALL, XLA_AE_LINES, AP_INVOICE_PAYMENTS_ALL, AP_CHECKS_ALL'],
    ['P2P', 'Requisition to Receipt', 'P_REQUISITION_NUMBER', 'Requisition number',
        'From self-service request to goods received: requisition → approval → purchase order → receipt → delivery.',
        ['Requisition', 'Requisition lines & distributions', 'Approval', 'Purchase order', 'Receipt', 'Delivery to destination'],
        'POR_REQUISITION_HEADERS_ALL, POR_REQUISITION_LINES_ALL, POR_REQ_DISTRIBUTIONS_ALL, PO_HEADERS_ALL, PO_LINES_ALL, RCV_TRANSACTIONS'],
    ['P2P', 'Blanket Agreement to Release', 'P_PO_NUMBER', 'Agreement number',
        'Blanket purchase agreement usage: agreement → released purchase orders → receipts → invoices → amount consumed.',
        ['Agreement', 'Agreement lines', 'Released orders', 'Receipts', 'Invoices', 'Consumption'],
        'PO_HEADERS_ALL (type BLANKET), PO_LINES_ALL, PO_LINES_ALL.FROM_HEADER_ID, RCV_TRANSACTIONS, AP_INVOICE_LINES_ALL'],
    ['P2P', 'Consignment to Invoice', 'P_PO_NUMBER', 'Consignment agreement number',
        'Supplier-owned stock: consignment receipt → consumption (ownership transfer) → consumption advice → invoice.',
        ['Consignment agreement', 'Consigned receipt', 'Ownership transfer', 'Consumption advice', 'Supplier invoice'],
        'PO_HEADERS_ALL, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, INV_CONSUMPTION_ADVICE_HEADERS, AP_INVOICES_ALL'],
    ['P2P', 'Return to Supplier', 'P_RECEIPT_NUMBER', 'Receipt number',
        'Goods sent back: receipt → return to supplier transaction → inventory → cost → debit memo.',
        ['Receipt', 'Return transactions', 'Inventory transaction', 'Receipt accounting', 'Debit memo', 'Accounting'],
        'RCV_SHIPMENT_HEADERS, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, CMR_RCV_EVENTS, AP_INVOICES_ALL (DEBIT), XLA_AE_LINES'],
    ['P2P', 'Supplier Onboarding', 'P_SUPPLIER_NUMBER', 'Supplier number',
        'Is the supplier ready to transact: supplier → sites and BU assignments → contacts → bank accounts → payment methods.',
        ['Supplier', 'Addresses', 'Sites', 'Site assignments', 'Contacts', 'Bank accounts', 'Payment methods'],
        'POZ_SUPPLIERS, HZ_PARTIES, POZ_SUPPLIER_ADDRESSES_V, POZ_SUPPLIER_SITES_ALL_M, POZ_SITE_ASSIGNMENTS_ALL_M, IBY_EXT_BANK_ACCOUNTS, IBY_EXTERNAL_PAYEES_ALL'],
    ['P2P', 'Invoice to Payment', 'P_INVOICE_NUMBER', 'Supplier invoice number',
        'A supplier invoice through Payables: invoice → lines/distributions → validation & holds → accounting → payment → bank clearing.',
        ['Invoice', 'Lines', 'Distributions', 'Holds', 'Accounting', 'Payment schedule', 'Payment', 'Bank clearing'],
        'AP_INVOICES_ALL, AP_INVOICE_LINES_ALL, AP_INVOICE_DISTRIBUTIONS_ALL, AP_HOLDS_ALL, XLA_AE_LINES, AP_PAYMENT_SCHEDULES_ALL, AP_INVOICE_PAYMENTS_ALL, AP_CHECKS_ALL, CE_STATEMENT_LINES'],
    ['P2P', 'Expense to Reimbursement', 'P_EXPENSE_REPORT', 'Expense report number',
        'Employee expense: expense report → items → approval → Payables invoice → payment.',
        ['Expense report', 'Expense items', 'Approval', 'AP invoice', 'Payment'],
        'EXM_EXPENSE_REPORTS, EXM_EXPENSES, EXM_EXPENSE_DISTS, AP_INVOICES_ALL, AP_INVOICE_PAYMENTS_ALL'],

    // ── Inventory & Costing ──
    ['INV', 'Receipt to Cost', 'P_RECEIPT_NUMBER', 'Receipt number',
        'Inbound goods to accounting: receipt → delivery → inventory transaction → cost transaction → distributions → accounting.',
        ['Receipt', 'Receiving transactions', 'Inventory transaction', 'Cost transaction', 'Cost distributions', 'Accounting'],
        'RCV_SHIPMENT_HEADERS, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, CST_COST_DISTRIBUTIONS, CST_COST_DISTRIBUTION_LINES, XLA_AE_LINES'],
    ['INV', 'Item to Onhand', 'P_ITEM_NUMBER', 'Item number',
        'An item end to end: item master → organisation assignments → costs → onhand → recent transactions → open reservations.',
        ['Item master', 'Organisation items', 'Item cost', 'Onhand', 'Recent transactions', 'Reservations'],
        'EGP_SYSTEM_ITEMS_B, INV_ORG_PARAMETERS, CST_ITEM_COSTS / CST_PERPAVG_COST, INV_ONHAND_QUANTITIES_DETAIL, INV_MATERIAL_TXNS, INV_RESERVATIONS'],
    ['INV', 'Inventory Adjustment to Accounting', 'P_TRANSACTION_ID', 'Inventory transaction id',
        'Miscellaneous / cycle count / physical adjustment: transaction → cost → distributions → subledger accounting → GL.',
        ['Inventory transaction', 'Cost transaction', 'Cost distributions', 'Subledger accounting', 'GL journal'],
        'INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, CST_TRANSACTIONS, CST_COST_DISTRIBUTION_LINES, XLA_AE_HEADERS, XLA_AE_LINES, GL_JE_LINES'],
    ['INV', 'Transfer Order', 'P_TRANSFER_ORDER', 'Transfer order number',
        'Inter-organisation transfer: transfer order → shipment → in-transit → receipt → transfer costs → accounting.',
        ['Transfer order', 'Transfer lines', 'Shipment', 'In-transit', 'Receipt', 'Cost', 'Accounting'],
        'INV_TRANSFER_ORDER_HEADERS, INV_TRANSFER_ORDER_LINES, WSH_DELIVERY_DETAILS, INV_MATERIAL_TXNS, RCV_TRANSACTIONS, CST_INV_TRANSACTIONS'],
    ['INV', 'Lot Traceability', 'P_LOT_NUMBER', 'Lot number',
        'Where a lot came from and went: lot → receipts → issues/transfers → shipments to customers.',
        ['Lot', 'Lot onhand', 'Receipts', 'Issues & transfers', 'Shipments', 'Customers'],
        'INV_LOT_NUMBERS, INV_ONHAND_QUANTITIES_DETAIL, INV_TRANSACTION_LOT_NUMBERS, INV_MATERIAL_TXNS, WSH_DELIVERY_DETAILS, DOO_HEADERS_ALL'],
    ['INV', 'Serial Traceability', 'P_SERIAL_NUMBER', 'Serial number',
        'A serial number\'s history: current status → transactions → shipment → customer.',
        ['Serial', 'Serial transactions', 'Receipt', 'Shipment', 'Customer order'],
        'INV_SERIAL_NUMBERS, INV_TRANSACTION_SERIAL_NUMS / INV_SERIAL_TXNS, INV_MATERIAL_TXNS, WSH_DELIVERY_DETAILS, DOO_HEADERS_ALL'],

    // ── Manufacturing ──
    ['MFG', 'Plan to Produce (Work Order)', 'P_WORK_ORDER', 'Work order number',
        'Discrete work order: work order → operations → material issues → resource charges → completions → WIP costing → accounting.',
        ['Work order', 'Operations', 'Material requirements & issues', 'Resource transactions', 'Completions', 'WIP cost', 'Accounting'],
        'WIE_WORK_ORDERS_B, WIE_WO_OPERATIONS_B, WIE_WO_OPERATION_MATERIALS, WIE_MATERIAL_TXNS / INV_MATERIAL_TXNS, WIE_RESOURCE_TXNS, CST_WORK_ORDER_COSTS, XLA_AE_LINES'],
    ['MFG', 'Make to Order', 'P_ORDER_NUMBER', 'Sales order number',
        'Built for a customer order: sales order → supply order → work order → completion → reservation → shipment.',
        ['Sales order', 'Supply order', 'Work order', 'Completion', 'Reservation', 'Shipment'],
        'DOO_FULFILL_LINES_ALL, DOS_SUPPLY_HEADERS, WIE_WORK_ORDERS_B, INV_MATERIAL_TXNS, INV_RESERVATIONS, WSH_DELIVERY_DETAILS'],

    // ── Financials ──
    ['FIN', 'Invoice to Cash (Receivables)', 'P_TRX_NUMBER', 'AR transaction number',
        'A receivables invoice to cash: invoice → payment schedule → receipt applications → adjustments → accounting.',
        ['AR invoice', 'Lines', 'Distributions', 'Payment schedule', 'Receipt applications', 'Adjustments', 'Accounting'],
        'RA_CUSTOMER_TRX_ALL, RA_CUSTOMER_TRX_LINES_ALL, RA_CUST_TRX_LINE_GL_DIST_ALL, AR_PAYMENT_SCHEDULES_ALL, AR_RECEIVABLE_APPLICATIONS_ALL, AR_ADJUSTMENTS_ALL, XLA_AE_LINES'],
    ['FIN', 'Receipt to Bank Reconciliation', 'P_RECEIPT_NUMBER', 'Receipt number',
        'A customer receipt: receipt → applications → remittance → clearing → bank statement line → reconciliation.',
        ['Receipt', 'Applications', 'Remittance batch', 'Receipt history', 'Bank statement line', 'Reconciliation'],
        'AR_CASH_RECEIPTS_ALL, AR_RECEIVABLE_APPLICATIONS_ALL, AR_CASH_RECEIPT_HISTORY_ALL, AR_BATCHES_ALL, CE_STATEMENT_LINES, CE_STATEMENT_RECONS'],
    ['FIN', 'Payment to Bank Reconciliation', 'P_CHECK_NUMBER', 'Payment number',
        'A supplier payment: payment → paid invoices → payment accounting → bank statement line → reconciliation.',
        ['Payment', 'Invoices paid', 'Payment accounting', 'Bank statement line', 'Reconciliation'],
        'AP_CHECKS_ALL, AP_INVOICE_PAYMENTS_ALL, AP_PAYMENT_HISTORY_ALL, XLA_AE_LINES, CE_STATEMENT_LINES, CE_STATEMENT_RECONS'],
    ['FIN', 'Record to Report', 'P_JE_BATCH_NAME', 'Journal batch name',
        'Journals to balances: journal batch → headers → lines → subledger links → posting → balances.',
        ['Journal batch', 'Journal headers', 'Journal lines', 'Subledger references', 'Posting status', 'Account balances'],
        'GL_JE_BATCHES, GL_JE_HEADERS, GL_JE_LINES, GL_IMPORT_REFERENCES, XLA_AE_LINES, GL_BALANCES, GL_CODE_COMBINATIONS'],
    ['FIN', 'Subledger to GL (Period Close)', 'P_PERIOD_NAME', 'Period name',
        'What blocks a close: subledger period statuses → unaccounted events → accounting errors → untransferred entries → GL period status.',
        ['Period statuses', 'Unaccounted events', 'Accounting errors', 'Not transferred to GL', 'GL journals', 'GL period'],
        'GL_PERIOD_STATUSES, XLA_EVENTS, XLA_ACCOUNTING_ERRORS, XLA_AE_HEADERS, GL_JE_HEADERS, GL_PERIODS'],
    ['FIN', 'Customer Onboarding', 'P_ACCOUNT_NUMBER', 'Customer account number',
        'Is the customer ready to trade: party → account → sites and uses → profiles and credit limits → contacts.',
        ['Party', 'Customer account', 'Account sites', 'Site uses (bill-to / ship-to)', 'Profiles & credit', 'Contacts'],
        'HZ_PARTIES, HZ_CUST_ACCOUNTS, HZ_CUST_ACCT_SITES_ALL, HZ_CUST_SITE_USES_ALL, HZ_CUSTOMER_PROFILES_F, HZ_CUST_ACCOUNT_ROLES'],
    ['FIN', 'Acquire to Retire (Assets)', 'P_ASSET_NUMBER', 'Asset number',
        'Fixed asset lifecycle: source invoice → mass addition → asset → books → depreciation → transfers → retirement.',
        ['Source invoice', 'Mass addition', 'Asset', 'Asset books', 'Depreciation', 'Transfers', 'Retirement'],
        'AP_INVOICE_LINES_ALL, FA_MASS_ADDITIONS, FA_ADDITIONS_B, FA_BOOKS, FA_DEPRN_DETAIL, FA_TRANSACTION_HEADERS, FA_RETIREMENTS'],
    ['FIN', 'Intercompany Transaction', 'P_IC_BATCH', 'Intercompany batch number',
        'Intercompany: batch → transactions → provider/receiver distributions → AR/AP invoices → journals.',
        ['Intercompany batch', 'Transactions', 'Distributions', 'AR invoice', 'AP invoice', 'Journals'],
        'FUN_TRX_BATCHES, FUN_TRX_HEADERS, FUN_DIST_LINES, RA_CUSTOMER_TRX_ALL, AP_INVOICES_ALL, GL_JE_LINES'],
    ['FIN', 'Transaction Tax', 'P_TRX_NUMBER', 'Invoice number',
        'How tax was calculated: invoice → tax lines → rates and jurisdictions → tax distributions → accounting.',
        ['Invoice', 'Tax lines', 'Tax rates', 'Jurisdictions', 'Tax distributions', 'Accounting'],
        'RA_CUSTOMER_TRX_ALL / AP_INVOICES_ALL, ZX_LINES, ZX_RATES_B, ZX_JURISDICTIONS_B, ZX_REC_NREC_DIST, XLA_AE_LINES'],

    // ── Projects ──
    ['PRJ', 'Project Contract to Cash', 'P_PROJECT_NUMBER', 'Project number',
        'Project billing: project → contract → costs → billing events → invoices → AR invoice → revenue.',
        ['Project', 'Contract', 'Expenditures', 'Billing events', 'Project invoice', 'AR invoice', 'Revenue'],
        'PJF_PROJECTS_ALL_B, OKC_K_HEADERS_ALL_B, PJC_EXP_ITEMS_ALL, PJB_BILLING_EVENTS, PJB_INVOICE_HEADERS, RA_CUSTOMER_TRX_ALL, PJB_REV_DISTRIBUTIONS'],
    ['PRJ', 'Procure to Project Cost', 'P_PO_NUMBER', 'Purchase order number',
        'Project-related purchase: PO with project → receipt → supplier invoice → project cost lines → accounting.',
        ['Purchase order', 'Project distributions', 'Receipt', 'Supplier invoice', 'Project costs', 'Accounting'],
        'PO_HEADERS_ALL, PO_DISTRIBUTIONS_ALL (PJC columns), RCV_TRANSACTIONS, AP_INVOICE_DISTRIBUTIONS_ALL, PJC_EXP_ITEMS_ALL, PJC_COST_DIST_LINES_ALL'],
    ['PRJ', 'Time to Project Cost', 'P_PROJECT_NUMBER', 'Project number',
        'Labour costing: timecards → project expenditures → cost distributions → accounting.',
        ['Project', 'Timecards', 'Labor expenditures', 'Cost distributions', 'Accounting'],
        'PJF_PROJECTS_ALL_B, HWM_TM_REC, PJC_EXP_ITEMS_ALL, PJC_COST_DIST_LINES_ALL, XLA_AE_LINES'],

    // ── Logistics ──
    ['LOG', 'Pick to Ship', 'P_ORDER_NUMBER', 'Sales order number',
        'Warehouse execution: fulfillment lines → delivery details → pick waves / move orders → picks → pack → ship confirm.',
        ['Fulfillment lines', 'Delivery details', 'Pick wave', 'Movement requests', 'Pick transactions', 'Delivery', 'Ship confirm'],
        'DOO_FULFILL_LINES_ALL, WSH_DELIVERY_DETAILS, WSH_PICKING_BATCHES, INV_TXN_REQUEST_HEADERS, INV_TXN_REQUEST_LINES, WSH_NEW_DELIVERIES, INV_MATERIAL_TXNS'],
    ['LOG', 'Ship Confirm to Invoice', 'P_DELIVERY_NAME', 'Delivery / shipment number',
        'After shipping: delivery → trip → interfaced to receivables → AutoInvoice → invoice.',
        ['Delivery', 'Delivery lines', 'Trip / stops', 'AR interface', 'AR invoice'],
        'WSH_NEW_DELIVERIES, WSH_DELIVERY_DETAILS, WSH_TRIPS, WSH_TRIP_STOPS, RA_INTERFACE_LINES_ALL, RA_CUSTOMER_TRX_LINES_ALL'],
    ['LOG', 'Inbound ASN to Putaway', 'P_SHIPMENT_NUMBER', 'ASN / shipment number',
        'Supplier shipment arriving: ASN → receipt → inspection → putaway → onhand.',
        ['ASN', 'Shipment lines', 'Receipt', 'Inspection', 'Putaway', 'Onhand'],
        'RCV_SHIPMENT_HEADERS, RCV_SHIPMENT_LINES, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, INV_ONHAND_QUANTITIES_DETAIL']
];
