/* ═══════════════════════════════════════════════════════════════
   Fusion SQL — Oracle Fusion process flow library
   The standard end-to-end processes, grouped by area. Flows tab ›
   Fusion flow library lists them; "Build with AI" sends the stages,
   the starting document and key tables to Claude in flow mode.
   Each entry: [area, name, param name, param label, description,
                stages[], key tables (hints for the AI), options]
   options (optional): { recon: true, params: [[name, label], …] } —
   reconciliations compare period totals (subledger vs SLA vs GL) and
   list the items behind each difference instead of tracing one document.
   ═══════════════════════════════════════════════════════════════ */

window.FS_FLOW_AREAS = [
    ['OTC', 'Order to Cash', 'fa-cart-shopping', '#2a78d6'],
    ['P2P', 'Procure to Pay', 'fa-file-invoice-dollar', '#eb6834'],
    ['INV', 'Inventory & Costing', 'fa-boxes-stacked', '#1baf7a'],
    ['MFG', 'Manufacturing', 'fa-industry', '#c98500'],
    ['FIN', 'Financials', 'fa-scale-balanced', '#4a3aa7'],
    ['PRJ', 'Projects', 'fa-diagram-project', '#d55181'],
    ['LOG', 'Logistics', 'fa-truck-fast', '#008300'],
    ['REC', 'Reconciliations', 'fa-code-compare', '#0f766e']
];

// Parameters shared by the period reconciliations
var FL_REC_P = [['P_LEDGER_NAME', 'Ledger name'], ['P_PERIOD_NAME', 'Period name (e.g. SEP-26)']];
var FL_REC_BU = [['P_LEDGER_NAME', 'Ledger name'], ['P_BU_NAME', 'Business unit'], ['P_PERIOD_NAME', 'Period name (e.g. SEP-26)']];
function flRec(params) { return { recon: true, params: params || FL_REC_P }; }

window.FS_FLOW_CATALOG = [
    // ── Order to Cash ──
    ['OTC', 'Order to Cash', 'P_ORDER_NUMBER', 'Sales order number',
        'Standard sales order from entry to cash: fulfilment, shipping, inventory issue, COGS, invoicing, revenue accounting and receipts — with margin.',
        ['Sales order', 'Fulfillment lines', 'Shipment / delivery', 'Inventory issue', 'Cost & COGS', 'AR invoice', 'Revenue distributions', 'Subledger accounting', 'Customer receipt'],
        'DOO_HEADERS_ALL, DOO_FULFILL_LINES_ALL, WSH_DELIVERY_DETAILS, INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, CST_COST_DISTRIBUTION_LINES, RA_CUSTOMER_TRX_ALL, RA_CUST_TRX_LINE_GL_DIST_ALL, XLA_AE_LINES, AR_RECEIVABLE_APPLICATIONS_ALL'],
    ['OTC', 'Drop Ship', 'P_ORDER_NUMBER', 'Sales order number',
        'Customer order fulfilled directly by a supplier: sales order → supply order → purchase order → supplier shipment/receipt → customer invoice and supplier invoice.',
        ['Sales order', 'Fulfillment lines', 'Supply order', 'Purchase order', 'Drop-ship receipt / ASN', 'Logical inventory transactions', 'AR invoice', 'AP invoice', 'Accounting'],
        'DOO_FULFILL_LINES_ALL, DOS_SUPPLY_HEADERS, DOS_SUPPLY_LINES, PO_HEADERS_ALL, PO_LINE_LOCATIONS_ALL, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, RA_CUSTOMER_TRX_LINES_ALL, AP_INVOICE_LINES_ALL'],
    ['OTC', 'Back-to-Back Order', 'P_ORDER_NUMBER', 'Sales order number',
        'Items bought specifically for a sales order: order → supply order → PO → receipt → reservation → shipment → invoice.',
        ['Sales order', 'Supply order', 'Purchase order', 'Receipt', 'Reservation', 'Shipment', 'AR invoice'],
        'DOO_FULFILL_LINES_ALL, DOS_SUPPLY_HEADERS, PO_HEADERS_ALL, RCV_TRANSACTIONS, INV_RESERVATIONS, WSH_DELIVERY_DETAILS, RA_CUSTOMER_TRX_ALL'],
    ['OTC', 'Return to Credit (RMA)', 'P_ORDER_NUMBER', 'Return order number',
        'Customer return: return order → expected receipt → return receipt / inspection → inventory → cost → credit memo → accounting.',
        ['Return order', 'Return lines', 'Expected receipt', 'Return receipt', 'Inventory transaction', 'Cost', 'Credit memo', 'Accounting'],
        'DOO_HEADERS_ALL, DOO_FULFILL_LINES_ALL, RCV_SHIPMENT_LINES, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, RA_CUSTOMER_TRX_ALL (credit memo), XLA_AE_LINES'],
    ['OTC', 'Configure to Order (ATO)', 'P_ORDER_NUMBER', 'Sales order number',
        'Assemble-to-order model: configured order → supply → work order → completion → shipment → invoice.',
        ['Configured order', 'Configuration lines', 'Supply order', 'Work order', 'Work order completion', 'Shipment', 'AR invoice'],
        'DOO_FULFILL_LINES_ALL, DOS_SUPPLY_HEADERS, WIE_WORK_ORDERS_B, WIE_WO_OPERATIONS_B, INV_MATERIAL_TXNS, WSH_DELIVERY_DETAILS, RA_CUSTOMER_TRX_ALL'],
    ['OTC', 'Intercompany Sale', 'P_ORDER_NUMBER', 'Sales order number',
        'Order shipped from another legal entity: order → shipment → intercompany AR/AP invoices → transfer pricing → accounting in both entities.',
        ['Sales order', 'Shipment', 'Inventory transaction', 'Intercompany cost', 'Intercompany AR invoice', 'Intercompany AP invoice', 'Customer AR invoice', 'Accounting'],
        'DOO_FULFILL_LINES_ALL, WSH_DELIVERY_DETAILS, INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, RA_CUSTOMER_TRX_ALL, AP_INVOICES_ALL, XLA_AE_LINES'],
    ['OTC', 'Order Holds & Credit Check', 'P_ORDER_NUMBER', 'Sales order number',
        'Why an order is stuck: order → holds applied/released → credit check → orchestration tasks and their status.',
        ['Sales order', 'Holds', 'Credit check', 'Orchestration process', 'Fulfillment tasks', 'Exceptions'],
        'DOO_HEADERS_ALL, DOO_HOLD_INSTANCES, DOO_PROCESS_INSTANCES, DOO_ORCHESTRATION_GROUPS, DOO_FULFILL_LINES_ALL'],
    ['OTC', 'Order Pricing & Charges', 'P_ORDER_NUMBER', 'Sales order number',
        'How an order was priced: lines → price adjustments → charges and charge components → totals vs invoice.',
        ['Sales order', 'Order lines', 'Price adjustments', 'Charges', 'Charge components', 'Order totals', 'AR invoice lines'],
        'DOO_LINES_ALL, DOO_PRICE_ADJUSTMENTS, DOO_ORDER_CHARGES, DOO_CHARGE_COMPONENTS, DOO_ORDER_TOTALS, RA_CUSTOMER_TRX_LINES_ALL'],
    ['OTC', 'Revenue Recognition (ASC 606)', 'P_ORDER_NUMBER', 'Sales order number',
        'Revenue Management: source document → customer contract → performance obligations → satisfaction events → recognised revenue → accounting.',
        ['Sales order', 'Source document lines', 'Customer contract', 'Performance obligations', 'Satisfaction events', 'Revenue recognised', 'Accounting'],
        'VRM_SOURCE_DOCUMENTS, VRM_SOURCE_DOC_LINES, VRM_CUSTOMER_CONTRACTS, VRM_PERF_OBLIGATIONS, VRM_SATISFACTION_EVENTS, XLA_AE_LINES'],

    // ── Procure to Pay ──
    ['P2P', 'Procure to Pay', 'P_PO_NUMBER', 'Purchase order number',
        'Standard purchase from order to payment: PO → schedules → receipts → receipt accounting → supplier invoice → payables accounting → payment.',
        ['Purchase order', 'Lines & schedules', 'Distributions', 'Receipts', 'Receipt accounting', 'Supplier invoice', 'Invoice holds', 'Payables accounting', 'Payment'],
        'PO_HEADERS_ALL, PO_LINE_LOCATIONS_ALL, PO_DISTRIBUTIONS_ALL, RCV_TRANSACTIONS, CMR_RCV_EVENTS, AP_INVOICE_LINES_ALL, AP_HOLDS_ALL, XLA_AE_LINES, AP_INVOICE_PAYMENTS_ALL, AP_CHECKS_ALL'],
    ['P2P', 'Requisition to Receipt', 'P_REQUISITION_NUMBER', 'Requisition number',
        'From self-service request to goods received: requisition → approval → purchase order → receipt → delivery.',
        ['Requisition', 'Requisition lines & distributions', 'Approval', 'Purchase order', 'Receipt', 'Delivery to destination'],
        'POR_REQUISITION_HEADERS_ALL, POR_REQUISITION_LINES_ALL, POR_REQ_DISTRIBUTIONS_ALL, PO_HEADERS_ALL, PO_LINES_ALL, RCV_TRANSACTIONS'],
    ['P2P', 'Blanket Agreement to Release', 'P_PO_NUMBER', 'Agreement number',
        'Blanket purchase agreement usage: agreement → released purchase orders → receipts → invoices → amount consumed.',
        ['Agreement', 'Agreement lines', 'Released orders', 'Receipts', 'Invoices', 'Consumption'],
        'PO_HEADERS_ALL (type BLANKET), PO_LINES_ALL, PO_LINES_ALL.FROM_HEADER_ID, RCV_TRANSACTIONS, AP_INVOICE_LINES_ALL'],
    ['P2P', 'Consignment to Invoice', 'P_PO_NUMBER', 'Consignment agreement number',
        'Supplier-owned stock: consignment receipt → consumption (ownership transfer) → consumption advice → invoice.',
        ['Consignment agreement', 'Consigned receipt', 'Ownership transfer', 'Consumption advice', 'Supplier invoice'],
        'PO_HEADERS_ALL, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, INV_CONSUMPTION_ADVICE_HEADERS, AP_INVOICES_ALL'],
    ['P2P', 'Return to Supplier', 'P_RECEIPT_NUMBER', 'Receipt number',
        'Goods sent back: receipt → return to supplier transaction → inventory → cost → debit memo.',
        ['Receipt', 'Return transactions', 'Inventory transaction', 'Receipt accounting', 'Debit memo', 'Accounting'],
        'RCV_SHIPMENT_HEADERS, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, CMR_RCV_EVENTS, AP_INVOICES_ALL (DEBIT), XLA_AE_LINES'],
    ['P2P', 'Supplier Onboarding', 'P_SUPPLIER_NUMBER', 'Supplier number',
        'Is the supplier ready to transact: supplier → sites and BU assignments → contacts → bank accounts → payment methods.',
        ['Supplier', 'Addresses', 'Sites', 'Site assignments', 'Contacts', 'Bank accounts', 'Payment methods'],
        'POZ_SUPPLIERS, HZ_PARTIES, POZ_SUPPLIER_ADDRESSES_V, POZ_SUPPLIER_SITES_ALL_M, POZ_SITE_ASSIGNMENTS_ALL_M, IBY_EXT_BANK_ACCOUNTS, IBY_EXTERNAL_PAYEES_ALL'],
    ['P2P', 'Invoice to Payment', 'P_INVOICE_NUMBER', 'Supplier invoice number',
        'A supplier invoice through Payables: invoice → lines/distributions → validation & holds → accounting → payment → bank clearing.',
        ['Invoice', 'Lines', 'Distributions', 'Holds', 'Accounting', 'Payment schedule', 'Payment', 'Bank clearing'],
        'AP_INVOICES_ALL, AP_INVOICE_LINES_ALL, AP_INVOICE_DISTRIBUTIONS_ALL, AP_HOLDS_ALL, XLA_AE_LINES, AP_PAYMENT_SCHEDULES_ALL, AP_INVOICE_PAYMENTS_ALL, AP_CHECKS_ALL, CE_STATEMENT_LINES'],
    ['P2P', 'Expense to Reimbursement', 'P_EXPENSE_REPORT', 'Expense report number',
        'Employee expense: expense report → items → approval → Payables invoice → payment.',
        ['Expense report', 'Expense items', 'Approval', 'AP invoice', 'Payment'],
        'EXM_EXPENSE_REPORTS, EXM_EXPENSES, EXM_EXPENSE_DISTS, AP_INVOICES_ALL, AP_INVOICE_PAYMENTS_ALL'],

    // ── Inventory & Costing ──
    ['INV', 'Receipt to Cost', 'P_RECEIPT_NUMBER', 'Receipt number',
        'Inbound goods to accounting: receipt → delivery → inventory transaction → cost transaction → distributions → accounting.',
        ['Receipt', 'Receiving transactions', 'Inventory transaction', 'Cost transaction', 'Cost distributions', 'Accounting'],
        'RCV_SHIPMENT_HEADERS, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, CST_COST_DISTRIBUTIONS, CST_COST_DISTRIBUTION_LINES, XLA_AE_LINES'],
    ['INV', 'Item to Onhand', 'P_ITEM_NUMBER', 'Item number',
        'An item end to end: item master → organisation assignments → costs → onhand → recent transactions → open reservations.',
        ['Item master', 'Organisation items', 'Item cost', 'Onhand', 'Recent transactions', 'Reservations'],
        'EGP_SYSTEM_ITEMS_B, INV_ORG_PARAMETERS, CST_ITEM_COSTS / CST_PERPAVG_COST, INV_ONHAND_QUANTITIES_DETAIL, INV_MATERIAL_TXNS, INV_RESERVATIONS'],
    ['INV', 'Inventory Adjustment to Accounting', 'P_TRANSACTION_ID', 'Inventory transaction id',
        'Miscellaneous / cycle count / physical adjustment: transaction → cost → distributions → subledger accounting → GL.',
        ['Inventory transaction', 'Cost transaction', 'Cost distributions', 'Subledger accounting', 'GL journal'],
        'INV_MATERIAL_TXNS, CST_INV_TRANSACTIONS, CST_TRANSACTIONS, CST_COST_DISTRIBUTION_LINES, XLA_AE_HEADERS, XLA_AE_LINES, GL_JE_LINES'],
    ['INV', 'Transfer Order', 'P_TRANSFER_ORDER', 'Transfer order number',
        'Inter-organisation transfer: transfer order → shipment → in-transit → receipt → transfer costs → accounting.',
        ['Transfer order', 'Transfer lines', 'Shipment', 'In-transit', 'Receipt', 'Cost', 'Accounting'],
        'INV_TRANSFER_ORDER_HEADERS, INV_TRANSFER_ORDER_LINES, WSH_DELIVERY_DETAILS, INV_MATERIAL_TXNS, RCV_TRANSACTIONS, CST_INV_TRANSACTIONS'],
    ['INV', 'Lot Traceability', 'P_LOT_NUMBER', 'Lot number',
        'Where a lot came from and went: lot → receipts → issues/transfers → shipments to customers.',
        ['Lot', 'Lot onhand', 'Receipts', 'Issues & transfers', 'Shipments', 'Customers'],
        'INV_LOT_NUMBERS, INV_ONHAND_QUANTITIES_DETAIL, INV_TRANSACTION_LOT_NUMBERS, INV_MATERIAL_TXNS, WSH_DELIVERY_DETAILS, DOO_HEADERS_ALL'],
    ['INV', 'Serial Traceability', 'P_SERIAL_NUMBER', 'Serial number',
        'A serial number\'s history: current status → transactions → shipment → customer.',
        ['Serial', 'Serial transactions', 'Receipt', 'Shipment', 'Customer order'],
        'INV_SERIAL_NUMBERS, INV_TRANSACTION_SERIAL_NUMS / INV_SERIAL_TXNS, INV_MATERIAL_TXNS, WSH_DELIVERY_DETAILS, DOO_HEADERS_ALL'],

    // ── Manufacturing ──
    ['MFG', 'Plan to Produce (Work Order)', 'P_WORK_ORDER', 'Work order number',
        'Discrete work order: work order → operations → material issues → resource charges → completions → WIP costing → accounting.',
        ['Work order', 'Operations', 'Material requirements & issues', 'Resource transactions', 'Completions', 'WIP cost', 'Accounting'],
        'WIE_WORK_ORDERS_B, WIE_WO_OPERATIONS_B, WIE_WO_OPERATION_MATERIALS, WIE_MATERIAL_TXNS / INV_MATERIAL_TXNS, WIE_RESOURCE_TXNS, CST_WORK_ORDER_COSTS, XLA_AE_LINES'],
    ['MFG', 'Make to Order', 'P_ORDER_NUMBER', 'Sales order number',
        'Built for a customer order: sales order → supply order → work order → completion → reservation → shipment.',
        ['Sales order', 'Supply order', 'Work order', 'Completion', 'Reservation', 'Shipment'],
        'DOO_FULFILL_LINES_ALL, DOS_SUPPLY_HEADERS, WIE_WORK_ORDERS_B, INV_MATERIAL_TXNS, INV_RESERVATIONS, WSH_DELIVERY_DETAILS'],

    // ── Financials ──
    ['FIN', 'Invoice to Cash (Receivables)', 'P_TRX_NUMBER', 'AR transaction number',
        'A receivables invoice to cash: invoice → payment schedule → receipt applications → adjustments → accounting.',
        ['AR invoice', 'Lines', 'Distributions', 'Payment schedule', 'Receipt applications', 'Adjustments', 'Accounting'],
        'RA_CUSTOMER_TRX_ALL, RA_CUSTOMER_TRX_LINES_ALL, RA_CUST_TRX_LINE_GL_DIST_ALL, AR_PAYMENT_SCHEDULES_ALL, AR_RECEIVABLE_APPLICATIONS_ALL, AR_ADJUSTMENTS_ALL, XLA_AE_LINES'],
    ['FIN', 'Receipt to Bank Reconciliation', 'P_RECEIPT_NUMBER', 'Receipt number',
        'A customer receipt: receipt → applications → remittance → clearing → bank statement line → reconciliation.',
        ['Receipt', 'Applications', 'Remittance batch', 'Receipt history', 'Bank statement line', 'Reconciliation'],
        'AR_CASH_RECEIPTS_ALL, AR_RECEIVABLE_APPLICATIONS_ALL, AR_CASH_RECEIPT_HISTORY_ALL, AR_BATCHES_ALL, CE_STATEMENT_LINES, CE_STATEMENT_RECONS'],
    ['FIN', 'Payment to Bank Reconciliation', 'P_CHECK_NUMBER', 'Payment number',
        'A supplier payment: payment → paid invoices → payment accounting → bank statement line → reconciliation.',
        ['Payment', 'Invoices paid', 'Payment accounting', 'Bank statement line', 'Reconciliation'],
        'AP_CHECKS_ALL, AP_INVOICE_PAYMENTS_ALL, AP_PAYMENT_HISTORY_ALL, XLA_AE_LINES, CE_STATEMENT_LINES, CE_STATEMENT_RECONS'],
    ['FIN', 'Record to Report', 'P_JE_BATCH_NAME', 'Journal batch name',
        'Journals to balances: journal batch → headers → lines → subledger links → posting → balances.',
        ['Journal batch', 'Journal headers', 'Journal lines', 'Subledger references', 'Posting status', 'Account balances'],
        'GL_JE_BATCHES, GL_JE_HEADERS, GL_JE_LINES, GL_IMPORT_REFERENCES, XLA_AE_LINES, GL_BALANCES, GL_CODE_COMBINATIONS'],
    ['FIN', 'Subledger to GL (Period Close)', 'P_PERIOD_NAME', 'Period name',
        'What blocks a close: subledger period statuses → unaccounted events → accounting errors → untransferred entries → GL period status.',
        ['Period statuses', 'Unaccounted events', 'Accounting errors', 'Not transferred to GL', 'GL journals', 'GL period'],
        'GL_PERIOD_STATUSES, XLA_EVENTS, XLA_ACCOUNTING_ERRORS, XLA_AE_HEADERS, GL_JE_HEADERS, GL_PERIODS'],
    ['FIN', 'Customer Onboarding', 'P_ACCOUNT_NUMBER', 'Customer account number',
        'Is the customer ready to trade: party → account → sites and uses → profiles and credit limits → contacts.',
        ['Party', 'Customer account', 'Account sites', 'Site uses (bill-to / ship-to)', 'Profiles & credit', 'Contacts'],
        'HZ_PARTIES, HZ_CUST_ACCOUNTS, HZ_CUST_ACCT_SITES_ALL, HZ_CUST_SITE_USES_ALL, HZ_CUSTOMER_PROFILES_F, HZ_CUST_ACCOUNT_ROLES'],
    ['FIN', 'Acquire to Retire (Assets)', 'P_ASSET_NUMBER', 'Asset number',
        'Fixed asset lifecycle: source invoice → mass addition → asset → books → depreciation → transfers → retirement.',
        ['Source invoice', 'Mass addition', 'Asset', 'Asset books', 'Depreciation', 'Transfers', 'Retirement'],
        'AP_INVOICE_LINES_ALL, FA_MASS_ADDITIONS, FA_ADDITIONS_B, FA_BOOKS, FA_DEPRN_DETAIL, FA_TRANSACTION_HEADERS, FA_RETIREMENTS'],
    ['FIN', 'Intercompany Transaction', 'P_IC_BATCH', 'Intercompany batch number',
        'Intercompany: batch → transactions → provider/receiver distributions → AR/AP invoices → journals.',
        ['Intercompany batch', 'Transactions', 'Distributions', 'AR invoice', 'AP invoice', 'Journals'],
        'FUN_TRX_BATCHES, FUN_TRX_HEADERS, FUN_DIST_LINES, RA_CUSTOMER_TRX_ALL, AP_INVOICES_ALL, GL_JE_LINES'],
    ['FIN', 'Transaction Tax', 'P_TRX_NUMBER', 'Invoice number',
        'How tax was calculated: invoice → tax lines → rates and jurisdictions → tax distributions → accounting.',
        ['Invoice', 'Tax lines', 'Tax rates', 'Jurisdictions', 'Tax distributions', 'Accounting'],
        'RA_CUSTOMER_TRX_ALL / AP_INVOICES_ALL, ZX_LINES, ZX_RATES_B, ZX_JURISDICTIONS_B, ZX_REC_NREC_DIST, XLA_AE_LINES'],

    // ── Projects ──
    ['PRJ', 'Project Contract to Cash', 'P_PROJECT_NUMBER', 'Project number',
        'Project billing: project → contract → costs → billing events → invoices → AR invoice → revenue.',
        ['Project', 'Contract', 'Expenditures', 'Billing events', 'Project invoice', 'AR invoice', 'Revenue'],
        'PJF_PROJECTS_ALL_B, OKC_K_HEADERS_ALL_B, PJC_EXP_ITEMS_ALL, PJB_BILLING_EVENTS, PJB_INVOICE_HEADERS, RA_CUSTOMER_TRX_ALL, PJB_REV_DISTRIBUTIONS'],
    ['PRJ', 'Procure to Project Cost', 'P_PO_NUMBER', 'Purchase order number',
        'Project-related purchase: PO with project → receipt → supplier invoice → project cost lines → accounting.',
        ['Purchase order', 'Project distributions', 'Receipt', 'Supplier invoice', 'Project costs', 'Accounting'],
        'PO_HEADERS_ALL, PO_DISTRIBUTIONS_ALL (PJC columns), RCV_TRANSACTIONS, AP_INVOICE_DISTRIBUTIONS_ALL, PJC_EXP_ITEMS_ALL, PJC_COST_DIST_LINES_ALL'],
    ['PRJ', 'Time to Project Cost', 'P_PROJECT_NUMBER', 'Project number',
        'Labour costing: timecards → project expenditures → cost distributions → accounting.',
        ['Project', 'Timecards', 'Labor expenditures', 'Cost distributions', 'Accounting'],
        'PJF_PROJECTS_ALL_B, HWM_TM_REC, PJC_EXP_ITEMS_ALL, PJC_COST_DIST_LINES_ALL, XLA_AE_LINES'],

    // ── Logistics ──
    ['LOG', 'Pick to Ship', 'P_ORDER_NUMBER', 'Sales order number',
        'Warehouse execution: fulfillment lines → delivery details → pick waves / move orders → picks → pack → ship confirm.',
        ['Fulfillment lines', 'Delivery details', 'Pick wave', 'Movement requests', 'Pick transactions', 'Delivery', 'Ship confirm'],
        'DOO_FULFILL_LINES_ALL, WSH_DELIVERY_DETAILS, WSH_PICKING_BATCHES, INV_TXN_REQUEST_HEADERS, INV_TXN_REQUEST_LINES, WSH_NEW_DELIVERIES, INV_MATERIAL_TXNS'],
    ['LOG', 'Ship Confirm to Invoice', 'P_DELIVERY_NAME', 'Delivery / shipment number',
        'After shipping: delivery → trip → interfaced to receivables → AutoInvoice → invoice.',
        ['Delivery', 'Delivery lines', 'Trip / stops', 'AR interface', 'AR invoice'],
        'WSH_NEW_DELIVERIES, WSH_DELIVERY_DETAILS, WSH_TRIPS, WSH_TRIP_STOPS, RA_INTERFACE_LINES_ALL, RA_CUSTOMER_TRX_LINES_ALL'],
    ['LOG', 'Inbound ASN to Putaway', 'P_SHIPMENT_NUMBER', 'ASN / shipment number',
        'Supplier shipment arriving: ASN → receipt → inspection → putaway → onhand.',
        ['ASN', 'Shipment lines', 'Receipt', 'Inspection', 'Putaway', 'Onhand'],
        'RCV_SHIPMENT_HEADERS, RCV_SHIPMENT_LINES, RCV_TRANSACTIONS, INV_MATERIAL_TXNS, INV_ONHAND_QUANTITIES_DETAIL'],
    // ── Reconciliations (period totals: subledger ↔ subledger accounting ↔ GL, plus the items behind each difference) ──
    ['REC', 'AP to GL Reconciliation', 'P_PERIOD_NAME', 'Period name',
        'Payables liability: open AP balance vs Payables subledger accounting vs GL liability accounts — with unaccounted, untransferred and manual GL entries that explain differences.',
        ['AP open balance (trial balance)', 'AP subledger accounting by liability account', 'Transferred to GL', 'GL liability balance', 'Unaccounted invoices & payments', 'Accounted but not transferred', 'Manual GL journals on liability accounts', 'Differences by account'],
        'AP_INVOICES_ALL, AP_PAYMENT_SCHEDULES_ALL, AP_INVOICE_PAYMENTS_ALL, XLA_TRANSACTION_ENTITIES, XLA_AE_HEADERS, XLA_AE_LINES (accounting_class LIABILITY), XLA_TRIAL_BALANCES, GL_JE_HEADERS, GL_JE_LINES, GL_BALANCES, GL_LEDGERS, GL_CODE_COMBINATIONS', flRec(FL_REC_BU)],
    ['REC', 'AR to GL Reconciliation', 'P_PERIOD_NAME', 'Period name',
        'Receivables control: aged open AR vs Receivables accounting vs GL receivable accounts — with unposted transactions, unapplied cash and manual journals.',
        ['AR open balance (aging)', 'AR subledger accounting by receivable account', 'Transferred to GL', 'GL receivable balance', 'Incomplete / unaccounted transactions', 'Unapplied & on-account receipts', 'Manual GL journals on receivable accounts', 'Differences by account'],
        'AR_PAYMENT_SCHEDULES_ALL, RA_CUSTOMER_TRX_ALL, RA_CUST_TRX_LINE_GL_DIST_ALL, AR_RECEIVABLE_APPLICATIONS_ALL, AR_CASH_RECEIPTS_ALL, XLA_AE_HEADERS, XLA_AE_LINES (RECEIVABLE), GL_JE_LINES, GL_BALANCES, GL_CODE_COMBINATIONS', flRec(FL_REC_BU)],
    ['REC', 'Unapplied Cash & Customer Deposits to GL', 'P_PERIOD_NAME', 'Period name',
        'Unapplied, on-account and unidentified receipts in Receivables vs the GL unapplied / unidentified cash accounts.',
        ['Unapplied receipts', 'On-account & unidentified receipts', 'Receipt accounting', 'GL unapplied cash balance', 'Differences'],
        'AR_CASH_RECEIPTS_ALL, AR_RECEIVABLE_APPLICATIONS_ALL (status UNAPP/ACC/UNID), XLA_AE_LINES, GL_BALANCES', flRec(FL_REC_BU)],
    ['REC', 'Bank (Cash Management) to GL', 'P_PERIOD_NAME', 'Period name',
        'Each bank account: bank statement closing balance vs system cash (GL cash account) — with unreconciled statement lines and uncleared payments/receipts.',
        ['Bank accounts & GL cash accounts', 'Statement closing balances', 'GL cash balance', 'Unreconciled statement lines', 'Uncleared payments', 'Uncleared receipts', 'Differences by bank account'],
        'CE_BANK_ACCOUNTS, CE_STATEMENT_HEADERS, CE_STATEMENT_LINES, CE_STATEMENT_RECONS, AP_CHECKS_ALL, AR_CASH_RECEIPTS_ALL, GL_BALANCES, GL_CODE_COMBINATIONS', flRec()],
    ['REC', 'Payments to Bank Clearing', 'P_PERIOD_NAME', 'Period name',
        'Supplier payments issued vs cleared in Cash Management vs cash clearing / cash accounts in GL.',
        ['Payments issued', 'Payment accounting', 'Cleared payments', 'Uncleared payments', 'GL cash clearing balance', 'Differences'],
        'AP_CHECKS_ALL, AP_PAYMENT_HISTORY_ALL, XLA_AE_LINES (CASH_CLEARING), CE_STATEMENT_RECONS, GL_BALANCES', flRec(FL_REC_BU)],
    ['REC', 'Fixed Assets to GL', 'P_PERIOD_NAME', 'Period name',
        'Asset cost and accumulated depreciation by book and category vs the GL asset cost / reserve accounts — with unposted asset transactions and pending mass additions.',
        ['Asset cost by category', 'Accumulated depreciation by category', 'Depreciation for the period', 'Asset accounting', 'GL asset cost & reserve balances', 'Unposted asset transactions', 'Pending mass additions', 'Differences by account'],
        'FA_BOOKS, FA_CATEGORY_BOOKS, FA_DEPRN_SUMMARY, FA_DEPRN_DETAIL, FA_TRANSACTION_HEADERS, FA_MASS_ADDITIONS, XLA_AE_LINES (application 140), GL_BALANCES', flRec([['P_LEDGER_NAME', 'Ledger name'], ['P_BOOK_TYPE_CODE', 'Asset book'], ['P_PERIOD_NAME', 'Period name (e.g. SEP-26)']])],
    ['REC', 'CIP & Asset Clearing to GL', 'P_PERIOD_NAME', 'Period name',
        'Construction-in-process and AP asset clearing: invoice lines sent to Assets vs mass additions vs CIP assets vs the GL clearing accounts.',
        ['AP invoice lines to Assets', 'Mass additions', 'CIP assets', 'Asset clearing accounting', 'GL clearing balance', 'Differences'],
        'AP_INVOICE_DISTRIBUTIONS_ALL (assets_tracking_flag), FA_MASS_ADDITIONS, FA_ASSET_INVOICES, FA_ADDITIONS_B, XLA_AE_LINES, GL_BALANCES', flRec()],
    ['REC', 'Inventory Valuation to GL', 'P_PERIOD_NAME', 'Period name',
        'Perpetual inventory value by organisation and subinventory (cost × onhand) vs costed inventory accounting vs GL inventory valuation accounts.',
        ['Onhand quantity × cost by org', 'Inventory valuation (cost books)', 'Cost accounting distributions', 'Transferred to GL', 'GL inventory balance', 'Uncosted transactions', 'Differences by account'],
        'INV_ONHAND_QUANTITIES_DETAIL, CST_PERPAVG_COST / CST_ITEM_COSTS, CST_INV_TRANSACTIONS, CST_COST_DISTRIBUTION_LINES, CST_COST_BOOKS_B, XLA_AE_LINES (application 10096), GL_BALANCES', flRec([['P_LEDGER_NAME', 'Ledger name'], ['P_COST_BOOK', 'Cost book'], ['P_PERIOD_NAME', 'Period name (e.g. SEP-26)']])],
    ['REC', 'Receipt Accrual (AP/PO) to GL', 'P_PERIOD_NAME', 'Period name',
        'Uninvoiced receipts: received-not-invoiced value by PO vs receipt accounting accrual vs GL accrual account — with invoices matched but not accounted.',
        ['Receipts not invoiced', 'Receipt accrual accounting', 'Invoices clearing the accrual', 'GL accrual balance', 'Accrual aging by supplier', 'Differences'],
        'RCV_TRANSACTIONS, PO_LINE_LOCATIONS_ALL (quantity_received vs quantity_billed), CMR_RCV_EVENTS, CMR_RCV_DISTRIBUTIONS, AP_INVOICE_DISTRIBUTIONS_ALL, XLA_AE_LINES (ACCRUAL), GL_BALANCES', flRec(FL_REC_BU)],
    ['REC', 'COGS & Deferred COGS to Revenue', 'P_PERIOD_NAME', 'Period name',
        'Revenue–COGS matching: shipped cost deferred vs recognised COGS vs recognised revenue per order line — lines with revenue but no COGS (or the reverse).',
        ['Shipped lines & cost', 'Deferred COGS', 'Recognised COGS', 'Recognised revenue', 'Lines with revenue but no COGS', 'Lines with COGS but no revenue', 'GL deferred COGS & COGS balances'],
        'CST_COGS_RECOGNITION_EVENTS / CST_REVENUE_LINES, CST_COST_DISTRIBUTION_LINES, RA_CUST_TRX_LINE_GL_DIST_ALL, DOO_FULFILL_LINES_ALL, XLA_AE_LINES, GL_BALANCES', flRec()],
    ['REC', 'In-Transit Inventory to GL', 'P_PERIOD_NAME', 'Period name',
        'Goods shipped between organisations but not yet received vs the intransit valuation in costing and GL.',
        ['Intransit shipments', 'Not yet received', 'Intransit cost accounting', 'GL intransit balance', 'Differences'],
        'INV_MATERIAL_TXNS (intransit shipment/receipt), RCV_SHIPMENT_LINES, CST_COST_DISTRIBUTION_LINES, XLA_AE_LINES, GL_BALANCES', flRec()],
    ['REC', 'WIP Valuation to GL', 'P_PERIOD_NAME', 'Period name',
        'Open work orders: material, resource and overhead charged less completions vs WIP accounting vs GL WIP accounts.',
        ['Open work orders', 'Material issued', 'Resource & overhead charged', 'Completions & scrap', 'WIP accounting', 'GL WIP balance', 'Differences'],
        'WIE_WORK_ORDERS_B, INV_MATERIAL_TXNS, WIE_RESOURCE_TXNS, CST_WORK_ORDER_COSTS / CST_WO_COST_DETAILS, XLA_AE_LINES, GL_BALANCES', flRec()],
    ['REC', 'Shipped not Invoiced (OM to AR)', 'P_PERIOD_NAME', 'Period name',
        'Order lines shipped or closed but not invoiced — stuck in the AR interface or waiting for AutoInvoice — valued at selling price.',
        ['Shipped fulfillment lines', 'Sent to AR interface', 'Interface errors', 'Invoiced lines', 'Shipped not invoiced (value)', 'Aging'],
        'DOO_FULFILL_LINES_ALL, WSH_DELIVERY_DETAILS, RA_INTERFACE_LINES_ALL, RA_INTERFACE_ERRORS_ALL, RA_CUSTOMER_TRX_LINES_ALL', flRec(FL_REC_BU)],
    ['REC', 'Revenue Management Contract Balances to GL', 'P_PERIOD_NAME', 'Period name',
        'ASC 606 / IFRS 15: contract liability (deferred revenue) and contract asset (unbilled) balances vs GL.',
        ['Customer contracts', 'Billed vs satisfied amounts', 'Contract liability', 'Contract asset (unbilled)', 'Revenue accounting', 'GL balances', 'Differences'],
        'VRM_CUSTOMER_CONTRACTS, VRM_PERF_OBLIGATIONS, VRM_SATISFACTION_EVENTS, VRM_BILLING_LINES, XLA_AE_LINES (application 10703), GL_BALANCES', flRec()],
    ['REC', 'Project Costs to GL', 'P_PERIOD_NAME', 'Period name',
        'Project expenditures by project and source (AP, inventory, labour, expenses) vs project cost accounting vs GL.',
        ['Expenditures by source', 'Cost distributions', 'Project cost accounting', 'Transferred to GL', 'GL project cost / WIP balances', 'Unaccounted cost lines', 'Differences'],
        'PJC_EXP_ITEMS_ALL, PJC_COST_DIST_LINES_ALL, PJF_PROJECTS_ALL_B, XLA_AE_LINES (application 10036), GL_BALANCES', flRec(FL_REC_BU)],
    ['REC', 'Project Revenue & Unbilled to GL', 'P_PERIOD_NAME', 'Period name',
        'Project revenue recognised vs invoiced: unbilled receivables and unearned revenue by contract vs GL.',
        ['Contracts', 'Revenue distributions', 'Project invoices', 'Unbilled receivables', 'Unearned revenue', 'GL balances', 'Differences'],
        'OKC_K_HEADERS_ALL_B, PJB_REV_DISTRIBUTIONS, PJB_INVOICE_HEADERS, PJB_INV_LINE_DISTS, XLA_AE_LINES, GL_BALANCES', flRec(FL_REC_BU)],
    ['REC', 'Intercompany AR to AP', 'P_PERIOD_NAME', 'Period name',
        'Intercompany receivables of the provider vs payables of the receiver for each pair of legal entities — with one-sided and mismatched transactions.',
        ['Intercompany transactions', 'Provider AR invoices', 'Receiver AP invoices', 'Matched pairs', 'One-sided transactions', 'Amount mismatches', 'Differences by entity pair'],
        'FUN_TRX_BATCHES, FUN_TRX_HEADERS, FUN_DIST_LINES, RA_CUSTOMER_TRX_ALL, AP_INVOICES_ALL, XLE_ENTITY_PROFILES', flRec()],
    ['REC', 'Intercompany Balances in GL', 'P_PERIOD_NAME', 'Period name',
        'Intercompany receivable vs payable account balances in GL by counterparty segment — the out-of-balance pairs to eliminate.',
        ['IC receivable balances by counterparty', 'IC payable balances by counterparty', 'Out-of-balance pairs', 'Journals causing the difference'],
        'GL_BALANCES, GL_CODE_COMBINATIONS (intercompany segment), GL_JE_LINES, FUN_BALANCE_ACCOUNTS', flRec()],
    ['REC', 'Tax to GL', 'P_PERIOD_NAME', 'Period name',
        'Tax registers (output and input tax by regime/rate) vs tax accounting vs GL tax accounts — with transactions missing tax accounting.',
        ['Output tax (sales)', 'Input tax (purchases)', 'Tax accounting', 'GL tax balances', 'Tax lines not accounted', 'Differences by tax account'],
        'ZX_LINES, ZX_REC_NREC_DIST, ZX_RATES_B, ZX_REGIMES_B, XLA_AE_LINES, GL_BALANCES', flRec()],
    ['REC', 'Expenses to AP to GL', 'P_PERIOD_NAME', 'Period name',
        'Employee expenses: approved reports vs Payables invoices created vs payments vs GL employee liability.',
        ['Approved expense reports', 'Expense invoices in AP', 'Reports not yet in AP', 'Payments to employees', 'GL employee liability', 'Differences'],
        'EXM_EXPENSE_REPORTS, EXM_EXPENSES, AP_INVOICES_ALL (EXPENSE REPORT), AP_INVOICE_PAYMENTS_ALL, XLA_AE_LINES, GL_BALANCES', flRec(FL_REC_BU)],
    ['REC', 'Subledger to GL Journal Import', 'P_PERIOD_NAME', 'Period name',
        'For every subledger: accounted entries vs transferred vs imported and posted in GL — by journal source/category, with gaps.',
        ['Subledger entries by application', 'Transferred to GL', 'GL journals by source', 'Posted vs unposted', 'Entries in error / not transferred', 'Differences by source'],
        'XLA_AE_HEADERS, XLA_AE_LINES, XLA_SUBLEDGERS, GL_IMPORT_REFERENCES, GL_JE_HEADERS, GL_JE_LINES, GL_JE_SOURCES_TL', flRec()],
    ['REC', 'Unaccounted Events & Accounting Errors', 'P_PERIOD_NAME', 'Period name',
        'Close blockers in every subledger: unprocessed events, draft entries and accounting errors by application and event class.',
        ['Unprocessed events by application', 'Draft / invalid entries', 'Accounting errors', 'Oldest items', 'Transactions behind them'],
        'XLA_EVENTS, XLA_TRANSACTION_ENTITIES, XLA_AE_HEADERS (accounting_entry_status_code), XLA_ACCOUNTING_ERRORS, XLA_SUBLEDGERS', flRec()],
    ['REC', 'Unposted & Suspense Journals', 'P_PERIOD_NAME', 'Period name',
        'GL hygiene before close: unposted journals, journals in error, suspense account balances and journals hitting suspense.',
        ['Unposted journals', 'Journals in error', 'Suspense account balance', 'Journals posted to suspense', 'By source & category'],
        'GL_JE_BATCHES, GL_JE_HEADERS, GL_JE_LINES, GL_SUSPENSE_ACCOUNTS, GL_BALANCES, GL_CODE_COMBINATIONS', flRec()],
    ['REC', 'Trial Balance Integrity', 'P_PERIOD_NAME', 'Period name',
        'Does the ledger balance: period activity from journal lines vs GL balances, debits vs credits by balancing segment, and opening + activity = closing.',
        ['Balances by account', 'Journal activity for the period', 'Activity vs balance movement', 'Debit = credit by balancing segment', 'Opening + activity = closing', 'Differences'],
        'GL_BALANCES, GL_JE_LINES, GL_JE_HEADERS, GL_CODE_COMBINATIONS, GL_PERIODS, GL_LEDGERS', flRec()],
    ['REC', 'Foreign Currency Revaluation Check', 'P_PERIOD_NAME', 'Period name',
        'Open foreign-currency balances revalued at period-end rates: revaluation journals vs expected unrealised gain/loss.',
        ['Foreign-currency balances', 'Period-end rates', 'Expected revaluation', 'Revaluation journals', 'Differences'],
        'GL_BALANCES (entered vs accounted), GL_DAILY_RATES, GL_JE_HEADERS (Revaluation), GL_JE_LINES', flRec()]
];
