/* ═══════════════════════════════════════════════════════════════
   Fusion SQL — starter setup checklist
   Loaded into WMS_FUSION_SETUP_TASKS the first time the Fusion Setups tab
   is opened ("Load starter checklist"). Each check SQL returns the records
   that prove the setup exists; the task is DONE when it returns >= min rows.
   These are a starting point — review/edit the SQL for your pod in the tab.
   Row format: [module, code, seq, task, fsmTask, description, sql, mandatory, minRows]
   ═══════════════════════════════════════════════════════════════ */

var FS_SETUP_MODULES = [
    ['COMMON', 'Enterprise Structures'],
    ['GL', 'General Ledger'],
    ['TAX', 'Tax'],
    ['CM', 'Cash Management'],
    ['AP', 'Payables'],
    ['AR', 'Receivables'],
    ['FA', 'Fixed Assets'],
    ['PO', 'Procurement'],
    ['INV', 'Inventory'],
    ['SHIP', 'Shipping'],
    ['OM', 'Order Management'],
    ['SEC', 'Users & Security'],
    ['HCM', 'HCM Core']
];

var FS_SETUP_SEED = [
    // ── Enterprise Structures ──
    ['COMMON', 'COMMON_LEGAL_ENTITIES', 10, 'Legal entities', 'Manage Legal Entity', 'At least one legal entity is defined.',
        'SELECT legal_entity_id, name, legal_entity_identifier FROM xle_entity_profiles', 'Y', 1],
    ['COMMON', 'COMMON_BUSINESS_UNITS', 20, 'Business units', 'Manage Business Unit', 'Business units exist.',
        'SELECT bu_id, bu_name FROM fun_all_business_units_v', 'Y', 1],
    ['COMMON', 'COMMON_REF_DATA_SETS', 30, 'Reference data sets', 'Manage Reference Data Sets', 'Reference data sets (SetIDs) are defined.',
        'SELECT * FROM fnd_setid_sets', 'Y', 1],
    ['COMMON', 'COMMON_LOCATIONS', 40, 'Locations', 'Manage Locations', 'Work/ship/bill-to locations exist.',
        'SELECT * FROM hr_locations_all', 'Y', 1],
    ['COMMON', 'COMMON_CURRENCIES', 50, 'Enabled currencies', 'Manage Currencies', 'Currencies enabled for use.',
        "SELECT currency_code, enabled_flag FROM fnd_currencies_b WHERE enabled_flag = 'Y'", 'Y', 1],
    ['COMMON', 'COMMON_INV_ORGS', 60, 'Inventory organizations', 'Manage Inventory Organizations', 'Inventory organizations with parameters.',
        'SELECT organization_id, organization_code, master_organization_id FROM inv_org_parameters', 'Y', 1],

    // ── General Ledger ──
    ['GL', 'GL_LEDGERS', 10, 'Ledgers', 'Manage Primary Ledgers', 'Primary (and secondary) ledgers with currency, calendar and chart of accounts.',
        'SELECT ledger_id, name, ledger_category_code, currency_code, period_set_name, chart_of_accounts_id FROM gl_ledgers', 'Y', 1],
    ['GL', 'GL_CALENDAR', 20, 'Accounting calendar', 'Manage Accounting Calendars', 'Accounting calendar periods are generated.',
        'SELECT period_set_name, period_name, period_year, start_date, end_date FROM gl_periods', 'Y', 1],
    ['GL', 'GL_VALUE_SETS', 30, 'Chart of accounts value sets', 'Manage Chart of Accounts Value Sets', 'Value sets for the chart of accounts segments.',
        'SELECT * FROM fnd_vs_value_sets', 'Y', 1],
    ['GL', 'GL_CODE_COMBINATIONS', 40, 'Account combinations', 'Manage Account Combinations', 'Enabled account code combinations exist.',
        "SELECT code_combination_id, chart_of_accounts_id, enabled_flag FROM gl_code_combinations WHERE enabled_flag = 'Y'", 'Y', 1],
    ['GL', 'GL_OPEN_PERIODS', 50, 'Open GL period', 'Manage Accounting Periods', 'At least one General Ledger period is open.',
        "SELECT l.name AS ledger, ps.period_name, ps.closing_status FROM gl_period_statuses ps JOIN gl_ledgers l ON l.ledger_id = ps.ledger_id WHERE ps.application_id = 101 AND ps.closing_status = 'O'", 'Y', 1],
    ['GL', 'GL_JE_SOURCES', 60, 'Journal sources', 'Manage Journal Sources', 'Journal sources are defined.',
        'SELECT * FROM gl_je_sources_b', 'Y', 1],
    ['GL', 'GL_JE_CATEGORIES', 70, 'Journal categories', 'Manage Journal Categories', 'Journal categories are defined.',
        'SELECT * FROM gl_je_categories_b', 'Y', 1],
    ['GL', 'GL_DAILY_RATES', 80, 'Daily conversion rates (last 30 days)', 'Manage Daily Rates', 'Recent daily currency conversion rates are loaded.',
        'SELECT from_currency, to_currency, conversion_type, conversion_date, conversion_rate FROM gl_daily_rates WHERE conversion_date >= TRUNC(SYSDATE) - 30', 'N', 1],
    ['GL', 'GL_JOURNALS_POSTED', 90, 'Posted journals', 'Create Journal', 'Journals have been posted (usage check).',
        "SELECT je_header_id, name, period_name, status FROM gl_je_headers WHERE status = 'P'", 'N', 1],

    // ── Tax ──
    ['TAX', 'TAX_REGIMES', 10, 'Tax regimes', 'Manage Tax Regimes', 'Tax regimes are defined.',
        'SELECT * FROM zx_regimes_b', 'Y', 1],
    ['TAX', 'TAX_TAXES', 20, 'Taxes', 'Manage Taxes', 'Taxes are defined within the regimes.',
        'SELECT * FROM zx_taxes_b', 'Y', 1],
    ['TAX', 'TAX_STATUSES', 30, 'Tax statuses', 'Manage Tax Statuses', 'Tax statuses are defined.',
        'SELECT * FROM zx_status_b', 'Y', 1],
    ['TAX', 'TAX_RATES', 40, 'Tax rates', 'Manage Tax Rates and Tax Recovery Rates', 'Tax rates are defined.',
        'SELECT * FROM zx_rates_b', 'Y', 1],
    ['TAX', 'TAX_JURISDICTIONS', 50, 'Tax jurisdictions', 'Manage Tax Jurisdictions', 'Tax jurisdictions are defined.',
        'SELECT * FROM zx_jurisdictions_b', 'N', 1],
    ['TAX', 'TAX_PARTY_PROFILES', 60, 'Party tax profiles', 'Manage Party Tax Profiles', 'Legal entity / BU tax profiles exist.',
        'SELECT * FROM zx_party_tax_profile', 'Y', 1],

    // ── Cash Management ──
    ['CM', 'CM_BANK_BRANCHES', 10, 'Banks and branches', 'Manage Bank Branches', 'Banks and bank branches are defined.',
        'SELECT * FROM ce_bank_branches_v', 'Y', 1],
    ['CM', 'CM_BANK_ACCOUNTS', 20, 'Internal bank accounts', 'Manage Bank Accounts', 'Company bank accounts are defined.',
        'SELECT bank_account_id, bank_account_name, bank_account_num, currency_code FROM ce_bank_accounts', 'Y', 1],
    ['CM', 'CM_BANK_ACCT_USES', 30, 'Bank account uses (BU access)', 'Manage Bank Accounts', 'Bank accounts are granted to business units.',
        'SELECT * FROM ce_bank_acct_uses_all', 'Y', 1],

    // ── Payables ──
    ['AP', 'AP_FIN_OPTIONS', 10, 'Common options for Payables and Procurement', 'Manage Common Options for Payables and Procurement', 'Financials options exist per business unit.',
        'SELECT * FROM financials_system_params_all', 'Y', 1],
    ['AP', 'AP_OPTIONS', 20, 'Invoice / payment options', 'Manage Invoice Options', 'Payables system options exist per business unit.',
        'SELECT * FROM ap_system_parameters_all', 'Y', 1],
    ['AP', 'AP_TERMS', 30, 'Payment terms', 'Manage Payables Payment Terms', 'Payables payment terms are defined.',
        'SELECT * FROM ap_terms_b', 'Y', 1],
    ['AP', 'AP_TOLERANCES', 40, 'Invoice tolerances', 'Manage Invoice Tolerances', 'Invoice tolerance templates are defined.',
        'SELECT * FROM ap_tolerance_templates', 'N', 1],
    ['AP', 'AP_DIST_SETS', 50, 'Distribution sets', 'Manage Distribution Sets', 'Distribution sets are defined.',
        'SELECT * FROM ap_distribution_sets_all', 'N', 1],
    ['AP', 'AP_PAYMENT_METHODS', 60, 'Payment methods', 'Manage Payment Methods', 'Payment methods are defined.',
        'SELECT * FROM iby_payment_methods_b', 'Y', 1],
    ['AP', 'AP_PPP', 70, 'Payment process profiles', 'Manage Payment Process Profiles', 'Payment process profiles are defined.',
        'SELECT * FROM iby_acct_pmt_profiles_b', 'Y', 1],
    ['AP', 'AP_SUPPLIERS', 80, 'Suppliers', 'Manage Suppliers', 'Suppliers exist.',
        'SELECT vendor_id, segment1 AS supplier_number, party_id FROM poz_suppliers', 'Y', 1],
    ['AP', 'AP_SUPPLIER_SITES', 90, 'Supplier sites', 'Manage Suppliers', 'Supplier sites exist (needed to invoice and pay).',
        'SELECT * FROM poz_supplier_sites_all_m', 'Y', 1],
    ['AP', 'AP_OPEN_PERIODS', 100, 'Open Payables period', 'Manage Payables Accounting Periods', 'At least one Payables period is open.',
        "SELECT l.name AS ledger, ps.period_name, ps.closing_status FROM gl_period_statuses ps JOIN gl_ledgers l ON l.ledger_id = ps.ledger_id WHERE ps.application_id = 200 AND ps.closing_status = 'O'", 'Y', 1],
    ['AP', 'AP_INVOICES', 110, 'Invoices entered', 'Manage Invoices', 'Payables invoices exist (usage check).',
        'SELECT invoice_id, invoice_num, invoice_amount FROM ap_invoices_all', 'N', 1],

    // ── Receivables ──
    ['AR', 'AR_SYS_OPTIONS', 10, 'Receivables system options', 'Manage Receivables System Options', 'System options exist per business unit.',
        'SELECT * FROM ar_system_parameters_all', 'Y', 1],
    ['AR', 'AR_TRX_TYPES', 20, 'Transaction types', 'Manage Transaction Types', 'Invoice / credit memo transaction types are defined.',
        'SELECT cust_trx_type_id, name, type FROM ra_cust_trx_types_all', 'Y', 1],
    ['AR', 'AR_TRX_SOURCES', 30, 'Transaction sources', 'Manage Transaction Sources', 'Transaction (batch) sources are defined.',
        'SELECT batch_source_id, name FROM ra_batch_sources_all', 'Y', 1],
    ['AR', 'AR_AUTOACCOUNTING', 40, 'AutoAccounting rules', 'Manage AutoAccounting Rules', 'AutoAccounting is defined.',
        'SELECT * FROM ra_account_defaults_all', 'Y', 1],
    ['AR', 'AR_TERMS', 50, 'Receivables payment terms', 'Manage Receivables Payment Terms', 'Receivables payment terms are defined.',
        'SELECT * FROM ra_terms_b', 'Y', 1],
    ['AR', 'AR_RECEIPT_CLASSES', 60, 'Receipt classes', 'Manage Receipt Classes and Methods', 'Receipt classes are defined.',
        'SELECT receipt_class_id, name FROM ar_receipt_classes', 'Y', 1],
    ['AR', 'AR_RECEIPT_METHODS', 70, 'Receipt methods', 'Manage Receipt Classes and Methods', 'Receipt methods are defined.',
        'SELECT receipt_method_id, name FROM ar_receipt_methods', 'Y', 1],
    ['AR', 'AR_REMIT_TO', 80, 'Remit-to addresses', 'Manage Remit-to Addresses', 'Remit-to addresses are defined.',
        'SELECT * FROM ar_remit_to_locs_all', 'N', 1],
    ['AR', 'AR_CUSTOMERS', 90, 'Customer accounts', 'Manage Customers', 'Customer accounts exist.',
        'SELECT cust_account_id, account_number, account_name, status FROM hz_cust_accounts', 'Y', 1],
    ['AR', 'AR_CUSTOMER_SITES', 100, 'Customer account sites', 'Manage Customers', 'Customer account sites exist (bill-to/ship-to).',
        'SELECT * FROM hz_cust_acct_sites_all', 'Y', 1],
    ['AR', 'AR_OPEN_PERIODS', 110, 'Open Receivables period', 'Manage Receivables Accounting Periods', 'At least one Receivables period is open.',
        "SELECT l.name AS ledger, ps.period_name, ps.closing_status FROM gl_period_statuses ps JOIN gl_ledgers l ON l.ledger_id = ps.ledger_id WHERE ps.application_id = 222 AND ps.closing_status = 'O'", 'Y', 1],

    // ── Fixed Assets ──
    ['FA', 'FA_BOOKS', 10, 'Asset books', 'Manage Asset Books', 'Corporate (and tax) asset books are defined.',
        'SELECT book_type_code, book_class FROM fa_book_controls', 'Y', 1],
    ['FA', 'FA_CATEGORIES', 20, 'Asset categories', 'Manage Asset Categories', 'Asset categories are defined.',
        'SELECT * FROM fa_categories_b', 'Y', 1],
    ['FA', 'FA_METHODS', 30, 'Depreciation methods', 'Manage Depreciation Methods', 'Depreciation methods are defined.',
        'SELECT * FROM fa_methods', 'Y', 1],
    ['FA', 'FA_CALENDARS', 40, 'Asset calendars', 'Manage Asset Calendars', 'Asset calendars are defined.',
        'SELECT * FROM fa_calendar_types', 'Y', 1],
    ['FA', 'FA_LOCATIONS', 50, 'Asset locations', 'Manage Asset Locations', 'Asset locations are defined.',
        'SELECT * FROM fa_locations', 'Y', 1],
    ['FA', 'FA_OPEN_PERIODS', 60, 'Open depreciation period', 'Manage Asset Calendars', 'Each book has an open depreciation period.',
        'SELECT book_type_code, period_name, period_open_date FROM fa_deprn_periods WHERE period_close_date IS NULL', 'Y', 1],
    ['FA', 'FA_ASSETS', 70, 'Assets added', 'Manage Assets', 'Assets exist (usage check).',
        'SELECT * FROM fa_additions_b', 'N', 1],

    // ── Procurement ──
    ['PO', 'PO_BUYERS', 10, 'Procurement agents (buyers)', 'Manage Procurement Agents', 'Buyers are defined.',
        'SELECT * FROM po_agents', 'Y', 1],
    ['PO', 'PO_DOC_STYLES', 20, 'Purchasing document styles', 'Manage Purchasing Document Styles', 'Document styles are defined.',
        'SELECT * FROM po_doc_style_headers', 'N', 1],
    ['PO', 'PO_LINE_TYPES', 30, 'Purchasing line types', 'Manage Purchasing Line Types', 'Line types (goods/services) are defined.',
        'SELECT * FROM po_line_types_b', 'Y', 1],
    ['PO', 'PO_RCV_PARAMS', 40, 'Receiving parameters', 'Manage Receiving Parameters', 'Receiving parameters exist per inventory organization.',
        'SELECT * FROM rcv_parameters', 'Y', 1],
    ['PO', 'PO_REQUISITIONS', 50, 'Requisitions created', 'Manage Requisitions', 'Requisitions exist (usage check).',
        'SELECT * FROM por_requisition_headers_all', 'N', 1],
    ['PO', 'PO_ORDERS', 60, 'Purchase orders created', 'Manage Orders', 'Purchase orders exist (usage check).',
        'SELECT po_header_id, segment1 AS po_number FROM po_headers_all', 'N', 1],

    // ── Inventory ──
    ['INV', 'INV_ORGS', 10, 'Inventory organization parameters', 'Manage Inventory Organization Parameters', 'Organizations have inventory parameters.',
        'SELECT organization_id, organization_code, master_organization_id FROM inv_org_parameters', 'Y', 1],
    ['INV', 'INV_SUBINVENTORIES', 20, 'Subinventories', 'Manage Subinventories and Locators', 'Subinventories are defined.',
        'SELECT organization_id, secondary_inventory_name FROM inv_secondary_inventories', 'Y', 1],
    ['INV', 'INV_LOCATORS', 30, 'Locators', 'Manage Subinventories and Locators', 'Stock locators are defined (if locator control is used).',
        'SELECT inventory_location_id, organization_id, subinventory_code FROM inv_item_locations', 'N', 1],
    ['INV', 'INV_UOMS', 40, 'Units of measure', 'Manage Units of Measure', 'Units of measure are defined.',
        'SELECT * FROM inv_units_of_measure_b', 'Y', 1],
    ['INV', 'INV_UOM_CONVERSIONS', 50, 'UOM conversions', 'Manage Unit of Measure Conversions', 'Unit of measure conversions are defined.',
        'SELECT * FROM inv_uom_conversions', 'N', 1],
    ['INV', 'INV_TXN_TYPES', 60, 'Transaction types', 'Manage Transaction Types', 'Inventory transaction types are available.',
        'SELECT * FROM inv_transaction_types_b', 'Y', 1],
    ['INV', 'INV_ITEM_CLASSES', 70, 'Item classes', 'Manage Item Classes', 'Item classes are defined.',
        'SELECT * FROM egp_item_classes_b', 'Y', 1],
    ['INV', 'INV_CATEGORY_SETS', 80, 'Catalogs (category sets)', 'Manage Catalogs', 'Item catalogs / category sets are defined.',
        'SELECT * FROM egp_category_sets_b', 'N', 1],
    ['INV', 'INV_ITEMS', 90, 'Items', 'Manage Items', 'Items exist in the item master.',
        'SELECT inventory_item_id, item_number, organization_id FROM egp_system_items_b', 'Y', 1],

    // ── Shipping ──
    ['SHIP', 'SHIP_CARRIERS', 10, 'Carriers', 'Manage Carriers', 'Carriers are defined.',
        'SELECT * FROM wsh_carriers', 'Y', 1],
    ['SHIP', 'SHIP_CARRIER_SERVICES', 20, 'Carrier ship methods', 'Manage Carriers', 'Carrier services / ship methods are defined.',
        'SELECT * FROM wsh_carrier_services', 'Y', 1],
    ['SHIP', 'SHIP_PICK_RULES', 30, 'Pick release rules', 'Manage Release Rules', 'Pick release rules are defined.',
        'SELECT * FROM wsh_picking_rules', 'N', 1],

    // ── Order Management ──
    ['OM', 'OM_ORDER_TYPES', 10, 'Order types', 'Manage Order Lookups', 'Order types (lookup ORA_DOO_ORDER_TYPES) are defined.',
        "SELECT lookup_code, enabled_flag FROM fnd_lookup_values_b WHERE lookup_type = 'ORA_DOO_ORDER_TYPES'", 'Y', 1],
    ['OM', 'OM_PRICE_LISTS', 20, 'Price lists', 'Manage Price Lists', 'Price lists are defined.',
        'SELECT * FROM qp_price_lists_b', 'Y', 1],
    ['OM', 'OM_SALESPERSONS', 30, 'Salespersons', 'Manage Salespersons', 'Salespersons are defined.',
        'SELECT * FROM jtf_rs_salesreps', 'N', 1],
    ['OM', 'OM_ORDERS', 40, 'Sales orders created', 'Manage Orders', 'Sales orders exist (usage check).',
        'SELECT header_id, order_number, status_code FROM doo_headers_all', 'N', 1],
    ['OM', 'OM_FULFILL_LINES', 50, 'Fulfillment lines', 'Manage Orders', 'Orders have fulfillment lines (usage check).',
        'SELECT * FROM doo_fulfill_lines_all', 'N', 1],

    // ── Users & Security ──
    ['SEC', 'SEC_USERS', 10, 'Users', 'Manage Users', 'Application users exist.',
        "SELECT user_id, username, active_flag FROM per_users WHERE active_flag = 'Y'", 'Y', 1],
    ['SEC', 'SEC_USER_ROLES', 20, 'Role provisioning', 'Manage Users', 'Users have roles provisioned.',
        'SELECT * FROM per_user_roles', 'Y', 1],
    ['SEC', 'SEC_ROLES', 30, 'Roles', 'Manage Job Roles', 'Roles are available.',
        'SELECT * FROM per_roles_dn', 'Y', 1],

    // ── HCM Core ──
    ['HCM', 'HCM_PERSONS', 10, 'Persons (workers)', 'Hire an Employee', 'Person records exist.',
        'SELECT person_id, person_number FROM per_all_people_f WHERE SYSDATE BETWEEN effective_start_date AND effective_end_date', 'Y', 1],
    ['HCM', 'HCM_ASSIGNMENTS', 20, 'Assignments', 'Hire an Employee', 'Worker assignments exist.',
        'SELECT * FROM per_all_assignments_m WHERE SYSDATE BETWEEN effective_start_date AND effective_end_date', 'Y', 1],
    ['HCM', 'HCM_JOBS', 30, 'Jobs', 'Manage Jobs', 'Jobs are defined.',
        'SELECT * FROM per_jobs_f', 'N', 1],
    ['HCM', 'HCM_DEPARTMENTS', 40, 'Departments / organizations', 'Manage Departments', 'HR organizations are defined.',
        'SELECT * FROM hr_all_organization_units_f', 'Y', 1]
];
