-- ============================================================
-- WMS ORDER CREATION - NEWORDER CONTRACT (reference)
-- ============================================================
-- The NEWORDER handler ALREADY EXISTS in APEX:
--   POST /ords/WKSP_GRAYSAPP/ORDERCRATION/NEWORDER
-- This file documents the JSON contract it expects, as used by
-- the AI chat's order.create form (aianalysis/api-catalog.js
-- buildBody wraps the reviewed form values into this shape).
--
-- Top level: { "OrderHeader": [ { ...header..., "Paymentdetails": [...], "lines": [...] } ] }
--
-- Header keys (sample values):
--   cartid: 2260000006                       ACCOUNT_NAME, agent_name, location
--   BILL_TO_CUSTOMER_NUMBER: "GR132044"      PO_NUMBER, ORDER_DATE: "2024-05-17T00:00:00"
--   BUSINESS_UNIT_IDENTIFIER: "300000003234003"
--   ORDER_TYPE: "PDA-DD-CASH"                FREEZEPRICE/FREEZETAX: "YES"
--   P_USERNAME, LOGIN_ID, LOGIN_NAME         SITE_USE_ID, PARTY_SITE_ID, PARTY_ID, CUST_ACCOUNT_ID
--   REQUESTINGLEGALUNIT: "GRAYS INC"         SALESREP_NUMBER, CURRENCY_CODE: "MUR"
--   PAYMENT_TERMS: "PAYMENT_TERM"            HOLD_STATUS: "Completed"
--   WAREHOUSE: "SHOPS", SUB_INVENTORY        PRICELIST: "PUBLIC"
--   FUSION_INTERFACE_ST: "NO", CONFIRM_ORDER_ST: "NO"
--   TOTAL_TAX / TOTAL_DISCOUNT / TOTAL_NET / TOTAL_GROSS
--   ORDER_STATUS: "CONFIRM"                  offline_order_number, OrderTime: "19:43:27"
--   ... plus nullable POS fields (returns, delivery, shop, approval).
--
-- Paymentdetails[] (POS payments; empty [] for chat-created B2B orders):
--   { PaymentMode: "CASH", AMOUNT_Pay, TOTAL_AMOUNT, SOURCE_ORDER_NUMBER,
--     CUSTOMER_NAME, ORDER_DATE: "17/05/2024", LOGIN_ID, LOCATION_NAME }
--
-- lines[] keys (sample values):
--   LINE_NUM: "1", CURRECY_CODE: "MUR" (sic), LIST_PRICE, SELLING_PRICE,
--   TAX_AMOUNT, NET, WAREHOUSE, SUBINVENTORY, ITEM_CODE, ITEM_DESC,
--   TAX_CODE: "GROT1.4", UOM_CODE: "UN", LOT_NUMBER, LOT_EXPIRY,
--   ORIGINALITEM, IsBogoItem, INVENTORY_ITEM_ID, BARCODE,
--   TOTAL_TAX / TOTAL_NET / TOTAL_GROSS, QTY, LINE_TYPE: "ORD",
--   ORDER_DATE, LOGIN_ID/LOGIN_NAME, parent_line_num, IsDeleted ...
--
-- Note the misspelled keys are part of the contract and must be kept:
--   CURRECY_CODE, MEMEBERSHIP_ID, PALYER_ID, RetunAmount, SHIPIING_COMMENT
-- ============================================================
