-- ============================================================================
-- 73_ai_dll_maps.sql - DLL Explorer feature maps
-- ----------------------------------------------------------------------------
-- DLL Explorer (dllexplorer/index.html) reads a .dll/.exe on the user's PC
-- (classes/DllInspector.cs - parsed and decompiled, never run) and "Explain
-- with AI" (classes/DllAnalystAgent.cs) writes a feature map in Markdown.
-- "Save to APEX" stores it here, one row per file version (SHA-256), so the
-- AI Digital Employee can answer "what does X.dll do?" from the saved map
-- (SELECT ... FROM wms_ai_dll_maps) before reading the DLL again.
-- The page creates the table itself through ai/executewrite when it is
-- missing; this script is the reference copy.
-- ============================================================================

CREATE TABLE wms_ai_dll_maps (
    map_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name      VARCHAR2(260)  NOT NULL,
    file_path      VARCHAR2(1000),
    sha256         VARCHAR2(64)   NOT NULL,
    file_version   VARCHAR2(100),
    kind           VARCHAR2(20),          -- managed | mixed | native
    machine        VARCHAR2(40),
    company        VARCHAR2(300),
    description    VARCHAR2(1000),
    summary        VARCHAR2(4000),        -- the "Summary" section of the map
    capabilities   VARCHAR2(4000),        -- comma list: Web / HTTP calls, Database, Printing ...
    feature_map    CLOB,                  -- full Markdown feature map
    focus          VARCHAR2(1000),        -- what the user asked Claude to focus on
    created_by     VARCHAR2(100),
    created_date   DATE DEFAULT SYSDATE,
    updated_by     VARCHAR2(100),
    updated_date   DATE DEFAULT SYSDATE,
    CONSTRAINT wms_ai_dll_maps_uk UNIQUE (sha256)
);

CREATE INDEX wms_ai_dll_maps_n1 ON wms_ai_dll_maps (UPPER(file_name));

-- Examples
-- SELECT file_name, file_version, summary FROM wms_ai_dll_maps ORDER BY updated_date DESC;
-- SELECT TO_CHAR(SUBSTR(feature_map, 1, 3900)) FROM wms_ai_dll_maps WHERE UPPER(file_name) = 'GRAYSWMS.DLL';
