-- ============================================================================
-- 75_ai_control.sql - AI Digital Employee: control, audit, inbox, saved chats
-- ----------------------------------------------------------------------------
-- The app creates these tables itself on first use (classes/AiControl.cs
-- EnsureTablesAsync, through ai/executewrite) - this script is the reference
-- copy. Run section 5 (DB-lane kill switch) by hand: it replaces the job
-- runner and cannot go through the write gateway.
--
--   WMS_AI_CONTROL        key/value switches: AI_ENABLED (kill switch), who may
--                         resume / approve, inbox alert targets, model prices
--   WMS_AI_AUDIT          one trail for everything the AI does or is asked to
--                         do: chat actions, approvals, jobs, agents, cost
--   WMS_AI_INBOX          approval requests that wait for a person (e.g. the
--                         Shipping Agent's line cancellations) - decided from
--                         any PC in AI Digital Employee > Control
--   WMS_AI_CONVERSATIONS  chats saved centrally (per app user), so they
--                         follow the user to another PC
-- ============================================================================

-- 1. Control ------------------------------------------------------------------
CREATE TABLE wms_ai_control (
    control_key    VARCHAR2(60) PRIMARY KEY,
    control_value  VARCHAR2(4000),
    updated_by     VARCHAR2(100),
    updated_date   DATE DEFAULT SYSDATE
);
-- AI_ENABLED          Y / N   - N pauses every AI action that changes or sends something
-- PAUSE_REASON        text shown while paused
-- ADMINS              comma list of app logins that may resume the AI, edit policies and
--                     these settings (empty = anyone, until you set it)
-- APPROVERS           comma list of app logins that may decide inbox requests (empty = anyone)
-- INBOX_TEAMS_WEBHOOK Teams incoming-webhook URL for new inbox requests (optional)
-- INBOX_EMAIL_TO      e-mail addresses for new inbox requests, ; separated (optional)
-- MODEL_PRICES        JSON {"model":{"in":USD per 1M input tokens,"out":USD per 1M output}}
--                     overrides the built-in list used for API-mode cost
INSERT INTO wms_ai_control (control_key, control_value, updated_by) VALUES ('AI_ENABLED', 'Y', 'SCRIPT75');

-- 2. Audit --------------------------------------------------------------------
CREATE TABLE wms_ai_audit (
    audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time   DATE DEFAULT SYSDATE,
    app_user     VARCHAR2(100),
    machine      VARCHAR2(100),
    source       VARCHAR2(30),      -- CHAT, DECISION, JOB, TASK, SHIPPING_AGENT, INBOX, CONTROL
    action_key   VARCHAR2(60),      -- fusion_write, db_write, email, mra_interface, cancel_lines, turn ...
    outcome      VARCHAR2(20),      -- OK, FAILED, ASKED, APPROVED, REJECTED, DENIED, BLOCKED, PAUSED
    approval     VARCHAR2(20),      -- NONE, CARD, AUTO, INBOX
    instance     VARCHAR2(10),
    ref_id       VARCHAR2(200),     -- chat session / trip / job / inbox id
    target       VARCHAR2(400),     -- path, table, order numbers ...
    detail       VARCHAR2(4000),
    model        VARCHAR2(60),
    tokens_in    NUMBER,
    tokens_out   NUMBER,
    cache_read   NUMBER,
    cache_write  NUMBER,
    cost_usd     NUMBER(14,6),
    duration_ms  NUMBER
);
CREATE INDEX wms_ai_audit_n1 ON wms_ai_audit (event_time);
CREATE INDEX wms_ai_audit_n2 ON wms_ai_audit (app_user, event_time);

-- 3. Inbox --------------------------------------------------------------------
CREATE TABLE wms_ai_inbox (
    inbox_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date    DATE DEFAULT SYSDATE,
    source          VARCHAR2(30),
    requested_by    VARCHAR2(100),
    machine         VARCHAR2(100),
    action_key      VARCHAR2(60),
    instance        VARCHAR2(10),
    ref_id          VARCHAR2(200),
    sig             VARCHAR2(200),     -- fingerprint of exactly what is asked (dedupe)
    title           VARCHAR2(400),
    summary         VARCHAR2(4000),
    payload_json    CLOB,
    status          VARCHAR2(20) DEFAULT 'PENDING',   -- PENDING, APPROVED, REJECTED, DONE, FAILED, EXPIRED, CANCELLED
    decided_by      VARCHAR2(100),
    decided_date    DATE,
    decision_note   VARCHAR2(1000),
    result_text     VARCHAR2(4000),
    expires_date    DATE
);
CREATE INDEX wms_ai_inbox_n1 ON wms_ai_inbox (status, created_date);

-- 4. Conversations ------------------------------------------------------------
CREATE TABLE wms_ai_conversations (
    chat_id        VARCHAR2(60) PRIMARY KEY,
    app_user       VARCHAR2(100),
    machine        VARCHAR2(100),
    title          VARCHAR2(400),
    message_count  NUMBER,
    messages_json  CLOB,
    created_date   DATE DEFAULT SYSDATE,
    updated_date   DATE DEFAULT SYSDATE,
    deleted        VARCHAR2(1) DEFAULT 'N'
);
CREATE INDEX wms_ai_conversations_n1 ON wms_ai_conversations (app_user, updated_date);

COMMIT;

-- 5. DB-lane kill switch (run by hand) ------------------------------------------
-- Scheduled DB-lane jobs run inside Oracle, so they check the switch themselves:
-- a paused AI records a PAUSED run and does nothing. Re-run 38_ai_jobs.sql
-- section 4 (wms_ai_job_runner) - it now starts with this check:
--
--     IF wms_ai_is_enabled = 'N' THEN RETURN; END IF;   -- no run row, no count
--
CREATE OR REPLACE FUNCTION wms_ai_is_enabled RETURN VARCHAR2 IS
    v VARCHAR2(10);
BEGIN
    -- dynamic, so this compiles before WMS_AI_CONTROL exists (75_ai_control.sql / created by the app)
    EXECUTE IMMEDIATE 'SELECT NVL(UPPER(MAX(control_value)), ''Y'') FROM wms_ai_control WHERE control_key = ''AI_ENABLED''' INTO v;
    RETURN CASE WHEN v = 'N' THEN 'N' ELSE 'Y' END;
EXCEPTION
    WHEN OTHERS THEN RETURN 'Y';   -- no control table yet = enabled (same as before)
END wms_ai_is_enabled;
/
