-- ============================================================================
-- 76_powerbi.sql - Power BI module (powerbi/ page, classes/PowerBiService.cs)
-- ----------------------------------------------------------------------------
-- The app creates these tables itself on first use (PowerBiService.EnsureTablesAsync,
-- through ai/executewrite) - this script is the reference copy.
--
--   WMS_PBI_DATASETS     dataset definitions: tables (APEX SQL + typed columns + DAX
--                        measures), relationships, schedule, and the Power BI ids once
--                        published. The app creates a PUSH dataset in the workspace and
--                        refreshes it by reading the SQL and posting the rows.
--   WMS_PBI_REFRESH_LOG  one row per refresh (who / which PC, rows per table, errors)
--
-- Shared settings live in WMS_AI_CONTROL (AI Digital Employee > Control):
--   PBI_TENANT_ID, PBI_CLIENT_ID  Entra ID app registration (public client, http://localhost)
--   PBI_WORKSPACE_ID              the Power BI workspace (group) the app works in
--   PBI_MODE                      USER (each user signs in - Pro licences) or APP (service
--                                 principal - Premium / Embedded / Fabric capacity)
-- The APP-mode client secret and the users' sign-in tokens stay on each PC (DPAPI).
-- ============================================================================

CREATE TABLE wms_pbi_datasets (
    dataset_key       VARCHAR2(60) PRIMARY KEY,
    name              VARCHAR2(200) NOT NULL,
    definition_json   CLOB,
    workspace_id      VARCHAR2(60),
    pbi_dataset_id    VARCHAR2(60),
    schema_hash       VARCHAR2(64),        -- tables/columns/measures last published
    rel_hash          VARCHAR2(64),        -- relationships last published (change = recreate)
    schedule_mode     VARCHAR2(20) DEFAULT 'MANUAL',   -- MANUAL, DAILY, HOURLY
    schedule_time     VARCHAR2(5),         -- HH24:MI for DAILY
    last_refresh      DATE,
    last_status       VARCHAR2(20),        -- OK, FAILED, RUNNING
    last_rows         NUMBER,
    last_error        VARCHAR2(4000),
    lock_by           VARCHAR2(100),       -- PC running a refresh (scheduled refresh lease)
    lock_at           DATE,
    created_by        VARCHAR2(100),
    created_date      DATE DEFAULT SYSDATE,
    updated_by        VARCHAR2(100),
    updated_date      DATE DEFAULT SYSDATE
);

CREATE TABLE wms_pbi_refresh_log (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_key   VARCHAR2(60),
    started_at    DATE DEFAULT SYSDATE,
    finished_at   DATE,
    run_by        VARCHAR2(100),
    machine       VARCHAR2(100),
    trigger_type  VARCHAR2(20),            -- MANUAL, SCHEDULE
    status        VARCHAR2(20),
    total_rows    NUMBER,
    detail        VARCHAR2(4000),          -- rows per table
    error_text    VARCHAR2(4000)
);
CREATE INDEX wms_pbi_refresh_log_n1 ON wms_pbi_refresh_log (dataset_key, started_at);

COMMIT;
