-- ============================================================================
-- 77_powerbi_feed.sql - Power BI without an app registration (powerbi/ page)
-- ----------------------------------------------------------------------------
-- Power BI Desktop (and the Power BI service's scheduled refresh) reads the tables
-- of a dataset defined in the app (WMS_PBI_DATASETS, Datasets tab) straight from
-- APEX through one GET endpoint:
--
--   GET https://<host>/ords/WKSP_GRAYSAPP/WAREHOUSEMANAGEMENT/pbi/feed
--         ?ds=wms_operations&t=TripOrders&skip=0&take=20000&k=<feed key>
--
--   -> { "dataset": "...", "table": "...", "skip": 0, "take": 20000, "items": [ {...}, ... ] }
--      (null values are left out of each item; the Power Query code the app generates
--       fills them back in)
--
-- Feed keys are made in the app (Setup > Power BI Desktop connection). Only their
-- SHA-256 is stored here; Power BI keeps the key itself as a "Web API" credential.
-- A key can be limited to one dataset and revoked at any time.
--
-- RUN ONCE in SQL Workshop > SQL Scripts (as the WKSP_GRAYSAPP schema owner).
-- The two tables are also created by the app on first use; the procedure and the
-- ORDS handler need this script.
-- ============================================================================

-- 1. Tables ------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE wms_pbi_feed_keys (
        key_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name          VARCHAR2(200) NOT NULL,       -- who / what uses it, e.g. "Javeed - Power BI Desktop"
        key_hash      VARCHAR2(64)  NOT NULL,       -- RAWTOHEX(STANDARD_HASH(key, ''SHA256''))
        key_hint      VARCHAR2(20),                 -- first characters, to recognise it
        dataset_key   VARCHAR2(60),                 -- NULL = every dataset
        revoked       VARCHAR2(1) DEFAULT ''N'',
        created_by    VARCHAR2(100),
        created_date  DATE DEFAULT SYSDATE,
        last_used     DATE,
        use_count     NUMBER DEFAULT 0)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX wms_pbi_feed_keys_u1 ON wms_pbi_feed_keys (key_hash)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE wms_pbi_links (
        link_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name           VARCHAR2(200) NOT NULL,
        url            VARCHAR2(4000) NOT NULL,     -- normalised secure-embed URL (app.powerbi.com/reportEmbed?...)
        source_url     VARCHAR2(4000),              -- what the user pasted
        description    VARCHAR2(1000),
        folder         VARCHAR2(100),
        filters_json   VARCHAR2(4000),              -- default WMS filters [{table,column,value,numeric}]
        is_public      VARCHAR2(1) DEFAULT ''N'',   -- Publish-to-web link (anyone with the link)
        sort_order     NUMBER DEFAULT 100,
        created_by     VARCHAR2(100),
        created_date   DATE DEFAULT SYSDATE,
        updated_by     VARCHAR2(100),
        updated_date   DATE DEFAULT SYSDATE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. Feed procedure ----------------------------------------------------------
CREATE OR REPLACE PROCEDURE wms_pbi_feed (
    p_ds    IN VARCHAR2,
    p_table IN VARCHAR2,
    p_key   IN VARCHAR2,
    p_skip  IN VARCHAR2 DEFAULT '0',
    p_take  IN VARCHAR2 DEFAULT '20000'
) IS
    v_hash    VARCHAR2(64);
    v_key_id  NUMBER;
    v_scope   VARCHAR2(60);
    v_sql     CLOB;
    v_head    VARCHAR2(20);
    v_skip    PLS_INTEGER;
    v_take    PLS_INTEGER;
    v_cur     SYS_REFCURSOR;

    FUNCTION num (p_val VARCHAR2, p_default PLS_INTEGER) RETURN PLS_INTEGER IS
    BEGIN
        RETURN NVL(TO_NUMBER(p_val), p_default);
    EXCEPTION WHEN VALUE_ERROR THEN RETURN p_default;
    END;

    PROCEDURE fail (p_status PLS_INTEGER, p_msg VARCHAR2) IS
    BEGIN
        owa_util.status_line(p_status, NULL, FALSE);
        owa_util.mime_header('application/json', TRUE, 'UTF-8');
        htp.p('{"error":"' || REPLACE(REPLACE(p_msg, '\', '\\'), '"', '\"') || '"}');
    END;
BEGIN
    -- key --------------------------------------------------------------------
    IF p_key IS NULL OR LENGTH(p_key) < 20 THEN
        fail(401, 'Feed key missing - in Power BI use the "Web API" credential with the key from the app');
        RETURN;
    END IF;
    SELECT RAWTOHEX(STANDARD_HASH(p_key, 'SHA256')) INTO v_hash FROM dual;
    BEGIN
        SELECT key_id, dataset_key INTO v_key_id, v_scope
          FROM wms_pbi_feed_keys
         WHERE key_hash = v_hash AND NVL(revoked, 'N') = 'N';
    EXCEPTION WHEN NO_DATA_FOUND THEN
        fail(401, 'Unknown or revoked feed key');
        RETURN;
    END;
    IF v_scope IS NOT NULL AND v_scope != p_ds THEN
        fail(403, 'This key is limited to dataset ' || v_scope);
        RETURN;
    END IF;

    -- table SQL from the dataset definition ------------------------------------
    BEGIN
        SELECT jt.sql_text INTO v_sql
          FROM wms_pbi_datasets d,
               JSON_TABLE(d.definition_json, '$.tables[*]'
                   COLUMNS (tname VARCHAR2(200) PATH '$.name',
                            sql_text CLOB PATH '$.sql')) jt
         WHERE d.dataset_key = p_ds
           AND jt.tname = p_table
           AND ROWNUM = 1;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        fail(404, 'No table ' || p_table || ' in dataset ' || p_ds);
        RETURN;
    END;

    -- read-only: one SELECT / WITH statement
    v_sql  := RTRIM(TRIM(v_sql), ';' || CHR(10) || CHR(13) || ' ');
    v_head := UPPER(SUBSTR(LTRIM(v_sql, ' (' || CHR(10) || CHR(13) || CHR(9)), 1, 6));
    IF NOT (v_head LIKE 'SELECT%' OR v_head LIKE 'WITH%') OR INSTR(v_sql, ';') > 0 THEN
        fail(400, 'The table SQL must be a single SELECT statement');
        RETURN;
    END IF;

    v_skip := GREATEST(num(p_skip, 0), 0);
    v_take := LEAST(GREATEST(num(p_take, 20000), 1), 50000);

    UPDATE wms_pbi_feed_keys SET last_used = SYSDATE, use_count = NVL(use_count, 0) + 1 WHERE key_id = v_key_id;
    COMMIT;

    OPEN v_cur FOR 'SELECT * FROM (' || v_sql || ') OFFSET :s ROWS FETCH NEXT :n ROWS ONLY' USING v_skip, v_take;

    owa_util.mime_header('application/json', TRUE, 'UTF-8');
    apex_json.open_object;
    apex_json.write('dataset', p_ds);
    apex_json.write('table', p_table);
    apex_json.write('skip', v_skip);
    apex_json.write('take', v_take);
    apex_json.write('items', v_cur);
    apex_json.close_object;
EXCEPTION
    WHEN OTHERS THEN
        IF v_cur%ISOPEN THEN CLOSE v_cur; END IF;
        fail(500, SUBSTR(SQLERRM, 1, 500));
END wms_pbi_feed;
/

-- 3. ORDS endpoint (same module as ai/executequery - found by its URI prefix) ---
DECLARE
    v_module VARCHAR2(200);
BEGIN
    SELECT name INTO v_module
      FROM user_ords_modules
     WHERE UPPER(uri_prefix) LIKE '%WAREHOUSEMANAGEMENT%'
       AND ROWNUM = 1;
    ORDS.DEFINE_TEMPLATE(
        p_module_name => v_module,
        p_pattern     => 'pbi/feed');
    ORDS.DEFINE_HANDLER(
        p_module_name => v_module,
        p_pattern     => 'pbi/feed',
        p_method      => 'GET',
        p_source_type => ORDS.source_type_plsql,
        p_source      => 'BEGIN wms_pbi_feed(:ds, :t, :k, :skip, :take); END;');
    COMMIT;
END;
/

-- 4. Check ---------------------------------------------------------------------
-- SELECT line, position, text FROM user_errors WHERE name = 'WMS_PBI_FEED' ORDER BY sequence;
-- Then in the app: Power BI > Setup > Power BI Desktop connection > Test the feed.
