-- ============================================================
-- WMS 2.0 (wms2/) — shared settings, the autopilot lease and the cancellation ledger
-- ============================================================
-- The WMS 2.0 page creates these tables itself on first use (through ai/executewrite); this script is the same DDL
-- for running by hand. Nothing in the existing WMS tables or ORDS handlers changes.
--
--   WMS_W2_SETTINGS    AUTOPILOT_PROD / AUTOPILOT_TEST = ON | OFF, AUTOPILOT_<POD>_REASON, AUTOPILOT_OPTIONS (JSON:
--                      every n minutes, trips of today / tomorrow, max lines per run) — shared by every PC
--   WMS_W2_LEASE       AUTOPILOT_<POD>: the PC that may cancel right now (10-minute lease, renewed per order)
--   WMS_W2_CANCEL_LOG  every line the autopilot cancelled (DONE), could not cancel (FAILED) or left (SKIPPED),
--                      plus one RUN row per run; read by every PC (last 3 days) into its DuckDB copy
-- ============================================================

CREATE TABLE wms_w2_settings (
    setting_key    VARCHAR2(80) PRIMARY KEY,
    setting_value  VARCHAR2(4000),
    changed_by     VARCHAR2(200),
    changed_date   DATE DEFAULT SYSDATE
);

CREATE TABLE wms_w2_lease (
    lease_name   VARCHAR2(80) PRIMARY KEY,
    holder       VARCHAR2(200),
    lease_until  DATE
);

CREATE TABLE wms_w2_cancel_log (
    log_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           VARCHAR2(40),
    logged_at        DATE DEFAULT SYSDATE,
    pod              VARCHAR2(10),
    pc_name          VARCHAR2(60),
    app_user         VARCHAR2(200),
    trip_date        VARCHAR2(10),
    trip_id          VARCHAR2(60),
    order_number     VARCHAR2(60),
    line_number      VARCHAR2(30),
    item             VARCHAR2(200),
    status_before    VARCHAR2(200),
    fulfill_line_id  VARCHAR2(60),
    via              VARCHAR2(20),      -- MAIN | SUB-LINE | BOGO
    result           VARCHAR2(20),      -- DONE | FAILED | SKIPPED | NOTHING | RUN
    message          VARCHAR2(1000),
    response         VARCHAR2(2000)
);

CREATE INDEX wms_w2_cancel_log_i1 ON wms_w2_cancel_log (pod, logged_at);
CREATE INDEX wms_w2_cancel_log_i2 ON wms_w2_cancel_log (order_number);
