-- ============================================================================
-- 90_mra_interface_status.sql
-- WMS_MRA_INTERFACE_STATUS — one row for every MRA interface run, from every place that runs it:
--   WMS MRA button (WMS_MANUAL), Trip Print / SO Trip Print batch (WMS_AUTO_INV / WMS_AUTO_SO), Shipping Agent Print Trip
--   (SHIPPING_AGENT), WMS 2.0 (WMS2), WMS › MRA Interface › MRA transactions history retry (WMS_MRA_HISTORY), AI Digital Employee chat (AI_EMPLOYEE), AI Agent (AI_AGENT), Order Management (ORDER_MGMT).
-- Written by the app (classes/MRAInterfaceStatus.cs, called from MRAProcessor.ProcessMRAInterfaceAsync) through ai/executewrite.
-- The app also creates the table on first use; run this script to create it up front or to re-create it.
--
-- mra_interface_status: SUCCESS (IRN received and stored on the Fusion order) / FAILED (failed_step + failed_reason,
--   mra_response_json = MRA's actual answer) / SKIPPED (order type not interfaced, MRA_ORDER_TYPES) / ALREADY_DONE (MRA had it).
-- trip_id: from the screen when it knows the trip, else looked up in WMS_TRIP_DETAILS (latest trip, never 9999).
-- ============================================================================

-- Step 1 (optional): drop it to start again — the history is lost.
-- DROP TABLE wms_mra_interface_status PURGE;

-- Step 2: create
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'WMS_MRA_INTERFACE_STATUS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE wms_mra_interface_status (
        id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_date          DATE DEFAULT SYSDATE,      -- when the row was written (end of the run)
        started_at            DATE,                      -- when the run started (PC time)
        instance_name         VARCHAR2(20),              -- PROD / TEST
        trip_id               VARCHAR2(50),
        order_number          VARCHAR2(60),
        header_id             VARCHAR2(40),              -- Fusion order header id
        order_type            VARCHAR2(100),
        order_date            DATE,
        customer_number       VARCHAR2(60),
        customer_name         VARCHAR2(400),
        customer_brn          VARCHAR2(60),
        customer_vat          VARCHAR2(60),
        mra_customer_cat      VARCHAR2(60),
        currency              VARCHAR2(10),
        order_amount          NUMBER,
        tax_amount            NUMBER,
        discount_amount       NUMBER,
        line_count            NUMBER,
        invoice_type          VARCHAR2(10),              -- STD / CRN (credit note) / PRF (pro-forma)
        mra_interface_id      VARCHAR2(200),             -- the IRN MRA returned
        mra_interface_status  VARCHAR2(20),              -- SUCCESS / FAILED / SKIPPED / ALREADY_DONE
        failed_step           VARCHAR2(40),              -- FetchingOrderSummary, ValidatingOrderLines, CreatingMRAInvoice, UpdatingFusionOrder …
        failed_reason         VARCHAR2(4000),
        gateway_problem       VARCHAR2(20),              -- TIMEOUT (sent, no answer) / UNREACHABLE (nothing sent)
        http_status           NUMBER,                    -- HTTP status of the MRA gateway
        fusion_updated        VARCHAR2(1),               -- Y = IRN written to the Fusion order
        source                VARCHAR2(30),              -- which screen / agent ran it
        batch_id              VARCHAR2(100),             -- one id per Print Trip click / batch
        app_user              VARCHAR2(100),
        machine               VARCHAR2(100),
        duration_ms           NUMBER,
        timings               VARCHAR2(1000),            -- seconds per step
        order_header_json     CLOB,                      -- the order summary row as Fusion returned it
        mra_request_json      CLOB,                      -- the invoice JSON sent to MRA
        mra_response_json     CLOB                       -- MRA's actual answer (kept for failures and successes)
      )]';
    EXECUTE IMMEDIATE 'CREATE INDEX wms_mra_if_status_n1 ON wms_mra_interface_status (order_number, created_date)';
    EXECUTE IMMEDIATE 'CREATE INDEX wms_mra_if_status_n2 ON wms_mra_interface_status (trip_id, instance_name)';
    EXECUTE IMMEDIATE 'CREATE INDEX wms_mra_if_status_n3 ON wms_mra_interface_status (created_date, mra_interface_status)';
  END IF;
END;
/

-- Useful queries ---------------------------------------------------------------

-- Latest state of every order (an order can have several tries)
SELECT * FROM (
  SELECT s.order_number, s.trip_id, s.instance_name, s.customer_name, s.order_amount, s.mra_interface_status,
         s.mra_interface_id, s.failed_step, s.failed_reason, s.source, s.app_user, s.created_date,
         ROW_NUMBER() OVER (PARTITION BY s.instance_name, s.order_number ORDER BY s.created_date DESC, s.id DESC) rn
  FROM wms_mra_interface_status s)
WHERE rn = 1
ORDER BY created_date DESC;

-- Failures today with MRA's answer
SELECT order_number, trip_id, failed_step, failed_reason, http_status, gateway_problem,
       TO_CHAR(SUBSTR(mra_response_json, 1, 3900)) AS mra_answer
FROM wms_mra_interface_status
WHERE mra_interface_status = 'FAILED' AND created_date >= TRUNC(SYSDATE)
ORDER BY created_date DESC;

-- Per day × source
SELECT TRUNC(created_date) AS day, source, mra_interface_status, COUNT(*) AS runs, SUM(order_amount) AS amount
FROM wms_mra_interface_status
GROUP BY TRUNC(created_date), source, mra_interface_status
ORDER BY 1 DESC, 2, 3;
