-- ============================================================================
-- 91_gettripdetails_mra_picker.sql
-- Trip Details API  GET WAREHOUSEMANAGEMENT/GETTRIPDETAILS/:TRIP_ID?P_INSTANCE_NAME=
-- (the call behind the WMS Trip Details grid, the Future Trip tab and WMS 2.0's trip tabs) gets six more fields:
--   mra_status          latest WMS_MRA_INTERFACE_STATUS.mra_interface_status of the order (SUCCESS / FAILED / SKIPPED / ALREADY_DONE)
--   mra_irn             its IRN (mra_interface_id)
--   mra_reason          failed_reason of that try (first 300 characters)
--   mra_at              when that try was written (DD-MM-YYYY HH24:MI)
--   mra_tries           how many tries the order has
--   picker_assigned_on  MAX(WMS_PICKER_ASSIGNMENT.picker_assignment_date) of the order (DD-MM-YYYY HH24:MI)
--
-- The handler query below is the current one with two changes, marked -- [91]:
--   * picker_data also returns MAX(picker_assignment_date)
--   * a new CTE mra_data (latest try per order of this trip, same instance) + LEFT JOIN
-- mra_status is the FIRST column (the grid shows it right after Actions) and picker_assigned_on comes right after
-- the picker. The page places both columns itself anyway, and reads them through the gateway while the handler
-- does not send them — so the app works before and after this script.
--
-- Needs: 90_mra_interface_status.sql (WMS_MRA_INTERFACE_STATUS). Run as the schema that owns the ORDS module.
-- Step 1 shows what runs today, step 3 saves it in WMS_ORDS_HANDLER_BACKUP before ORDS.DEFINE_HANDLER;
-- ROLLBACK at the end puts the saved source back.
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED

-- 1) What runs today (look before you change)
SELECT m.name AS module_name, m.uri_prefix, t.uri_template, h.method, h.source_type, h.items_per_page,
       DBMS_LOB.SUBSTR(h.source, 4000, 1) AS source_first_4000
FROM   user_ords_handlers h
JOIN   user_ords_templates t ON t.id = h.template_id
JOIN   user_ords_modules  m ON m.id = t.module_id
WHERE  UPPER(m.uri_prefix) LIKE '%WAREHOUSEMANAGEMENT%'
AND    UPPER(t.uri_template) LIKE 'GETTRIPDETAILS/:%'
AND    h.method = 'GET';

-- 2) Backup table
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'WMS_ORDS_HANDLER_BACKUP';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE wms_ords_handler_backup (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, saved_at DATE DEFAULT SYSDATE, module_name VARCHAR2(255),
      uri_template VARCHAR2(600), method VARCHAR2(10), source_type VARCHAR2(100), items_per_page NUMBER, note VARCHAR2(400), source CLOB)';
  END IF;
END;
/

-- 3) Back up the current source and define the new one
DECLARE
  l_module  user_ords_modules.name%TYPE;
  l_tpl     user_ords_templates.uri_template%TYPE;
  l_type    user_ords_handlers.source_type%TYPE;
  l_ipp     user_ords_handlers.items_per_page%TYPE;
  l_mimes   user_ords_handlers.mimes_allowed%TYPE;
  l_src     CLOB;
  l_cur     INTEGER;
  l_n       NUMBER;
  l_new     CLOB := q'~
WITH
-- Pre-aggregate data from frequently queried tables
store_txn_data AS (
    SELECT
        trx_number,
        LISTAGG(DISTINCT TRANSACTION_STATUS, ', ')
            WITHIN GROUP (ORDER BY TRANSACTION_STATUS) AS statuses,
        MAX(DECODE(TRANSACTION_STATUS,'SUCCESS','YES','NO')) as ship_confirm,
        COUNT(*) as txn_count
    FROM pos_store_transactions
    WHERE trx_number IN (SELECT ORDER_NUMBER FROM WMS_TRIP_DETAILS
                         WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    GROUP BY trx_number
),
store_lot_data AS (
    SELECT
        trx_number,
        MAX(DECODE(PICKED_STATUS,'YES','YES','NO')) as picked_status,
        COUNT(*) as total_lots,
        SUM(CASE WHEN NVL(picked_qty,0) > 0 THEN 1 ELSE 0 END) as picked_lots,
        SUM(CASE WHEN NVL(picked_qty,0) = 0 THEN 1 ELSE 0 END) as not_picked_lots
    FROM WMS_STORE_TRANSACTION_LOTS
    WHERE trim(trx_number) IN (SELECT trim(ORDER_NUMBER) FROM WMS_TRIP_DETAILS
                         WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    GROUP BY trx_number
),
order_line_data AS (
    SELECT
        SOURCE_TRANSACTION_ID,
        LISTAGG(DISTINCT status, ', ') WITHIN GROUP (ORDER BY status) AS statuses,
        COUNT(*) as line_count,
        SUM(extended_amount) as order_amount
    FROM WMS_ORDER_LINES
    WHERE SOURCE_TRANSACTION_ID IN (SELECT ORDER_NUMBER FROM WMS_TRIP_DETAILS
                                     WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
        AND RESERVED_QUANTITY > 0
       AND INSTANCE_NAME = :P_INSTANCE_NAME
    GROUP BY SOURCE_TRANSACTION_ID
),
ship_confirm_data AS (
    SELECT DISTINCT
        SOURCE_ORDER_NUMBER,
        DECODE(SHIP_CONFIRM_ST,'YES','YES','NO') as ship_confirm_st
    FROM WMS_V_SHIP_CONFIRM_ST
    WHERE TRIP_ID = :TRIP_ID  AND INSTANCE_NAME = :P_INSTANCE_NAME
 ),
pick_slip_data AS (
    SELECT
        SOURCE_ORDER_NUMBER,
        MAX(PICKSLIP) as pickslip
    FROM WMS_PICK_SLIPS
    WHERE SOURCE_ORDER_NUMBER IN (SELECT ORDER_NUMBER FROM WMS_TRIP_DETAILS
                                   WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    AND INSTANCE_NAME = :P_INSTANCE_NAME
    GROUP BY SOURCE_ORDER_NUMBER
),
lot_detail_data AS (
    SELECT
        SOURCE_ORDER,
        COUNT(*) as lot_count,
        SUM(CASE WHEN NVL(picked_qty,0) = 0 THEN 1 ELSE 0 END) as not_picked_count
    FROM WMS_PICK_SLIP_LOT_DETAILS
    WHERE trim(SOURCE_ORDER) IN (SELECT trim(ORDER_NUMBER) FROM WMS_TRIP_DETAILS
                           WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    AND INSTANCE_NAME = :P_INSTANCE_NAME
    GROUP BY SOURCE_ORDER
),
fusion_pick_data AS (
    SELECT
        SOURCE_ORDER,
        COUNT(*) as picks_count
    FROM WMS_FUSION_PICKSLIP_DETAILS
    WHERE trim(SOURCE_ORDER) IN (SELECT ORDER_NUMBER FROM WMS_TRIP_DETAILS
                           WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    AND INSTANCE_NAME = :P_INSTANCE_NAME
    GROUP BY SOURCE_ORDER
),
warehouse_data AS (
    SELECT
        SOURCE_ORDER_NUMBER,
        MAX(PRINTING_ST) as printing_st,
        COUNT(*) as cnt_w2
    FROM WMS_OPEN_PICKS_RELEASED_2_WAREHOUSE
    WHERE SOURCE_ORDER_NUMBER IN (SELECT ORDER_NUMBER FROM WMS_TRIP_DETAILS
                                   WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    GROUP BY SOURCE_ORDER_NUMBER
),
order_volume_data AS (
    SELECT DISTINCT
        SOURCE_ORDER_NUMBER,
        ROUND(PACKED_VOLUME, 2) as order_volume
    FROM wms_order_volumes
   WHERE TRIP_ID = :TRIP_ID
),
picker_data AS (
    SELECT
        trim(SOURCE_ORDER_NUMBER) SOURCE_ORDER_NUMBER ,
        MAX(picker_name) as picker_name,
        MAX(picker_assignment_date) as picker_assigned_on                              -- [91]
    FROM WMS_PICKER_ASSIGNMENT
    WHERE trim(SOURCE_ORDER_NUMBER) IN (SELECT ORDER_NUMBER FROM WMS_TRIP_DETAILS
                                   WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    AND INSTANCE = :P_INSTANCE_NAME
    GROUP BY trim(SOURCE_ORDER_NUMBER)
),
shipment_data AS (
    SELECT
        SOURCE_ORDER_NUMBER,
        MAX(ADDRESS) as address
    FROM WMS_V_PENDING_SHIPMENT_ORDERS
    WHERE SOURCE_ORDER_NUMBER IN (SELECT ORDER_NUMBER FROM WMS_TRIP_DETAILS
                                   WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    GROUP BY SOURCE_ORDER_NUMBER
),
-- [91] latest MRA interface try per order of this trip (every run is written by the app, classes/MRAInterfaceStatus.cs)
mra_data AS (
    SELECT
        order_number,
        MAX(mra_interface_status) KEEP (DENSE_RANK LAST ORDER BY created_date, id) as mra_status,
        MAX(mra_interface_id)     KEEP (DENSE_RANK LAST ORDER BY created_date, id) as mra_irn,
        MAX(SUBSTR(failed_reason, 1, 300)) KEEP (DENSE_RANK LAST ORDER BY created_date, id) as mra_reason,
        MAX(created_date) as mra_at,
        COUNT(*) as mra_tries
    FROM WMS_MRA_INTERFACE_STATUS
    WHERE order_number IN (SELECT trim(ORDER_NUMBER) FROM WMS_TRIP_DETAILS
                           WHERE TRIP_ID = :TRIP_ID AND INSTANCE_NAME = :P_INSTANCE_NAME)
    AND instance_name = UPPER(:P_INSTANCE_NAME)
    GROUP BY order_number
)
SELECT
    mra.mra_status as MRA_STATUS,                                                       -- [91] first: right after Actions
DECODE(td.order_type,
        'Store to Van', std.statuses,
        old.statuses
    ) as Line_status,

  -- Pick Confirm Status
    DECODE(td.order_type,
        'Store to Van', NVL(sld.picked_status, 'NO'),
        NVL(scd.ship_confirm_st, 'NO')
    ) as PICK_CONFIRM_ST,

    -- Ship Confirm Status
    scd.ship_confirm_st as SHIP_CONFIRM_ST,

    -- Printing Status
    wd.printing_st as PRINTING_ST,

    H.trip_date tripdate,

    td.ORDER_NUMBER,
        pd.picker_name as picker,
    TO_CHAR(pd.picker_assigned_on, 'DD-MM-YYYY HH24:MI') as PICKER_ASSIGNED_ON,         -- [91]
    -- Order Lines
    DECODE(td.order_type,
        'Store to Van', NVL(std.txn_count, 0),
        NVL(old.line_count, 0)
    ) as order_lines,

     -- Lot Count
    DECODE(td.order_type,
        'Store to Van', NVL(sld.total_lots, 0),
        NVL(ldd.lot_count, 0)
    ) as lot_count,

    -- Picks Count
    DECODE(td.order_type,
        'Store to Van', NVL(sld.picked_lots, 0),
        NVL(fpd.picks_count, 0)
    ) as picks_count,

    -- Not Picked
    DECODE(td.order_type,
        'Store to Van', NVL(sld.not_picked_lots, 0),
        NVL(ldd.not_picked_count, 0)
    ) as not_picked,

    td.ACCOUNT_NUMBER,
        td.ACCOUNT_NAME,
    H.trip_date,
    td.ORDER_DATE,
    td.ORDER_TYPE,
    td.SALESMAN,
    h.trip_lorry ,-- LORRY,
    h.TRIP_LOADING_BAY,-- LOADINGBY_NUM,
    td.PICK_RELEASE_STATUS,
    td.INSTANCE_NAME,
    to_char(ov.order_volume)  AS ORDER_VOLUME1,
     td.PRIORITY,

    -- Pick Slip Number
    DECODE(td.ORDER_TYPE,
        'Store to Van', td.ORDER_NUMBER,
        psd.pickslip
    ) as PICK_SLIP_NO,

    -- STV Pick Slip
    DECODE(td.ORDER_TYPE,
        'Store to Van', td.ORDER_NUMBER,
        ''
    ) as STV_PICK_SLIP,

    -- Address
    shd.address as ADDRESS,

       td.CUSTOMER_PO,

    -- Order Amount
    old.order_amount as order_amount,

    -- Count W2
    NVL(wd.cnt_w2, 0) as cnt_w2,
     td.TRIP_ID,
    td.TRIP_LINE_ID,
    td.TRIP_LINE_NO,
    td.RELEASE_DATE,

    -- [91] MRA details (the grid shows them on the MRA badge)
    mra.mra_irn as MRA_IRN,
    mra.mra_reason as MRA_REASON,
    TO_CHAR(mra.mra_at, 'DD-MM-YYYY HH24:MI') as MRA_AT,
    mra.mra_tries as MRA_TRIES

FROM WMS_TRIP_DETAILS td
LEFT JOIN WMS_TRIP_HEADER H ON TD.TRIP_ID = H.TRIP_ID
LEFT JOIN store_txn_data std ON std.trx_number = td.ORDER_NUMBER
LEFT JOIN store_lot_data sld ON sld.trx_number = td.ORDER_NUMBER
LEFT JOIN order_line_data old ON old.SOURCE_TRANSACTION_ID = td.ORDER_NUMBER
LEFT JOIN ship_confirm_data scd ON scd.SOURCE_ORDER_NUMBER = td.ORDER_NUMBER
LEFT JOIN pick_slip_data psd ON psd.SOURCE_ORDER_NUMBER = td.ORDER_NUMBER
LEFT JOIN lot_detail_data ldd ON ldd.SOURCE_ORDER = td.ORDER_NUMBER
LEFT JOIN fusion_pick_data fpd ON fpd.SOURCE_ORDER = td.ORDER_NUMBER
LEFT JOIN warehouse_data wd ON wd.SOURCE_ORDER_NUMBER = td.ORDER_NUMBER
LEFT JOIN order_volume_data ov ON ov.SOURCE_ORDER_NUMBER = td.ORDER_NUMBER
LEFT JOIN picker_data pd ON pd.SOURCE_ORDER_NUMBER = td.ORDER_NUMBER
LEFT JOIN shipment_data shd ON shd.SOURCE_ORDER_NUMBER = td.ORDER_NUMBER
LEFT JOIN mra_data mra ON mra.order_number = trim(td.ORDER_NUMBER)                      -- [91]
WHERE td.TRIP_ID = :TRIP_ID
 AND td.INSTANCE_NAME = :P_INSTANCE_NAME
~';
BEGIN
  SELECT COUNT(*) INTO l_n FROM user_tables WHERE table_name = 'WMS_MRA_INTERFACE_STATUS';
  IF l_n = 0 THEN
    RAISE_APPLICATION_ERROR(-20005, 'WMS_MRA_INTERFACE_STATUS does not exist yet — run 90_mra_interface_status.sql first.');
  END IF;

  SELECT m.name, t.uri_template, h.source_type, h.items_per_page, h.mimes_allowed, h.source
  INTO   l_module, l_tpl, l_type, l_ipp, l_mimes, l_src
  FROM   user_ords_handlers h
  JOIN   user_ords_templates t ON t.id = h.template_id
  JOIN   user_ords_modules  m ON m.id = t.module_id
  WHERE  UPPER(m.uri_prefix) LIKE '%WAREHOUSEMANAGEMENT%'
  AND    UPPER(t.uri_template) LIKE 'GETTRIPDETAILS/:%'
  AND    h.method = 'GET'
  AND    ROWNUM = 1;
  DBMS_OUTPUT.PUT_LINE('Handler: module ' || l_module || ' · ' || l_tpl || ' · ' || l_type);

  IF DBMS_LOB.INSTR(l_src, 'mra_data') > 0 THEN
    DBMS_OUTPUT.PUT_LINE('Already has mra_data — nothing to do.');
    RETURN;
  END IF;

  -- the new SQL must parse before the API is touched
  l_cur := DBMS_SQL.OPEN_CURSOR;
  BEGIN
    DBMS_SQL.PARSE(l_cur, l_new, DBMS_SQL.NATIVE);
    DBMS_SQL.CLOSE_CURSOR(l_cur);
  EXCEPTION WHEN OTHERS THEN
    IF DBMS_SQL.IS_OPEN(l_cur) THEN DBMS_SQL.CLOSE_CURSOR(l_cur); END IF;
    RAISE_APPLICATION_ERROR(-20006, 'The new query does not parse (API not changed): ' || SQLERRM);
  END;

  INSERT INTO wms_ords_handler_backup (module_name, uri_template, method, source_type, items_per_page, note, source)
  VALUES (l_module, l_tpl, 'GET', l_type, l_ipp, 'before 91_gettripdetails_mra_picker.sql', l_src);

  ORDS.DEFINE_HANDLER(
    p_module_name    => l_module,
    p_pattern        => l_tpl,
    p_method         => 'GET',
    p_source_type    => l_type,
    p_source         => l_new,
    p_items_per_page => l_ipp,
    p_mimes_allowed  => l_mimes,
    p_comments       => 'Trip details + MRA status + picker assigned on (91_gettripdetails_mra_picker.sql)');
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Done — the old source is saved in WMS_ORDS_HANDLER_BACKUP.');
END;
/

-- 4) Check: call the API for a trip, e.g.
--    .../ords/WKSP_GRAYSAPP/WAREHOUSEMANAGEMENT/GETTRIPDETAILS/<trip>?P_INSTANCE_NAME=PROD
--    every item now starts with "mra_status" and has "picker_assigned_on" after "picker".

-- ROLLBACK — put the saved source back (run only if needed)
/*
DECLARE
  b wms_ords_handler_backup%ROWTYPE;
BEGIN
  SELECT * INTO b FROM (SELECT * FROM wms_ords_handler_backup WHERE UPPER(uri_template) LIKE 'GETTRIPDETAILS/:%' ORDER BY id DESC) WHERE ROWNUM = 1;
  ORDS.DEFINE_HANDLER(p_module_name => b.module_name, p_pattern => b.uri_template, p_method => 'GET',
                      p_source_type => b.source_type, p_source => b.source, p_items_per_page => b.items_per_page);
  COMMIT;
END;
/
*/
