-- ============================================================================
-- 92_actual_shipdate.sql
-- WMS_ACTUAL_SHIPDATE — one row per order × shipment every time a user presses
-- Trip Details › All Shipment Lines › Update Actual Ship Date › Confirm Update.
-- The dialog posts shipmentTransactionRequests (ActionCode ShipmentUpdate) to Fusion per shipment;
-- wms/future-trip.js then writes the result here through ai/executewrite (status SUCCESS / FAILED + Fusion's error)
-- and the Trip Details grid shows the latest SUCCESS date per order in the "Actual Ship Date" column
-- (from the GETTRIPDETAILS handler once 91_gettripdetails_mra_picker.sql has run, else read by the page).
-- The page also creates the table on first use; run this to create it up front.
-- ============================================================================

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'WMS_ACTUAL_SHIPDATE';
  IF n = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE wms_actual_shipdate (
        id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_date         DATE DEFAULT SYSDATE,     -- when the user confirmed
        instance_name        VARCHAR2(20),             -- PROD / TEST
        trip_id              VARCHAR2(50),
        trip_date            DATE,
        order_number         VARCHAR2(60),
        header_id            VARCHAR2(40),             -- Fusion SourceOrderId
        order_date           DATE,
        order_type           VARCHAR2(100),
        customer_number      VARCHAR2(60),
        customer_name        VARCHAR2(400),
        shipment             VARCHAR2(40),             -- Fusion shipment number
        line_count           NUMBER,                   -- shipment lines of this order in that shipment
        actual_ship_date     DATE,                     -- the date + time the user chose
        actual_ship_date_tz  VARCHAR2(40),             -- exactly what was sent, e.g. 2026-10-06T14:30:00+04:00
        status               VARCHAR2(20),             -- SUCCESS / FAILED (Fusion's answer for that shipment)
        error_message        VARCHAR2(4000),
        app_user             VARCHAR2(120),
        source               VARCHAR2(30)              -- WMS_ASL = All Shipment Lines dialog
      )]';
    EXECUTE IMMEDIATE 'CREATE INDEX wms_actual_shipdate_n1 ON wms_actual_shipdate (order_number, created_date)';
    EXECUTE IMMEDIATE 'CREATE INDEX wms_actual_shipdate_n2 ON wms_actual_shipdate (trip_id, instance_name)';
  END IF;
END;
/

-- Latest successful actual ship date per order
SELECT order_number, instance_name,
       MAX(actual_ship_date) KEEP (DENSE_RANK LAST ORDER BY created_date, id) AS actual_ship_date,
       LISTAGG(DISTINCT shipment, ', ') WITHIN GROUP (ORDER BY shipment) AS shipments
FROM   wms_actual_shipdate
WHERE  status = 'SUCCESS'
GROUP  BY order_number, instance_name;

-- Every update of one trip, failures first
SELECT created_date, order_number, shipment, actual_ship_date_tz, status, error_message, app_user
FROM   wms_actual_shipdate
WHERE  trip_id = :trip_id
ORDER  BY CASE status WHEN 'FAILED' THEN 0 ELSE 1 END, created_date DESC;
