-- ============================================================================
-- GENERAL LEDGER CORE SCHEMA
-- Oracle General Ledger - Core GL Tables
-- Version: 1.0
-- Date: November 8, 2025
-- ============================================================================

-- ============================================================================
-- SECTION 1: LEDGER AND ACCOUNTING SETUP
-- ============================================================================

-- GL_LEDGERS: Stores ledger information
CREATE TABLE GL_LEDGERS (
    LEDGER_ID               NUMBER PRIMARY KEY,
    NAME                    VARCHAR2(100) NOT NULL UNIQUE,
    SHORT_NAME              VARCHAR2(30),
    DESCRIPTION             VARCHAR2(240),
    LEDGER_CATEGORY_CODE    VARCHAR2(30) CHECK (LEDGER_CATEGORY_CODE IN ('PRIMARY', 'SECONDARY', 'ALC')),
    CURRENCY_CODE           VARCHAR2(15) NOT NULL,
    CHART_OF_ACCOUNTS_ID    NUMBER NOT NULL,
    PERIOD_SET_NAME         VARCHAR2(15),
    ACCOUNTED_PERIOD_TYPE   VARCHAR2(15),
    ENABLED_FLAG            VARCHAR2(1) DEFAULT 'Y' CHECK (ENABLED_FLAG IN ('Y', 'N')),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL
);

CREATE SEQUENCE GL_LEDGERS_SEQ START WITH 1 INCREMENT BY 1;

-- GL_PERIOD_SETS: Stores calendar definitions
CREATE TABLE GL_PERIOD_SETS (
    PERIOD_SET_NAME         VARCHAR2(15) PRIMARY KEY,
    DESCRIPTION             VARCHAR2(240),
    FIRST_PERIOD_NAME       VARCHAR2(15),
    LAST_PERIOD_NAME        VARCHAR2(15),
    NUMBER_OF_PERIODS       NUMBER,
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL
);

-- GL_PERIOD_TYPES: Stores period type definitions
CREATE TABLE GL_PERIOD_TYPES (
    PERIOD_TYPE             VARCHAR2(15) PRIMARY KEY,
    DESCRIPTION             VARCHAR2(240),
    NUMBER_PER_FISCAL_YEAR  NUMBER,
    YEAR_TYPE_NAME          VARCHAR2(15),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL
);

-- GL_PERIODS: Stores accounting period information
CREATE TABLE GL_PERIODS (
    PERIOD_SET_NAME         VARCHAR2(15) NOT NULL,
    PERIOD_NAME             VARCHAR2(15) NOT NULL,
    PERIOD_YEAR             NUMBER NOT NULL,
    PERIOD_NUM              NUMBER NOT NULL,
    QUARTER_NUM             NUMBER,
    START_DATE              DATE NOT NULL,
    END_DATE                DATE NOT NULL,
    PERIOD_TYPE             VARCHAR2(15) NOT NULL,
    ADJUSTMENT_PERIOD_FLAG  VARCHAR2(1) DEFAULT 'N' CHECK (ADJUSTMENT_PERIOD_FLAG IN ('Y', 'N')),
    YEAR_START_DATE         DATE,
    QUARTER_START_DATE      DATE,
    ENABLED_FLAG            VARCHAR2(1) DEFAULT 'Y' CHECK (ENABLED_FLAG IN ('Y', 'N')),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_PERIODS_PK PRIMARY KEY (PERIOD_SET_NAME, PERIOD_NAME),
    CONSTRAINT GL_PERIODS_FK1 FOREIGN KEY (PERIOD_SET_NAME) REFERENCES GL_PERIOD_SETS(PERIOD_SET_NAME),
    CONSTRAINT GL_PERIODS_FK2 FOREIGN KEY (PERIOD_TYPE) REFERENCES GL_PERIOD_TYPES(PERIOD_TYPE)
);

-- GL_PERIOD_STATUSES: Stores period status by ledger
CREATE TABLE GL_PERIOD_STATUSES (
    LEDGER_ID               NUMBER NOT NULL,
    PERIOD_NAME             VARCHAR2(15) NOT NULL,
    PERIOD_YEAR             NUMBER NOT NULL,
    PERIOD_NUM              NUMBER NOT NULL,
    CLOSING_STATUS          VARCHAR2(1) CHECK (CLOSING_STATUS IN ('O', 'C', 'P', 'N')), -- O=Open, C=Closed, P=Perm Closed, N=Never Opened
    ADJUSTMENT_PERIOD_FLAG  VARCHAR2(1) DEFAULT 'N' CHECK (ADJUSTMENT_PERIOD_FLAG IN ('Y', 'N')),
    EFFECTIVE_PERIOD_NUM    NUMBER,
    START_DATE              DATE NOT NULL,
    END_DATE                DATE NOT NULL,
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_PERIOD_STATUSES_PK PRIMARY KEY (LEDGER_ID, PERIOD_NAME),
    CONSTRAINT GL_PERIOD_STATUSES_FK1 FOREIGN KEY (LEDGER_ID) REFERENCES GL_LEDGERS(LEDGER_ID)
);

CREATE INDEX GL_PERIOD_STATUSES_N1 ON GL_PERIOD_STATUSES(CLOSING_STATUS);

-- ============================================================================
-- SECTION 2: CHART OF ACCOUNTS
-- ============================================================================

-- GL_CODE_COMBINATIONS: Stores valid account combinations
CREATE TABLE GL_CODE_COMBINATIONS (
    CODE_COMBINATION_ID     NUMBER PRIMARY KEY,
    CHART_OF_ACCOUNTS_ID    NUMBER NOT NULL,
    SEGMENT1                VARCHAR2(30), -- Company
    SEGMENT2                VARCHAR2(30), -- Cost Center
    SEGMENT3                VARCHAR2(30), -- Account
    SEGMENT4                VARCHAR2(30), -- Sub Account
    SEGMENT5                VARCHAR2(30), -- Product
    SEGMENT6                VARCHAR2(30), -- Future Use
    SEGMENT7                VARCHAR2(30), -- Future Use
    SEGMENT8                VARCHAR2(30), -- Future Use
    CONCATENATED_SEGMENTS   VARCHAR2(240),
    ENABLED_FLAG            VARCHAR2(1) DEFAULT 'Y' CHECK (ENABLED_FLAG IN ('Y', 'N')),
    START_DATE_ACTIVE       DATE,
    END_DATE_ACTIVE         DATE,
    SUMMARY_FLAG            VARCHAR2(1) DEFAULT 'N' CHECK (SUMMARY_FLAG IN ('Y', 'N')),
    DETAIL_BUDGETING_ALLOWED VARCHAR2(1) DEFAULT 'Y' CHECK (DETAIL_BUDGETING_ALLOWED IN ('Y', 'N')),
    DETAIL_POSTING_ALLOWED  VARCHAR2(1) DEFAULT 'Y' CHECK (DETAIL_POSTING_ALLOWED IN ('Y', 'N')),
    ACCOUNT_TYPE            VARCHAR2(1) CHECK (ACCOUNT_TYPE IN ('A', 'L', 'O', 'R', 'E')), -- Asset, Liability, Owners Equity, Revenue, Expense
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL
);

CREATE SEQUENCE GL_CODE_COMBINATIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX GL_CODE_COMBINATIONS_N1 ON GL_CODE_COMBINATIONS(CHART_OF_ACCOUNTS_ID);
CREATE INDEX GL_CODE_COMBINATIONS_N2 ON GL_CODE_COMBINATIONS(SEGMENT1, SEGMENT2, SEGMENT3);
CREATE INDEX GL_CODE_COMBINATIONS_N3 ON GL_CODE_COMBINATIONS(CONCATENATED_SEGMENTS);

-- ============================================================================
-- SECTION 3: JOURNAL ENTRY TABLES
-- ============================================================================

-- GL_JE_SOURCES: Stores journal source names
CREATE TABLE GL_JE_SOURCES (
    JE_SOURCE_NAME          VARCHAR2(25) PRIMARY KEY,
    DESCRIPTION             VARCHAR2(240),
    USER_JE_SOURCE_NAME     VARCHAR2(25),
    LANGUAGE                VARCHAR2(4) DEFAULT 'US',
    IMPORT_ALLOWED_FLAG     VARCHAR2(1) DEFAULT 'Y' CHECK (IMPORT_ALLOWED_FLAG IN ('Y', 'N')),
    FREEZE_FLAG             VARCHAR2(1) DEFAULT 'N' CHECK (FREEZE_FLAG IN ('Y', 'N')),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL
);

-- GL_JE_CATEGORIES: Stores journal category names
CREATE TABLE GL_JE_CATEGORIES (
    JE_CATEGORY_NAME        VARCHAR2(25) PRIMARY KEY,
    DESCRIPTION             VARCHAR2(240),
    USER_JE_CATEGORY_NAME   VARCHAR2(25),
    LANGUAGE                VARCHAR2(4) DEFAULT 'US',
    CONSOLIDATION_FLAG      VARCHAR2(1) DEFAULT 'N' CHECK (CONSOLIDATION_FLAG IN ('Y', 'N')),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL
);

-- GL_JE_BATCHES: Stores journal entry batches
CREATE TABLE GL_JE_BATCHES (
    JE_BATCH_ID             NUMBER PRIMARY KEY,
    LEDGER_ID               NUMBER NOT NULL,
    NAME                    VARCHAR2(100) NOT NULL,
    DESCRIPTION             VARCHAR2(240),
    STATUS                  VARCHAR2(1) CHECK (STATUS IN ('U', 'P', 'S', 'I')), -- Unposted, Posted, Selected, In Process
    DEFAULT_PERIOD_NAME     VARCHAR2(15),
    POSTING_RUN_ID          NUMBER,
    APPROVAL_STATUS_CODE    VARCHAR2(30) CHECK (APPROVAL_STATUS_CODE IN ('A', 'R', 'P')), -- Approved, Rejected, Pending
    BUDGET_VERSION_ID       NUMBER,
    CONTROL_TOTAL           NUMBER,
    RUNNING_TOTAL_DR        NUMBER DEFAULT 0,
    RUNNING_TOTAL_CR        NUMBER DEFAULT 0,
    RUNNING_TOTAL_ACCOUNTED_DR NUMBER DEFAULT 0,
    RUNNING_TOTAL_ACCOUNTED_CR NUMBER DEFAULT 0,
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_JE_BATCHES_FK1 FOREIGN KEY (LEDGER_ID) REFERENCES GL_LEDGERS(LEDGER_ID)
);

CREATE SEQUENCE GL_JE_BATCHES_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX GL_JE_BATCHES_N1 ON GL_JE_BATCHES(LEDGER_ID);
CREATE INDEX GL_JE_BATCHES_N2 ON GL_JE_BATCHES(STATUS);
CREATE INDEX GL_JE_BATCHES_N3 ON GL_JE_BATCHES(NAME);

-- GL_JE_HEADERS: Stores journal entry headers
CREATE TABLE GL_JE_HEADERS (
    JE_HEADER_ID            NUMBER PRIMARY KEY,
    JE_BATCH_ID             NUMBER NOT NULL,
    LEDGER_ID               NUMBER NOT NULL,
    NAME                    VARCHAR2(100) NOT NULL,
    DESCRIPTION             VARCHAR2(240),
    PERIOD_NAME             VARCHAR2(15) NOT NULL,
    POSTED_DATE             DATE,
    STATUS                  VARCHAR2(1) CHECK (STATUS IN ('U', 'P', 'S', 'I')), -- Unposted, Posted, Selected, In Process
    JE_SOURCE               VARCHAR2(25) NOT NULL,
    JE_CATEGORY             VARCHAR2(25) NOT NULL,
    CURRENCY_CODE           VARCHAR2(15) NOT NULL,
    ACTUAL_FLAG             VARCHAR2(1) DEFAULT 'A' CHECK (ACTUAL_FLAG IN ('A', 'B', 'E')), -- Actual, Budget, Encumbrance
    ACCRUAL_REV_FLAG        VARCHAR2(1) CHECK (ACCRUAL_REV_FLAG IN ('Y', 'N')),
    ACCRUAL_REV_EFFECTIVE_DATE DATE,
    ACCRUAL_REV_JE_HEADER_ID NUMBER,
    EXTERNAL_REFERENCE      VARCHAR2(240),
    REVERSED_JE_HEADER_ID   NUMBER,
    REVERSAL_FLAG           VARCHAR2(1) CHECK (REVERSAL_FLAG IN ('Y', 'N')),
    REVERSAL_METHOD         VARCHAR2(30),
    REVERSAL_PERIOD_NAME    VARCHAR2(15),
    DOC_SEQUENCE_ID         NUMBER,
    DOC_SEQUENCE_VALUE      NUMBER,
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_JE_HEADERS_FK1 FOREIGN KEY (JE_BATCH_ID) REFERENCES GL_JE_BATCHES(JE_BATCH_ID),
    CONSTRAINT GL_JE_HEADERS_FK2 FOREIGN KEY (LEDGER_ID) REFERENCES GL_LEDGERS(LEDGER_ID),
    CONSTRAINT GL_JE_HEADERS_FK3 FOREIGN KEY (JE_SOURCE) REFERENCES GL_JE_SOURCES(JE_SOURCE_NAME),
    CONSTRAINT GL_JE_HEADERS_FK4 FOREIGN KEY (JE_CATEGORY) REFERENCES GL_JE_CATEGORIES(JE_CATEGORY_NAME)
);

CREATE SEQUENCE GL_JE_HEADERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX GL_JE_HEADERS_N1 ON GL_JE_HEADERS(JE_BATCH_ID);
CREATE INDEX GL_JE_HEADERS_N2 ON GL_JE_HEADERS(LEDGER_ID);
CREATE INDEX GL_JE_HEADERS_N3 ON GL_JE_HEADERS(PERIOD_NAME);
CREATE INDEX GL_JE_HEADERS_N4 ON GL_JE_HEADERS(STATUS);
CREATE INDEX GL_JE_HEADERS_N5 ON GL_JE_HEADERS(NAME);

-- GL_JE_LINES: Stores journal entry lines
CREATE TABLE GL_JE_LINES (
    JE_HEADER_ID            NUMBER NOT NULL,
    JE_LINE_NUM             NUMBER NOT NULL,
    CODE_COMBINATION_ID     NUMBER NOT NULL,
    PERIOD_NAME             VARCHAR2(15) NOT NULL,
    EFFECTIVE_DATE          DATE,
    STATUS                  VARCHAR2(1) CHECK (STATUS IN ('U', 'P')), -- Unposted, Posted
    ENTERED_DR              NUMBER,
    ENTERED_CR              NUMBER,
    ACCOUNTED_DR            NUMBER,
    ACCOUNTED_CR            NUMBER,
    DESCRIPTION             VARCHAR2(240),
    REFERENCE_1             VARCHAR2(100),
    REFERENCE_2             VARCHAR2(100),
    REFERENCE_3             VARCHAR2(100),
    REFERENCE_4             VARCHAR2(240),
    REFERENCE_5             VARCHAR2(240),
    ATTRIBUTE1              VARCHAR2(150), -- Descriptive Flexfield
    ATTRIBUTE2              VARCHAR2(150),
    ATTRIBUTE3              VARCHAR2(150),
    ATTRIBUTE4              VARCHAR2(150),
    ATTRIBUTE5              VARCHAR2(150),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_JE_LINES_PK PRIMARY KEY (JE_HEADER_ID, JE_LINE_NUM),
    CONSTRAINT GL_JE_LINES_FK1 FOREIGN KEY (JE_HEADER_ID) REFERENCES GL_JE_HEADERS(JE_HEADER_ID),
    CONSTRAINT GL_JE_LINES_FK2 FOREIGN KEY (CODE_COMBINATION_ID) REFERENCES GL_CODE_COMBINATIONS(CODE_COMBINATION_ID),
    CONSTRAINT GL_JE_LINES_CHK1 CHECK ((ENTERED_DR IS NOT NULL AND ENTERED_CR IS NULL) OR (ENTERED_DR IS NULL AND ENTERED_CR IS NOT NULL))
);

CREATE INDEX GL_JE_LINES_N1 ON GL_JE_LINES(CODE_COMBINATION_ID);
CREATE INDEX GL_JE_LINES_N2 ON GL_JE_LINES(PERIOD_NAME);

-- ============================================================================
-- SECTION 4: BALANCE TABLES
-- ============================================================================

-- GL_BALANCES: Stores account balances
CREATE TABLE GL_BALANCES (
    LEDGER_ID               NUMBER NOT NULL,
    CODE_COMBINATION_ID     NUMBER NOT NULL,
    CURRENCY_CODE           VARCHAR2(15) NOT NULL,
    PERIOD_NAME             VARCHAR2(15) NOT NULL,
    PERIOD_YEAR             NUMBER NOT NULL,
    PERIOD_NUM              NUMBER NOT NULL,
    ACTUAL_FLAG             VARCHAR2(1) NOT NULL CHECK (ACTUAL_FLAG IN ('A', 'B', 'E')),
    BEGIN_BALANCE_DR        NUMBER DEFAULT 0,
    BEGIN_BALANCE_CR        NUMBER DEFAULT 0,
    PERIOD_NET_DR           NUMBER DEFAULT 0,
    PERIOD_NET_CR           NUMBER DEFAULT 0,
    QUARTER_TO_DATE_DR      NUMBER DEFAULT 0,
    QUARTER_TO_DATE_CR      NUMBER DEFAULT 0,
    YEAR_TO_DATE_DR         NUMBER DEFAULT 0,
    YEAR_TO_DATE_CR         NUMBER DEFAULT 0,
    PROJECT_TO_DATE_DR      NUMBER DEFAULT 0,
    PROJECT_TO_DATE_CR      NUMBER DEFAULT 0,
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_BALANCES_PK PRIMARY KEY (LEDGER_ID, CODE_COMBINATION_ID, CURRENCY_CODE, PERIOD_NAME, ACTUAL_FLAG),
    CONSTRAINT GL_BALANCES_FK1 FOREIGN KEY (LEDGER_ID) REFERENCES GL_LEDGERS(LEDGER_ID),
    CONSTRAINT GL_BALANCES_FK2 FOREIGN KEY (CODE_COMBINATION_ID) REFERENCES GL_CODE_COMBINATIONS(CODE_COMBINATION_ID)
);

CREATE INDEX GL_BALANCES_N1 ON GL_BALANCES(CODE_COMBINATION_ID);
CREATE INDEX GL_BALANCES_N2 ON GL_BALANCES(PERIOD_NAME);

-- GL_DAILY_BALANCES: Stores daily balances
CREATE TABLE GL_DAILY_BALANCES (
    LEDGER_ID               NUMBER NOT NULL,
    CODE_COMBINATION_ID     NUMBER NOT NULL,
    CURRENCY_CODE           VARCHAR2(15) NOT NULL,
    PERIOD_NAME             VARCHAR2(15) NOT NULL,
    ACCOUNTING_DATE         DATE NOT NULL,
    ACTUAL_FLAG             VARCHAR2(1) NOT NULL CHECK (ACTUAL_FLAG IN ('A', 'B', 'E')),
    BEGIN_BALANCE_DR        NUMBER DEFAULT 0,
    BEGIN_BALANCE_CR        NUMBER DEFAULT 0,
    PERIOD_NET_DR           NUMBER DEFAULT 0,
    PERIOD_NET_CR           NUMBER DEFAULT 0,
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_DAILY_BALANCES_PK PRIMARY KEY (LEDGER_ID, CODE_COMBINATION_ID, CURRENCY_CODE, ACCOUNTING_DATE, ACTUAL_FLAG)
);

-- ============================================================================
-- SECTION 5: BUDGET TABLES
-- ============================================================================

-- GL_BUDGETS: Stores budget definitions
CREATE TABLE GL_BUDGETS (
    BUDGET_VERSION_ID       NUMBER PRIMARY KEY,
    LEDGER_ID               NUMBER NOT NULL,
    BUDGET_NAME             VARCHAR2(15) NOT NULL,
    DESCRIPTION             VARCHAR2(240),
    STATUS                  VARCHAR2(1) CHECK (STATUS IN ('O', 'F', 'C')), -- Open, Frozen, Current
    DATE_OPENED             DATE,
    DATE_CLOSED             DATE,
    BUDGET_TYPE             VARCHAR2(1) CHECK (BUDGET_TYPE IN ('S', 'F')), -- Standard, Financial Planning
    FIRST_VALID_PERIOD_NAME VARCHAR2(15),
    LAST_VALID_PERIOD_NAME  VARCHAR2(15),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_BUDGETS_FK1 FOREIGN KEY (LEDGER_ID) REFERENCES GL_LEDGERS(LEDGER_ID)
);

CREATE SEQUENCE GL_BUDGETS_SEQ START WITH 1 INCREMENT BY 1;

-- ============================================================================
-- SECTION 6: INTERFACE TABLES
-- ============================================================================

-- GL_INTERFACE: Interface table for importing journals
CREATE TABLE GL_INTERFACE (
    INTERFACE_ID            NUMBER PRIMARY KEY,
    STATUS                  VARCHAR2(30) CHECK (STATUS IN ('NEW', 'PENDING', 'POSTED', 'ERROR')),
    LEDGER_ID               NUMBER NOT NULL,
    USER_JE_SOURCE_NAME     VARCHAR2(25) NOT NULL,
    USER_JE_CATEGORY_NAME   VARCHAR2(25) NOT NULL,
    ACCOUNTING_DATE         DATE NOT NULL,
    CURRENCY_CODE           VARCHAR2(15) NOT NULL,
    DATE_CREATED            DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    ACTUAL_FLAG             VARCHAR2(1) DEFAULT 'A',
    SEGMENT1                VARCHAR2(30),
    SEGMENT2                VARCHAR2(30),
    SEGMENT3                VARCHAR2(30),
    SEGMENT4                VARCHAR2(30),
    SEGMENT5                VARCHAR2(30),
    SEGMENT6                VARCHAR2(30),
    SEGMENT7                VARCHAR2(30),
    SEGMENT8                VARCHAR2(30),
    ENTERED_DR              NUMBER,
    ENTERED_CR              NUMBER,
    ACCOUNTED_DR            NUMBER,
    ACCOUNTED_CR            NUMBER,
    REFERENCE1              VARCHAR2(100),
    REFERENCE2              VARCHAR2(100),
    REFERENCE3              VARCHAR2(100),
    REFERENCE4              VARCHAR2(240),
    REFERENCE5              VARCHAR2(240),
    REFERENCE10             VARCHAR2(240),
    GROUP_ID                NUMBER,
    REQUEST_ID              NUMBER,
    PERIOD_NAME             VARCHAR2(15),
    CHART_OF_ACCOUNTS_ID    NUMBER,
    ERROR_MESSAGE           VARCHAR2(500)
);

CREATE SEQUENCE GL_INTERFACE_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX GL_INTERFACE_N1 ON GL_INTERFACE(STATUS);
CREATE INDEX GL_INTERFACE_N2 ON GL_INTERFACE(GROUP_ID);

-- ============================================================================
-- SECTION 7: CURRENCY TABLES
-- ============================================================================

-- FND_CURRENCIES: Stores currency definitions
CREATE TABLE FND_CURRENCIES (
    CURRENCY_CODE           VARCHAR2(15) PRIMARY KEY,
    CURRENCY_NAME           VARCHAR2(60),
    DESCRIPTION             VARCHAR2(240),
    PRECISION               NUMBER DEFAULT 2,
    ENABLED_FLAG            VARCHAR2(1) DEFAULT 'Y' CHECK (ENABLED_FLAG IN ('Y', 'N')),
    START_DATE_ACTIVE       DATE,
    END_DATE_ACTIVE         DATE,
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL
);

-- GL_DAILY_RATES: Stores daily currency exchange rates
CREATE TABLE GL_DAILY_RATES (
    FROM_CURRENCY           VARCHAR2(15) NOT NULL,
    TO_CURRENCY             VARCHAR2(15) NOT NULL,
    CONVERSION_DATE         DATE NOT NULL,
    CONVERSION_TYPE         VARCHAR2(30) NOT NULL,
    CONVERSION_RATE         NUMBER NOT NULL,
    STATUS_CODE             VARCHAR2(15),
    CREATION_DATE           DATE NOT NULL,
    CREATED_BY              NUMBER NOT NULL,
    LAST_UPDATE_DATE        DATE NOT NULL,
    LAST_UPDATED_BY         NUMBER NOT NULL,
    CONSTRAINT GL_DAILY_RATES_PK PRIMARY KEY (FROM_CURRENCY, TO_CURRENCY, CONVERSION_DATE, CONVERSION_TYPE),
    CONSTRAINT GL_DAILY_RATES_FK1 FOREIGN KEY (FROM_CURRENCY) REFERENCES FND_CURRENCIES(CURRENCY_CODE),
    CONSTRAINT GL_DAILY_RATES_FK2 FOREIGN KEY (TO_CURRENCY) REFERENCES FND_CURRENCIES(CURRENCY_CODE)
);

-- ============================================================================
-- SAMPLE DATA
-- ============================================================================

-- Insert default journal sources
INSERT INTO GL_JE_SOURCES (JE_SOURCE_NAME, DESCRIPTION, USER_JE_SOURCE_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('Manual', 'Manual journal entry', 'Manual', SYSDATE, 0, SYSDATE, 0);

INSERT INTO GL_JE_SOURCES (JE_SOURCE_NAME, DESCRIPTION, USER_JE_SOURCE_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('Payables', 'Accounts Payable', 'Payables', SYSDATE, 0, SYSDATE, 0);

INSERT INTO GL_JE_SOURCES (JE_SOURCE_NAME, DESCRIPTION, USER_JE_SOURCE_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('Receivables', 'Accounts Receivable', 'Receivables', SYSDATE, 0, SYSDATE, 0);

-- Insert default journal categories
INSERT INTO GL_JE_CATEGORIES (JE_CATEGORY_NAME, DESCRIPTION, USER_JE_CATEGORY_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('Adjustment', 'Adjustment', 'Adjustment', SYSDATE, 0, SYSDATE, 0);

INSERT INTO GL_JE_CATEGORIES (JE_CATEGORY_NAME, DESCRIPTION, USER_JE_CATEGORY_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('Accrual', 'Accrual', 'Accrual', SYSDATE, 0, SYSDATE, 0);

-- Insert common currencies
INSERT INTO FND_CURRENCIES (CURRENCY_CODE, CURRENCY_NAME, DESCRIPTION, PRECISION, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('USD', 'US Dollar', 'United States Dollar', 2, SYSDATE, 0, SYSDATE, 0);

INSERT INTO FND_CURRENCIES (CURRENCY_CODE, CURRENCY_NAME, DESCRIPTION, PRECISION, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('EUR', 'Euro', 'European Euro', 2, SYSDATE, 0, SYSDATE, 0);

INSERT INTO FND_CURRENCIES (CURRENCY_CODE, CURRENCY_NAME, DESCRIPTION, PRECISION, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('GBP', 'Pound Sterling', 'British Pound', 2, SYSDATE, 0, SYSDATE, 0);

-- Insert period type
INSERT INTO GL_PERIOD_TYPES (PERIOD_TYPE, DESCRIPTION, NUMBER_PER_FISCAL_YEAR, YEAR_TYPE_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY)
VALUES ('Month', 'Month', 12, 'Calendar', SYSDATE, 0, SYSDATE, 0);

COMMIT;

-- ============================================================================
-- END OF GL CORE SCHEMA
-- ============================================================================
