"""Copy the WMS screens WMS 2.0 reuses, VERBATIM, from wms/ into wms2/legacy/.

WMS 2.0 never edits these files: fix the original in wms/ and run this script again
(python wms2/legacy/copy-from-wms.py from the repo root). The line ranges below are the
WMS source as of this copy; check them after a big change in wms/app.js.

  trip-workspace.js  wms/app.js 5108-15807: the Trip Details page (openTripDetails, header actions
                     Refresh / Edit Trip / Assign Picker / Allocate Lots for S2V / Pick Release All /
                     All Shipment Lines / Show Lines / Get Profit Centers / Add Orders, per-row Move /
                     Remove / Print), the picker dialog, pick release with or without lots, print store
                     transaction, the order + store transaction dialogs (editTripOrder …), remove order,
                     activateTripTab — in one closure, like the DOMContentLoaded handler it comes from
  trip-details.js    wms/trip-details.js (Add Orders modal, paste orders, fetch pending shipments)
  trip-move.js       wms/trip-move.js (move an order to another trip)
  pickers.js         wms/pickers.js (loadPickers → window.pickersData)
  vehicles.js        wms/vehicles.js (loadVehicles → window.vehiclesData, lorry capacity)
  new-trip.js        wms/copilot.js 296-840 (Create New Trip modal)
  agent-assign.js    wms/shipping-agent.js 8, 89-126, 5524-5586, 5610-5613 (Add to Agent)
  markup.js          wms/index.html from <!-- Add Orders Modal --> to <!-- Edit Trip Modal --> (Add Orders / Paste /
                     Fetch pending shipments) and <!-- New Trip Modal --> to <!-- WMS Co-Pilot --> (New Trip)
  wms-legacy.css     the rules of wms/styles.css those screens use
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, 'wms2', 'legacy')


def lines(path):
    with open(os.path.join(ROOT, path), encoding='utf-8') as f:
        return f.read().split('\n')


def cut(src, a, b):
    return '\n'.join(src[a - 1:b])


def write(name, text):
    with open(os.path.join(OUT, name), 'w', encoding='utf-8', newline='\n') as f:
        f.write(text.rstrip('\n') + '\n')


def head(what):
    return ('/* WMS 2.0 — VERBATIM COPY of ' + what + '.\n'
            '   Generated by wms2/legacy/copy-from-wms.py. The WMS module itself is not changed.\n'
            '   Do not edit: fix the original and run the script again. */\n')


app = lines('wms/app.js')
write('trip-workspace.js', head('wms/app.js lines 5108-15807 (Trip Details page, its actions and the order dialogs)') +
      '(function () {\n' + cut(app, 5108, 15807) + '\n})();')

for f in ['trip-details.js', 'trip-move.js', 'pickers.js', 'vehicles.js']:
    write(f, head('wms/' + f) + '\n'.join(lines('wms/' + f)))

cop = lines('wms/copilot.js')
write('new-trip.js', head('wms/copilot.js lines 296-840 (Create New Trip)') + cut(cop, 296, 840))

sa = lines('wms/shipping-agent.js')
write('agent-assign.js', head('wms/shipping-agent.js lines 8, 89-126, 5524-5586, 5610-5613 (Add to Agent)') +
      '(function () {\n    \'use strict\';\n' + cut(sa, 8, 8) + '\n' + cut(sa, 89, 126) + '\n' + cut(sa, 5524, 5586) + '\n' + cut(sa, 5610, 5613) +
      '\n    // the agent dashboard is not on this page\n    if (typeof window.saRefreshDashboard !== \'function\') window.saRefreshDashboard = function () { return Promise.resolve(); };\n})();')

html = lines('wms/index.html')
def between(lines_, start, stop):
    a = next(i for i, l in enumerate(lines_) if start in l)
    b = next(i for i in range(a + 1, len(lines_)) if stop in lines_[i])
    return '\n'.join(lines_[a:b]).rstrip()


# found by their comments, so edits elsewhere in wms/index.html do not shift them
markup = between(html, '<!-- Add Orders Modal -->', '<!-- Edit Trip Modal -->') + '\n' + between(html, '<!-- New Trip Modal -->', '<!-- WMS Co-Pilot -->')
write('markup.js', head('wms/index.html: Add Orders, Paste Orders, Fetch Pending Shipments and New Trip modals (found by their comments)') +
      '(function () {\n    var html = ' + json.dumps(markup) + ';\n'
      '    function put() { var d = document.createElement(\'div\'); d.id = \'w2-legacy-markup\'; d.innerHTML = html; document.body.appendChild(d); }\n'
      '    if (document.body) put(); else document.addEventListener(\'DOMContentLoaded\', put);\n})();')

# CSS: every rule of wms/styles.css whose selector names one of these classes (plain .btn is left to wms2.css)
css = '\n'.join(lines('wms/styles.css'))
css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)


def drop_at_blocks(text):  # @media / @supports: their rules would apply everywhere without the wrapper
    res, i = [], 0
    for m in re.finditer(r'@(media|supports)[^{]*\{', text):
        if m.start() < i:
            continue
        res.append(text[i:m.start()])
        depth, j = 1, m.end()
        while depth and j < len(text):
            depth += {'{': 1, '}': -1}.get(text[j], 0)
            j += 1
        i = j
    return ''.join(res) + text[i:]


keyframes = [m.group(0) for m in re.finditer(r'@keyframes\s+spin\s*\{(?:[^{}]*\{[^{}]*\})*\s*\}', css)]
css = re.sub(r'@keyframes[^{]*\{(?:[^{}]*\{[^{}]*\})*\s*\}', '', drop_at_blocks(css))
want = re.compile(r'\.(btn-(primary|secondary|danger|warning|success|info|sm)|modal|modal-(content|header|body|footer)|close-modal|form-group|form-control'
                  r'|tab-item|tab-pane|close-tab|order-trans-[\w-]+|store-trans-[\w-]+|spinner)\b')
out = []
for m in re.finditer(r'([^{}]+)\{([^{}]*)\}', css):
    sel = m.group(1).strip()
    if '@' in sel:
        continue
    if want.search(sel):
        out.append(sel + ' {' + m.group(2).rstrip() + '\n}')
out += keyframes[:1]
root = re.search(r':root\s*\{([^{}]*)\}', css)
used = sorted(set(re.findall(r'var\((--[\w-]+)\)', '\n'.join(out))))
decl = [d.strip() for d in (root.group(1).split(';') if root else []) if d.strip().split(':')[0].strip() in used]
out.insert(0, ':root {\n    ' + ';\n    '.join(decl) + ';\n}' if decl else '')
write('wms-legacy.css', '/* WMS 2.0 — VERBATIM COPY of the wms/styles.css rules the copied WMS screens use (generated by copy-from-wms.py).\n'
      '   Loaded after wms2.css: these classes are only used by the copied WMS screens. */\n' + '\n'.join(out))
print('copied into', OUT)
